####################################################
# INPUTS BOOLEAN                                   #
####################################################

  restart_hass:
    name: Restart HASS
    initial: off
    icon: mdi:autorenew
    
  running_hass:
    name: HASS is running
    initial: off
    icon: mdi:autorenew
    
  request_position:
    name: Request IOS positions
    initial: off
    icon: mdi:map-marker-radius
    
  force_reset_graphs:
    name: Force Reset Graphs
    initial: off
    icon: mdi:trending-up
    
  test_button:
    name: Test Button #do not leave in templates to prevent errors
    initial: off
    
  enable_flash:
    name: Flash Enable
    #initial: on
    icon: mdi:alarm-light
    
#Garden
  gardenirrigation_start30m:
    name: Garden Irrigation 30 minutes
    initial: off
    icon: mdi:clock-start
  gardenirrigation_start1h:
    name: Garden Irrigation 1 hour
    initial: off
    icon: mdi:clock-start
  gardenirrigation_cancel:
    name: Garden Irrigation Cancel
    initial: off
    icon: mdi:clock-start
    
  pondfiller_start30m:
    name: Pond Filler 30 minutes
    initial: off
    icon: mdi:clock-start
  pondfiller_start1h:
    name: Pond Filler 1 hour
    initial: off
    icon: mdi:clock-start
  pondfiller_start2h:
    name: Pond Filler 2 hour
    initial: off
    icon: mdi:clock-start
  pondfiller_cancel:
    name: Pond Filler Cancel
    initial: off
    icon: mdi:clock-start
    
#Control Panels reset
  control_room_control_reset:
    name: Control Room Control Reset
    initial: off
    icon: mdi:power-cycle
  garage_main_control_reset:
    name: Garage Main Reset
    initial: off
    icon: mdi:power-cycle
  garage_slave_control_reset:
    name: Garage Slave Reset
    initial: off
    icon: mdi:power-cycle
  pond_control_reset:
    name: Pond Control Reset
    initial: off
    icon: mdi:power-cycle
  pool_control_reset:
    name: Pool Control Reset
    initial: off
    icon: mdi:power-cycle
  weather_control_reset:
    name: Weather Control Reset
    initial: off
    icon: mdi:power-cycle
  shed_control_reset:
    name: Shed Control Reset
    initial: off
    icon: mdi:power-cycle
  glasshouse_control_reset:
    name: Glasshouse Control Reset
    initial: off
    icon: mdi:power-cycle
  pool_toilet_control_reset:
    name: Pool Toilet Control Reset
    initial: off
    icon: mdi:power-cycle
  transmitter_box_control_reset:
    name: Transmitter Box Control Reset
    initial: off
    icon: mdi:power-cycle
  well_control_reset:
    name: Well Control Reset
    initial: off
    icon: mdi:power-cycle

#Seasonal setups
  global_winterization:
    name: Global Winterization
    icon: mdi:snowflake
  pool_running:
    name: Pool Running
    icon: mdi:pool
  pond_running:
    name: Pond Running
    icon: mdi:fish

#House
  living_room_hvac_tilt:
    name: Living Room HVAC Tilt
    icon: mdi:arrow-expand-vertical
  recroom_hvac_tilt:
    name: RecRoom HVAC Tilt
    icon: mdi:arrow-expand-vertical
  storage_room_floor_air_temp:
    name: Storage Room sensing air
    icon: mdi:select-compare
  cold_storage_floor_air_temp:
    name: Cold Storage sensing air
    icon: mdi:select-compare
  lights_doors_alerts_pause_30min:
    name: Pause Light/Door alerts 30min
  
  doorbell_state:
    name: Doorbell State
  test_doorbell:
    name: Test Doorbell
    
#Garage
  garage_heaters:
    name: Garage Heaters
    icon: mdi:radiator
  garage_air_valve:
    name: Garage Air Valve
  house_air_valve:
    name: House Air Valve
  air_compressor_purge:
    name: Air Compressor Purge
    
#Pool
  poolpump_force_off:
    name: Pond Running
    icon: mdi:pump

  findphone_button:
    name: Find My Phone
    initial: off
    icon: mdi:cellphone

  storage_room_door:
  