####################################################
# UILOVELACE - PEOPLE                              #
####################################################

- title: People
  icon: mdi:account-group
  # Unique path for direct access /lovelace/${path}
  path: people
  visible: true
  badges:
    - sensor.time
    - device_tracker.life360_jean
    - device_tracker.life360_cindy
  cards:
  # Entities card will take a list of entities and show their state.
  # The entities here will be shown in the same order as specified.
  # Each entry is an entity ID or a map with extra options.
    - type: custom:bignumber-card
      entity: sensor.dates
      scale: 25px
      
    - type: entities
      title: "House Birthdays"
      show_header_toggle: false
      entities:
        - sensor.party_18_ans_cody
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.jean_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.cindy_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.cody_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.mi_loup_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        
    - type: entities
      title: "Jean's Family Birthdays"
      show_header_toggle: false
      entities:
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.michel_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.suzanne_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.benoit_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
          
    - type: entities
      title: "Cindy's Family Birthdays"
      show_header_toggle: false
      entities:
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.gisele_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.roxanne_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.pierre_luc_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.kaleb_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.sabrina_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.frederick_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        
    - type: entities
      title: "Friends Birthdays"
      show_header_toggle: false
      entities:
        - type: "custom:secondaryinfo-entity-row"
          entity: sensor.mi_loup_s_birthday
          secondary_info: "Birthday: [[ {entity}.attributes.date ]] => [[ {entity}.attributes.current_years ]] y/o"
        