####################################################
# UILOVELACE - PARAMETERS                          #
####################################################

- title: Parameters
  icon: mdi:wrench
  # Unique path for direct access /lovelace/${path}
  path: params
  visible: true
  badges:
    - sensor.time
  cards:
    - type: entities
      title: TED5000
      show_header_toggle: false
      #state_color: true
      entities: 
        - sensor.ted5000_mtu1_power
        - sensor.ted5000_mtu2_power
        - sensor.ted5000_mtu3_power
        - binary_sensor.power_peakperiod
        
    - type: entities
      title: Cold Storage
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: binary_sensor.control_room_light
          entities:
            - automation.cold_storage_light_on_immediate
            - automation.cold_storage_light_on_repetitive
        - type: custom:fold-entity-row
          head: binary_sensor.control_room_door
          entities:
            - automation.cold_storage_door_on_immediate
            - automation.cold_storage_door_on_repetitive

    - type: entities
      title: Water Entrance
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.water_valve_status
          entities:
            - type: "custom:button-entity-row"
              buttons:
                - entity: switch.water_valve_open
                  name: Turn ON
                - entity: switch.water_valve_close
                  name: Turn OFF
            - type: custom:fold-entity-row
              head:
                type: section
                label: Automations
              entities:
                - automation.water_valve_force_off
                - automation.water_valve_off
                - automation.water_valve_on
        - type: custom:fold-entity-row
          head: sensor.water_heater_status
          entities:
            - switch.water_heater
            - sensor.water_heater_temperature
            - sensor.water_heater_flow
        
    - type: entities
      title: Control Room Cabinet Status
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.control_room_control_status
          entities:
            - sensor.cold_storage_temperature
            - sensor.cold_storage_humidity
            - sensor.control_room_box_temperature
            - sensor.control_room_box_humidity
            - sensor.control_room_12v_voltage
            - sensor.control_room_5v_voltage
            - type: "custom:button-entity-row"
              buttons:
                - entity: input_boolean.control_room_control_reset
                  name: RESET
                  icon: "mdi:power-cycle"
        - type: custom:fold-entity-row
          head: sensor.shed_control_status
          entities:
            - sensor.shed_box_temperature
            - sensor.shed_box_humidity
            - sensor.shed_12v_voltage
            - sensor.shed_5v_voltage
            - type: "custom:button-entity-row"
              buttons:
                - entity: input_boolean.shed_control_reset
                  name: RESET
                  icon: "mdi:power-cycle"
                  
    - type: entities
      title: Clocks
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.nixie_clock
          entities:
            - sensor.nixie_clock_case_temp
            - light.nixie_clock
            - light.nixie_clock_rgb
            - switch.nixie_hour_mode
            - switch.nixie_blank_leading_zero
            - switch.nixie_enable_scroll_back
            - switch.nixie_slots_mode
            - switch.nixie_use_fading
            - switch.nixie_use_ldr
            - switch.nixie_suppress_acp
        - type: custom:fold-entity-row
          head: sensor.stepper_wall_clock
          entities:
            - switch.stepper_wall_clock_homed

    - type: entities
      title: Beds
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.master_bed_presence
          entities:
            - sensor.master_bed_raw
            - switch.master_bed_tare
