####################################################
# UILOVELACE - HA Server                           #
####################################################

- title: HA Server
  icon: mdi:home-assistant
  # Unique path for direct access /lovelace/${path}
  path: settings
  visible: true
  badges:
    - sensor.time
    - input_boolean.restart_hass
    - sensor.time_online
    - sensor.server_cpu_temperature_temp
    - sensor.server_used_percent
    - binary_sensor.ha_update_available
    - sensor.ha_installed_version
  cards:
    - type: entities
      title: Health Data
      show_header_toggle: false
      entities:
        - sensor.date_time
        - sensor.last_boot
        - sensor.time_online
        - binary_sensor.ha_update_available
        - binary_sensor.remote_ui
        - !include /config/UILovelaceCards/entities.yaml
        
    # - type: 'custom:monster-card'
      # show_empty: true
      # card:
        # type: entities
        # title: Air quality
        # show_header_toggle: false
      # filter:
        # exclude:
          # - state: unavailable
        # include:
          # - entity_id: "sensor.*status*"
        
    - type: entities
      title: Resources
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.server_cpu_temperature_temp
          entities:
            - sensor.server_k8temp_1_temp
            - sensor.server_k8temp_2_temp
            - sensor.server_k8temp_3_temp
            - sensor.server_k8temp_4_temp
        - type: custom:fold-entity-row
          head: sensor.server_mb_temperature_temp
          entities:
            - sensor.server_mb_temperature_temp
        - type: custom:fold-entity-row
          head: sensor.server_running
          entities:
            - sensor.server_sleeping
            - sensor.server_total
            - sensor.server_thread
        - type: custom:fold-entity-row
          head: sensor.server_cpu_used
          entities:
            - sensor.load_1m
            - sensor.load_15m
        - type: custom:fold-entity-row
          head: sensor.server_ram_used_percent
          entities:
            - sensor.server_ram_used
            - sensor.server_ram_free
        - type: custom:fold-entity-row
          head: sensor.server_swap_used_percent
          entities:
            - sensor.server_swap_used
            - sensor.server_swap_free
        
    - type: entities
      title: Storage
      show_header_toggle: false
      entities:
        - sensor.home_assistant_v2_db
        - type: custom:fold-entity-row
          head: sensor.server_used_percent
          entities:
            - sensor.server_used
            - sensor.server_free
        - type: custom:fold-entity-row
          head: sensor.server_media_gauthier_data01_used_percent
          entities:
            - sensor.server_media_gauthier_data01_used
            - sensor.server_media_gauthier_data01_free

    - type: entities
      title: Network
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.network_throughput_in_hassio
          entities:
            - sensor.network_in_hassio
            - sensor.packets_in_hassio
        - type: custom:fold-entity-row
          head: sensor.network_throughput_out_hassio
          entities:
            - sensor.network_out_hassio
            - sensor.packets_out_hassio
        - type: custom:fold-entity-row
          head: sensor.network_throughput_in_enp1s6
          entities:
            - sensor.network_in_enp1s6
            - sensor.packets_in_enp1s6
        - type: custom:fold-entity-row
          head: sensor.network_throughput_out_enp1s6
          entities:
            - sensor.network_out_enp1s6
            - sensor.packets_out_enp1s6
            
    - type: entities
      title: Battery Back-UPS
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.ups_status
          entities:
            - sensor.ups_startup_time
            - sensor.ups_status_date
            - sensor.ups_status_data
            - sensor.ups_input_voltage
            - sensor.ups_load
        - type: custom:fold-entity-row
          head: sensor.ups_battery
          entities:
            - sensor.ups_time_left
            - sensor.ups_shutdown_time
            - sensor.ups_battery_voltage
            - sensor.ups_battery_nominal_voltage
            - sensor.ups_battery_shutdown
            - sensor.ups_battery_timeout
        - type: custom:fold-entity-row
          head: sensor.ups_transfer_count
          entities:
            - sensor.ups_time_on_battery
            - sensor.ups_total_time_on_battery
            - sensor.ups_transfer_low
            - sensor.ups_transfer_high
            - sensor.ups_transfer_from_battery
            - sensor.ups_last_transfer
        - type: custom:fold-entity-row
          head: sensor.ups_model
          entities:
            - sensor.ups_name
            - sensor.ups_hostname
            - sensor.ups_nominal_input_voltage
            - sensor.ups_nominal_output_power
            - sensor.ups_battery_nominal_voltage
            - sensor.ups_daemon_info
            - sensor.ups_cable_type
            - sensor.ups_battery_replaced
        
    - type: history-graph
      title: Speed Tests
      entities:
        - entity: sensor.speedtest_ping
          name: Ping Response
        - entity: sensor.speedtest_download
          name: Download Speed
        - entity: sensor.speedtest_upload
          name: Upload Speed

    - type: vertical-stack
      title: Hardware
      cards:
        - type: horizontal-stack
          cards:
            - type: gauge
              name: CPU
              unit: '%'
              entity: sensor.server_cpu_used
              theme: th_gauge_3
              severity:
                green: 0
                yellow: 45
                red: 85
            - type: gauge
              name: Disk
              unit: '%'
              entity: sensor.server_used_percent
              theme: th_gauge_3
              severity:
                green: 0
                yellow: 45
                red: 85
            - type: gauge
              name: Memory
              unit: '%'
              entity: sensor.server_ram_used_percent
              theme: th_gauge_3
              severity:
                green: 0
                yellow: 45
                red: 85
        - type: horizontal-stack
          cards:
            - type: gauge
              name: UPS Battery
              unit: '%'
              entity: sensor.ups_battery
              theme: th_gauge_3
              severity:
                green: 70
                yellow: 45
                red: 0
            - type: gauge
              name: UPS Load
              unit: '%'
              entity: sensor.ups_load
              theme: th_gauge_3
              severity:
                green: 0
                yellow: 20
                red: 30
