####################################################
# UILOVELACE - DEV (INVISIBLE ICON)                #
####################################################

- title: Dev
  icon: mdi:hidden
  # Unique path for direct access /lovelace/${path}
  path: dev
  visible:
    - user: !secret userid_jean
  badges:
    - sensor.time
  cards:
    - type: custom:state-element
      tap_action:
      action: toggle
      entity: sensor.dates
      style:
        font-size: 60px
        color: white
        top: 10%
        left: 10%
    # The markdown card will render markdown text.
    - type: markdown
      title: Lovelace
      content: >
        Welcome to your **Lovelace UI**.

    - type: entities
      title: Milight RGBW Controller
      show_header_toggle: false
      entities:     
        - type: custom:fold-entity-row
          head:
            type: section
            label: Milight Sync Function
          entities:
            - input_number.milight_id_sync
            - type: "custom:button-entity-row"
              buttons:
                - icon: mdi:help-circle
                  name: Generate Help Notification
                  service: script.turn_on
                  service_data:
                    entity_id: script.milightsynchelp
        - type: custom:fold-entity-row
          head: light.master_bedroom_rgbw
          entities:
            - cover.master_bedroom_rgbw
        - type: 'custom:text-divider-row'
          text: Test Row Divider
          style: |
            ha-card {
              --secondary-text-color: var(--primary-text-color);
            }
        - type: custom:fold-entity-row
          head: light.under_bar_rgbw
          entities:
            - cover.under_bar_rgbw
        - type: custom:fold-entity-row
          head: light.pool_water_rgb
          entities:
            - cover.pool_water_rgb
            
    - type: entities
      title: Shed Lights
      show_header_toggle: false
      entities:
        - switch.shed_door_light
        - switch.shed_inside_light
        - switch.shed_pool_light
            
    - type: entities
      title: Massage Room
      show_header_toggle: false
      entities:
        - sensor.massage_room_temp
        - sensor.massage_room_humidity
        - light.massage_clock_rgb
        - type: custom:fold-entity-row
          head: sensor.massage_room_status
          entities:
            - switch.massage_room_appliances
            - sensor.massage_room_power
            - sensor.massage_room_data
            # - type: custom:fold-entity-row
              # head:
                # type: section
                # label: Automations
              # entities:
                # - input_number.massage_room_appliances
                # - automation.shut_massage_room_warning
                # - automation.shut_massage_room_shutdown
    - type: light
      entity: light.massage_clock_rgb
        
    # - type: picture
      # name: Doorbell Camera
      # tap_action:
        # action: none
      # hold_action:
        # action: none
      # image: http://192.168.1.20/
            
    - type: entities
      title: Pool Valves
      show_header_toggle: false
      entities:
        - input_number.pool_drain_percent
        - input_number.pool_heater_percent
        - input_number.pool_slide_percent
        - input_select.pool_drain_skimmer_mode
        - input_select.pool_heater_mode
        - input_select.pool_slide_mode
        - switch.pool_control_valves
        
    - type: statistics-graph
      title: 'Test Graph'
      chart_type: line
      entities:
        - sensor.outdoor_temperature
        - entity: sensor.pool_cabin_temperature
          name: Pool Cabin Temperature
          
    - type: statistics-graph
      title: 'Test Graph Energy'
      chart_type: line
      #stat_types: sum
      entities:
        - entity: sensor.ted5000_mtu3_power
          name: Pool Power

    - type: statistics-graph
      title: 'Test Graph CPU Load'
      chart_type: line
      #stat_types: sum
      entities:
        - sensor.server_cpu_used

    - type: markdown
      title: Season
      card_size: 4
      content: |
        ## <div style="text-align: right"> {{ states('sensor.season') }} </div>
        <ha-icon icon={{ state_attr('sensor.season','icon') }} />

    # - type: custom:roomba-vacuum-card
    #   entity: vacuum.roomba_irobot
    #   #image: /local/img/different_vacuum.png
    #   name: Insatiable Suceuse
    #   clean_base: false

    # - type: custom:history-explorer-card
    #   cardName: historycard-67119468
    #   header: hide
    #   uiLayout:
    #     toolbar: top
    #     selector: bottom
    #   combineSameUnits: true
    #   showUnavailable: false
      
    - type: custom:history-explorer-card
      filterEntities:                     # Or use multiple filters, entities matching any of the filters will be added
        - '*power*'
        - 'sensor.*energy*'

    - type: custom:button-card
      entity: sensor.times
      show_label: true
      show_state: true
