####################################################
# UILOVELACE - ALARM                               #
####################################################

- title: Alarm
  icon: mdi:shield-home
  # Unique path for direct access /lovelace/${path}
  path: alarm
  visible: true
  badges:
    - sensor.time
  cards:
    - type: alarm-panel
      entity: alarm_control_panel.house
      name: Home Alarm
      states:
        - arm_home
        - arm_away
        - arm_night
        
    - type: alarm-panel
      entity: alarm_control_panel.garage
      name: Garage Alarm
      states:
        - arm_away
        
        