####################################################
# INPUT NUMBER                                     #
####################################################
    
  milight_id_sync:
    name: Milight ID to Sync (1-254)
    icon: mdi:sync
    mode: box
    initial: 0
    min: 0
    max: 254
    step: 1
    
  doorchime_tf_volume:
    name: Volume Top Floor
    icon: mdi:volume-high
    mode: slider
    #initial: 5
    min: 0
    max: 7
    step: 1
    
  doorchime_bf_volume:
    name: Volume Bottom Floor
    icon: mdi:volume-high
    mode: slider
    #initial: 5
    min: 0
    max: 7
    step: 1
    
  doorchime_gf_volume:
    name: Volume Garage
    icon: mdi:volume-high
    mode: slider
    #initial: 5
    min: 0
    max: 30
    step: 1

  soldering_station:
    name: Soldering Station Delay
    unit_of_measurement: 'min'
    icon: mdi:timer-sand
    mode: box
    #initial: 5
    min: 10
    max: 300
    step: 1
    
  garage_front_setpoint:
    name: Garage Front Temp Setpoint
    unit_of_measurement: °C
    icon: mdi:timer-sand
    mode: slider
    min: 7
    max: 30
    step: 1
    
  garage_rear_setpoint:
    name: Garage Rear Temp Setpoint
    unit_of_measurement: °C
    icon: mdi:timer-sand
    mode: slider
    min: 7
    max: 30
    step: 1
    
  air_compressor_purge:
    name: Air Compressor Purge Hold Time
    unit_of_measurement: 'sec'
    icon: mdi:timer-sand
    mode: box
    min: 0.5
    max: 30
    step: 0.5
    
  # issues_count:
    # name: Sensors that need attention
    # mode: box
    # min: 0
    # max: 9999
    # step: 1
    
  energy_tier2_threshold:
    name: Energy Tier 2 Threshold
    unit_of_measurement: kWh
    icon: mdi:cash-plus
    mode: box
    initial: 1219
    min: 0
    max: 100000
    step: 1
    
  drive_used_threshold:
    name: Drive Used High Threshold
    unit_of_measurement: '%'
    icon: mdi:harddisk-remove
    mode: box
    min: 5
    max: 100
    step: 5

  random_number_generator:
    name: Random Number Generator
    unit_of_measurement: '#'
    icon: mdi:counter
    mode: box
    min: 100000
    max: 999999
    step: 1
    initial: 100000
