####################################################
# INPUT NUMBER - GARAGE                            #
####################################################

  garage_clock_scroll_speed:
    name: Garage Text Scroll Speed
    mode: slider
    initial: 80
    min: 0
    max: 100
    step: 5
  garage_clock_trans_speed:
    name: Garage Color Cycle Speed
    mode: slider
    initial: 1
    min: 1
    max: 10
    step: 1
