####################################################
# INPUT NUMBER                                     #
####################################################
    
  milight_id_sync:
    name: Milight ID to Sync (1-254)
    icon: mdi:sync
    mode: box
    initial: 0
    min: 0
    max: 254
    step: 1
    
  doorchime_tf_volume:
    name: Volume
    icon: mdi:volume-high
    mode: slider
    #initial: 5
    min: 0
    max: 7
    step: 1
    
  doorchime_bf_volume:
    name: Volume
    icon: mdi:volume-high
    mode: slider
    #initial: 5
    min: 0
    max: 7
    step: 1
    
  doorchime_gf_volume:
    name: Volume
    icon: mdi:volume-high
    mode: slider
    #initial: 5
    min: 0
    max: 7
    step: 1

  soldering_station:
    name: Soldering Station Delay
    icon: mdi:timer-sand
    mode: box
    #initial: 5
    min: 10
    max: 300
    step: 1
    
  garage_front_setpoint:
    name: Garage Front Temp Setpoint
    icon: mdi:timer-sand
    mode: slider
    min: 7
    max: 30
    step: 1
    
  garage_rear_setpoint:
    name: Garage Rear Temp Setpoint
    icon: mdi:timer-sand
    mode: slider
    min: 7
    max: 30
    step: 1
    
  air_compressor_purge:
    name: Air Compressor Purge Hold Time
    icon: mdi:timer-sand
    mode: box
    min: 0.5
    max: 30
    step: 0.5
    
  # issues_count:
    # name: Sensors that need attention
    # mode: box
    # min: 0
    # max: 9999
    # step: 1