####################################################
# INPUT NUMBER - POOL                              #
####################################################

  pool_heater_setpoint:
    name: Pool Heater Setpoint
    unit_of_measurement: '° F'
    mode: slider
    #initial: 85
    min: 80
    max: 95
    step: 1

  pool_drain_percent:
    name: Pool Drain Percent (Drain / Skim)
    unit_of_measurement: '%'
    mode: slider
    #initial: 50
    min: 0
    max: 100
    step: 50
  pool_heater_percent:
    name: Pool Heater Percent
    unit_of_measurement: '%'
    mode: slider
    #initial: 50
    min: 0
    max: 100
    step: 100
  pool_slide_percent:
    name: Pool Slide Percent
    unit_of_measurement: '%'
    mode: slider
    #initial: 50
    min: 0
    max: 100
    step: 50
    
  pool_clock_scroll_speed:
    name: Pool Text Scroll Speed
    mode: slider
    initial: 80
    min: 0
    max: 100
    step: 5
  pool_clock_trans_speed:
    name: Pool Color Cycle Speed
    mode: slider
    initial: 1
    min: 1
    max: 10
    step: 1
    
  pool_filler_start:
    name: Pool Filler Start
    unit_of_measurement: 'min'
    mode: slider
    #initial: 5
    min: 2
    max: 15
    step: 1
  pool_filler_stop:
    name: Pool Filler Stop
    unit_of_measurement: 'min'
    mode: slider
    #initial: 5
    min: 2
    max: 15
    step: 1
  pool_filler_runtime:
    name: Pool Filler Daily Max
    unit_of_measurement: 'min'
    mode: slider
    #initial: 60
    min: -1
    max: 180
    step: 1
    