####################################################
# INPUT NUMBER - POND                              #
####################################################

  pond_filler_start:
    name: Pond Filler Start
    unit_of_measurement: 'min'
    mode: slider
    #initial: 5
    min: 2
    max: 15
    step: 1
  pond_filler_stop:
    name: Pond Filler Stop
    unit_of_measurement: 'min'
    mode: slider
    #initial: 5
    min: 2
    max: 15
    step: 1
  pond_filler_runtime:
    name: Pond Filler Daily Max
    unit_of_measurement: 'min'
    mode: slider
    #initial: 60
    min: -1
    max: 180
    step: 1
    