####################################################
# TEMPLATES - ANNIVERSARIES                        #
####################################################

  - unique_id: party_18_ans_cody
    #name: "18 ans de Cody :)"
    unit_of_measurement: 'days'
    #state_class: measurement
    #device_class: none
    icon: mdi:cake-variant
    state: >
      {% set numeric = is_number(states('sensor.cody_counter').split(' ')[0]) and is_number(states('sensor.cody_counter').split(' ')[2]) and is_number(states('sensor.cody_counter').split(' ')[4]) %}
      {% if numeric %}
        {% set day = states('sensor.cody_counter').split(' ')[0]|int(0) + states('sensor.cody_counter').split(' ')[2]|int(0)/24 + states('sensor.cody_counter').split(' ')[4]|int(0)/60 %}
        {% if day > 365 %}
          {{ day|round(0) }}
        {% else %}
          {{ states('sensor.cody_counter') }}
        {% endif %}
      {% else %}
        {{ 0 }}
      {% endif %}
    attributes:
      friendly_name: 18 ans de Cody :)
      
#    - name: Voyage Floride
#      #unique_id: voyage_floride
#      #unit_of_measurement: 'days'
#      #state_class: measurement
#      #device_class: none
#      icon: mdi:medical-bag
#      state: >
#        {{ states('sensor.voyage_floride') }}
#      attributes:
#        friendly_name: "18 ans de Cody :)"

  