####################################################
# SENSORS - POND                                   #
####################################################

  - unique_id: pondwaterfallpump_status
    #name: Pond Waterfall Pump
    icon: mdi:pump
    availability: > 
      {{ not is_state('switch.pond_waterfall_pump', 'unavailable') }}
    state: >
      {% if is_state('switch.pond_waterfall_pump', 'on') %}
        {% if is_state('binary_sensor.antifreeze_active', 'on') %}
          Run Low Temp
        {% else %}
          On
        {% endif %}
      {% elif is_state('switch.pond_waterfall_pump', 'off') %}
        {% if is_state('binary_sensor.pond_level_low', 'off')%}
          Low Level
        {% else %}
          Off
        {% endif %}
      {% else %}
        unknown
      {% endif %}
    attributes:
      friendly_name: Pond Waterfall Pump
      mode: "{{ states('input_select.pondwaterfallpump_mode') }}"
      schedule1: >-
        {% if is_state('input_select.pondwaterfallpump_mode', '24/7') %}
          ALWAYS ON
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Spring') %}
          8AM to 8PM
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Summer') %}
          SUN to THU: 6AM to 9PM
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Autumn') %}
          2AM to 6AM
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Winter/Off') %}
          ALWAYS OFF
        {% else %}
          ERROR
        {% endif %}
      schedule2: >-
        {% if is_state('input_select.pondwaterfallpump_mode', '24/7') %}
          N/A
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Spring') %}
          0AM to 4AM
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Summer') %}
          SUN to THU: 12AM to 3AM
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Autumn') %}
          9AM to 11AM
        {% else %}
          N/A
        {% endif %}
      schedule3: >-
        {% if is_state('input_select.pondwaterfallpump_mode', '24/7') %}
          N/A
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Spring') %}
          N/A
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Summer') %}
          FRI / SAT: 6AM to 11PM
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Autumn') %}
          2PM to 4PM
        {% else %}
          N/A
        {% endif %}
      schedule4: >-
        {% if is_state('input_select.pondwaterfallpump_mode', '24/7') %}
          N/A
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Spring') %}
          N/A
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Summer') %}
          FRI / SAT: 1AM to 4AM
        {% elif is_state('input_select.pondwaterfallpump_mode', 'Autumn') %}
          9PM to 11PM
        {% else %}
          N/A
        {% endif %}
      schedule5: >-
        {% if is_state('input_select.pondpump_mode', '24/7') %}
          N/A
        {% elif is_state('input_select.pondpump_mode', 'Spring') %}
          N/A
        {% elif is_state('input_select.pondpump_mode', 'Summer') %}
          N/A
        {% elif is_state('input_select.pondpump_mode', 'Autumn') %}
          Outside peak power from HQ
        {% else %}
          N/A
        {% endif %}
  
######### POND CONTROL - SENSORS #########

  - name: Pond Temperature
    #unique_id: pond_temperature
    unit_of_measurement: '° F'
    state_class: measurement
    #device_class: temperature
    icon: mdi:thermometer
    availability: >
      {{ not is_state('sensor.pond_temperature_raw', 'unavailable') and is_number(states('sensor.pond_temperature_stats')) }}
    state: >
      {{ states('sensor.pond_temperature_stats') }}
    attributes:
      temp_raw: "{{ states('sensor.pond_temperature_raw') }}"
      temp_mean: "{{ states('sensor.pond_temperature_stats') }}"
      # temp_min: "{{ state_attr('sensor.pond_temperature_stats', 'min_value') }}"
      # temp_max: "{{ state_attr('sensor.pond_temperature_stats', 'max_value') }}"
