####################################################
# TEMPLATES - SENSORS - ALL OTHERS                 #
####################################################

    - name: Postal Status
      #unique_id: postal_status
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: none
      icon: mdi:mailbox
      availability: >
        {{ not is_state('switch.postal_status', 'unavailable') }}
      state: >
        {% if is_state('switch.postal_status', 'on') %}
          New Mail
        {% else %}
          No Mail
        {% endif %}
      attributes:
        state: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        bat_voltage: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'voltage') }}{% else %}{{ 'unknown' }}{% endif %}"
        bat_percent: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
        id: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'id') }}{% else %}{{ 'unknown' }}{% endif %}"
        lora_rssi: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        source: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'source') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"

    - unique_id: last_postal_arrival
      #name: Last Postal Arrival Time
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: timestamp  //Makes display on minutes since...
      icon: mdi:clock-in
      availability: >
        {{ not is_state('switch.postal_status', 'unavailable') }}
      state: >
        {{ states('input_datetime.last_postal_arrival') }}
      attributes:
        friendly_name: Last Postal Arrival Time

    - unique_id: last_postal_removal
      #name: Last Postal Removal Time
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: timestamp  //Makes display on minutes since...
      icon: mdi:clock-out
      state: >
        {{ states('input_datetime.last_postal_removal') }}
        {{ states('input_datetime.last_postal_removal') }}
      attributes:
        friendly_name: Last Postal Removal Time

    - name: Nixie Clock
      #unique_id: nixie_clock
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: none
      icon: mdi:clock-out
      availability: >
        {{ not is_state('sensor.nixie_clock_status', 'unavailable') }}
      state: >
        {{ states('sensor.nixie_clock_status') }}
      attributes:
        state: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        case_temp: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'temp_in') }}{% else %}{{ 'unknown' }}{% endif %}"
        vcc_3v3: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
      picture: >
        {% if is_state('sensor.nixie_clock_status','On') %}
          /local/images/CustomMDI/nixietubes/dark_FBCD41.png
        {% elif is_state('sensor.nixie_clock_status','Off') %}
          /local/images/CustomMDI/nixietubes/dark_007AFF.png
        {% else %}
          /local/images/CustomMDI/nixietubes/dark_48485E.png
        {% endif %}

    - name: OwnCloud Status Code
      #unique_id: owncloud_status_code
      #unit_of_measurement: ''
      #state_class: 
      #device_class: 
      icon: mdi:database-check
      availability: >
        {{ not is_state('sensor.owncloud_status', 'unavailable') }}
      state: >
        {{ state_attr('sensor.owncloud_status','statuscode') }}
        
    - name: OwnCloud Status Message
      #unique_id: owncloud_status_message
      #unit_of_measurement: ''
      #state_class: 
      #device_class: 
      icon: mdi:database-check
      availability: >
        {{ not is_state('sensor.owncloud_status', 'unavailable') }}
      state: >
        {% if state_attr('sensor.owncloud_status','message')|string == "None" %}
          No Message
        {% else %}
          {{ state_attr('sensor.owncloud_status','message') }}
        {% endif %}

    - name: Random Number Generator
      unique_id: random_number_generator
      icon: mdi:shield-account
      state: "{{ states('input_number.random_number_generator')|int(0) }}"
      attributes:
        time_left: "{{ 300 - state_attr('sensor.times','sec_midnight')|int(0) % 300 }}s"
