####################################################
# ALARMS                                           #
####################################################

#####TESTS#####

  - platform: manual
    name: House
    code: 1725
    arming_time: 10
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
      
  - platform: manual
    name: Garage
    code: 1425
    arming_time: 10
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

