####################################################
# ALERTS                                           #
####################################################

  garage_door_alert:
    name: Garage is open
    done_message: Garage is closed
    entity_id: binary_sensor.garage_door_opened
    state: 'on'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - sms