####################################################
####################################################
# CONFIGURATION                                    #
####################################################

homeassistant:
  # Customization file
  customize: !include_dir_merge_named Customizations
  customize_glob: !include_dir_merge_named CustomizationsGlob
  customize_domain: !include_dir_merge_named CustomizationsDomain
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
  #whitelist_external_dirs:
  allowlist_external_dirs:
    - /config
  external_url: !secret ha_ext_url
  internal_url: !secret ha_int_url
  
#Activate iOS devices
mobile_app:

#Lovelace personalized interface
lovelace:
  mode: yaml
  resources: !include resources.yaml

# Enables the frontend
frontend:
 themes: !include themes.yaml
 extra_module_url:
   #- /local/custom-ui/custom-ui-pre-2021.6.js
   - /local/custom-ui/custom-ui.js

# Custom iframe panels
panel_iframe:
 chicoutimi:
   title: Chicoutimi
   icon: mdi:account-supervisor-circle
   url: !secret ha_chicout_url

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
  # base_url: !secret ha_ext_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
#logbook: !include logbook.yaml

#Database recorder
recorder: !include recorder.yaml

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# Python scripts
python_script:

#Sensors and others
alarm_control_panel: !include alarm.yaml
alert: !include alerts.yaml
#automation: !include_dir_merge_list Automations
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list BinarySensors
climate: !include climates.yaml
counter: !include counters.yaml
cover: !include covers.yaml
device_tracker: !include device_tracker.yaml
fan: !include fans.yaml
group: !include groups.yaml
input_boolean: !include_dir_merge_named InputBool
input_datetime: !include input_datetime.yaml
input_number: !include_dir_merge_named InputNumbers
input_select: !include_dir_merge_named InputSelects
input_text: !include input_text.yaml
light: !include lights.yaml
lock: !include locks.yaml
modbus: !include_dir_merge_list Modbus
notify: !include notifications.yaml
shell_command: !include shell_commands.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list Sensors
switch: !include_dir_merge_list Switches
#time_counter: !include timecounters.yaml
utility_meter: !include utilities.yaml
zone: !include zones.yaml


#Weather Forecasts from Environement Canada
weather:
  - platform: environment_canada
    name: !secret ha_city
    forecast: hourly
    # language: english
camera:
  - platform: environment_canada
    name: !secret ha_city
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret img_octopi
    mjpeg_url: !secret cam_octopi
  - platform: mjpeg
    name: Pool Area
    mjpeg_url: !secret cam_pool
    
  # - platform: mjpeg 
    # name: Pool Area
    # still_image_url: !secret img_pool
    # mjpeg_url: !secret cam_pool
    # verify_ssl: false
    
#Health
system_health:
#breaking_changes:
apcupsd:

speedtestdotnet:
  scan_interval:
    minutes: 10
    
#Devices and integrations
# vacuum:
  # - platform: roomba
    # name: Roomba iRobot
    # host: !secret roomba_ip
    # username: !secret roomba_username
    # password: !secret roomba_password

# iaqualink:
  # username: !secret iaqualink_username
  # password: !secret iaqualink_password
  
# media_player:
# - platform: kodi
#   host: !secret kodi_ip

#Communication protocols
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_login
  password: !secret mqtt_pass

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# logger:
  # default: info
  # logs:
    # homeassistant.components.websocket_api: debug

clean_up_snapshots_service:
  host: !secret ha_ext_url
  token: !secret ha_cleanup_token
  number_of_snapshots_to_keep: 10

life360:
  # MPH, assuming imperial units.
  # If using metric (KPH), the equivalent would be 29.
  driving_speed: 20
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  # Set comm error thresholds so first is not logged,
  # second is logged as a WARNING, and third and fourth
  # are logged as ERRORs.
  warning_threshold: 2
  error_threshold: 3

glances:
  - host: localhost
    version: 2
    name: Server

octoprint:
  - host: !secret ip_octopi
    api_key: !secret key_octopi
    name: OctoPrint
    bed: true
    number_of_tools: 1
