####################################################
# COUNTERS                                         #
####################################################

  second_counter:
    name: Second Counter
    restore: true
    minimum: 0
    maximum: 59
    initial: 0
    step: 1
    
  minute_counter:
    name: Minute Counter
    restore: true
    minimum: 0
    maximum: 59
    initial: 0
    step: 1
    
  heaters_counter:
    name: Heaters Counter
    restore: true
    minimum: 1
    maximum: 2
    initial: 1
    step: 1