####################################################
# COVERS                                           #
####################################################

  - platform: mqtt
    name: "Garage CD Opener"
    #device_class: garage
    command_topic: "Garage/Door/Car/Cmd"
    state_topic: "Garage/Door/Car/Sensors/Stts"
    value_template: '{{ value_json.state }}'
    availability:
      - topic: "Garage/Door/Car/LWT"
    qos: 0
    retain: false
    payload_open: '{"open":"ON"}'
    payload_close: '{"close":"ON"}'
    payload_stop: '{"stop":"ON"}'
    state_open: "opened"
    state_closed: "closed"
    optimistic: false
    json_attributes_topic: "Garage/Door/Car/Json"


#RGBW Milight Speed Up/Dn
  - platform: template
    covers:
      master_bedroom_rgbw:
        friendly_name: "Master Bedroom RGBW Speed"
        position_template: "{{ 50 }}"
        open_cover:
          service: script.milightspeed
          data:
            topic: "Home/Milight/Cmd/1"
            command: "up"
        close_cover:
          service: script.milightspeed
          data:
            topic: "Home/Milight/Cmd/1"
            command: "down"
            
      under_bar_rgbw:
        friendly_name: "Under Bar RGBW Speed"
        position_template: "{{ 50 }}"
        open_cover:
          service: script.milightspeed
          data:
            topic: "Home/Milight/Cmd/2"
            command: "up"
        close_cover:
          service: script.milightspeed
          data:
            topic: "Home/Milight/Cmd/2"
            command: "down"
