####################################################
# FANS                                             #
####################################################

#   - platform: mqtt  
#     name: "Master Bedroom Fan"
#     command_topic: "cmnd/sonoff_MBR_fan/FanSpeed"
#     speed_command_topic: "cmnd/sonoff_MBR_fan/FanSpeed"    
#     state_topic: "stat/sonoff_MBR_fan/RESULT"
#     speed_state_topic: "stat/sonoff_MBR_fan/RESULT"
#     state_value_template: "{% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}" 
#     speed_value_template: "{{ value_json.FanSpeed }}"
#     payload_off: "0"
#     payload_on: "4"
#     payload_low_speed: "1"
#     payload_medium_speed: "2"
#     payload_high_speed: "3"
#     availability:
#       - topic: "todo"
#     speeds:
#       - low
#       - medium
#       - high