####################################################
# GROUPS                                           #
####################################################
      
  all_locks:
    name: Lock All
    all: true
    entities:
      - lock.house_fd_lock
      #- lock.house_sd_lock
      #- lock.house_bd_lock
      - lock.garage_fd_lock
      #- lock.shed_fd_lock
      #- lock.pool_fd_lock

  locks:
    name: Locks
    entities:
      - input_boolean.house_fd_lock
      - input_boolean.house_fd_unlock
      - input_boolean.house_sd_lock
      - input_boolean.house_sd_unlock
      - input_boolean.house_bd_lock
      - input_boolean.house_bd_unlock
      - input_boolean.garage_fd_lock
      - input_boolean.garage_fd_unlock
      - input_boolean.shed_fd_lock
      - input_boolean.shed_fd_unlock
      - input_boolean.pool_fd_lock
      - input_boolean.pool_fd_unlock
      - input_boolean.lock_all
      
  garagedoors:
    name: Garage Doors
    entities:
      - input_boolean.garage_cd_trigger
      
  cars:
    name: Cars
    entities:
      - input_boolean.cars_lexus_lock
      - input_boolean.cars_lexus_unlock
      - input_boolean.cars_lexus_start
      - input_boolean.cars_lexus_other1
      - input_boolean.cars_journey_lock
      - input_boolean.cars_journey_unlock
      - input_boolean.cars_journey_start
      
  irrigation:
    name: Irrigation
    entities:
      - switch.backyard_irrigation
      - switch.frontyard_irrigation
      - switch.garden_irrigation
      
  control_boxes:
    name: Control Boxes
    entities:
      - input_boolean.control_room_control_reset
      - input_boolean.pond_control_reset
      - input_boolean.pool_control_reset
      - input_boolean.weather_control_reset
      - input_boolean.garage_main_control_reset
      - input_boolean.garage_slave_control_reset
      - input_boolean.shed_control_reset

