####################################################
# INPUT DATETIME                                   #
####################################################

  collect_trash_start:
    name: Trash Last Normal Day
    has_date: true
    has_time: false
  collect_trash_end:
    name: Trash Last Summer Day
    has_date: true
    has_time: false
    
  collect_recycle_start:
    name: Recycle Last Normal Day
    has_date: true
    has_time: false
  collect_recycle_end:
    name: Recycle Last Summer Day
    has_date: true
    has_time: false
    
  collect_compost_start:
    name: Compost Last Normal Day
    has_date: true
    has_time: false
  collect_compost_end:
    name: Compost Last Summer Day
    has_date: true
    has_time: false
    
  last_postal_arrival:
    name: Last Postal Arrival
    has_date: true
    has_time: true
  last_postal_removal:
    name: Last Postal Removal
    has_date: true
    has_time: true
    
  frontyardirrigation_start:
    name: Frontyard Irrigation Start
    has_time: true
  frontyardirrigation_stop:
    name: Frontyard Irrigation Stop
    has_time: true
    
  gardenirrigation_start:
    name: Garden Irrigation Start
    has_time: true
  gardenirrigation_stop:
    name: Garden Irrigation Stop
    has_time: true
    
  gardenirrigationaux_start:
    name: Garden Irrigation Aux Start
    has_time: true
  gardenirrigationaux_stop:
    name: Garden Irrigation Aux Stop
    has_time: true
    
  utility_tier_change_date:
    name: Utility Tier Last Change
    has_date: true
    has_time: true
    
  utility_tier_change_date_prev1:
    name: Utility Tier Prev Change 1
    has_date: true
    has_time: true
    
  utility_tier_change_date_prev2:
    name: Utility Tier Prev Change 2
    has_date: true
    has_time: true
    
  utility_tier_change_date_prev3:
    name: Utility Tier Prev Change 3
    has_date: true
    has_time: true
    
  utility_tier_change_date_prev4:
    name: Utility Tier Prev Change 4
    has_date: true
    has_time: true

  house_front_door:
    name: House Front Door Last Locked
    has_date: true
    has_time: true
  garage_front_door:
    name: Garage Front Door Last Locked
    has_date: true
    has_time: true
    
  lexus_morning_start:
    name: Lexus Morning Start
    has_time: true