####################################################
# UILOVELACE - RESOURCES                           #
####################################################

  - url: /local/your/path/lovelace-card-preloader.js
    type: js 

  #https://github.com/thomasloven/lovelace-card-tools
  - url: /local/card-tools.js?v=2
    type: module
    
  - url: /local/alarm_control_panel-card.js?v=1
    type: js

  #https://github.com/custom-cards/button-card
  - url: /local/button-card.js
    type: module
    
  #https://github.com/thomasloven/lovelace-card-mod
  - url: /local/card-mod.js?v=2
    type: module
    
  #https://github.com/thomasloven/lovelace-hui-element
  - url: /local/hui-element.js?v=1
    type: module
    
  #https://github.com/custom-cards/text-divider-row
  - url: /local/text-divider-row.js
    type: module

  #https://github.com/thomasloven/lovelace-color-picker
  # - url: /local/plugins/color_picker.js?v=1
    # type: js

  #https://github.com/ciotlosm/custom-lovelace
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/group-card.js?v=1
    type: js

  #https://github.com/custom-cards/button-entity-row
  - url: /local/button-entity-row.js?v=0.4.2
    type: module

  #https://github.com/custom-cards/state-element
  - url: /local/state-element.js?v=1
    type: js

  #https://github.com/custom-cards/radial-menu
#   - url: /local/radial-menu.js
#     type: module

  #https://github.com/custom-cards/circle-sensor-card
#   - url: /local/circle-sensor-card.js?v=0
#     type: module

  #https://github.com/custom-cards/bignumber-card
  - url: /local/bignumber-card.js?v=1
    type: js

  #https://github.com/custom-cards/bar-card
  - url: /local/bar-card.js?v=1.0.0
    type: js

  #https://github.com/thomasloven/lovelace-auto-entities
  - url: /local/auto-entities.js
    type: js

  #https://github.com/custom-cards/entity-attributes-card
  - url: /local/entity-attributes-card.js
    type: js

    
  - url: /local/fold-entity-row.js
    type: module

  #https://github.com/custom-cards/gauge-card
  - url: /local/gauge-card.js?v=2
    type: js

  #https://github.com/custom-cards/secondaryinfo-entity-row
  - url: /local/secondaryinfo-entity-row.js?v=0.4
    type: module
    
  - url: /local/dual-gauge-card.js
    type: js

#   #https://github.com/iantrich/restriction-card
#   - url: /local/community/restriction-card/restriction-card.js?v=1
#     type: module

#   #https://github.com/CyrisXD/love-lock-card  
#   - url: /local/love-lock-card.js
#     type: js

  # #https://github.com/Mariusthvdb/custom-ui
  # - url: /local/custom-ui/custom-ui.js?v=20200528
    # type: module

#   - url: /local/custom-ui/custom-ui.js?v=20200720
#     type: module
    
  #https://github.com/custom-cards/stack-in-card
  # - url: /local/stack-in-card.js?v=0.1.1
    # type: module