####################################################
# UILOVELACE - RESOURCES                           #
####################################################

#### MANUALLY ADDED RESSOURCES
  - url: /local/alarm_control_panel-card.js?v=1
    type: js

  #https://github.com/ciotlosm/custom-lovelace
  - url: /local/monster-card.js?v=1
    type: js

  #https://github.com/custom-cards/button-entity-row
  - url: /local/button-entity-row.js?v=0.4.2
    type: module

  #https://github.com/custom-cards/state-element
  - url: /local/state-element.js?v=1
    type: js

#   #https://github.com/dangreco/threedy
#   - url: /local/threedy-card.js?v=2021.0.4
#     type: js
    
  #https://github.com/AitorDB/home-assistant-sun-card (deprecated)
  - url: /local/home-assistant-sun-card.js
    type: js

#### HACS RESSOURCES
  # - url: /local/custom-ui/custom-ui.js
  #   type: module

  - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
    type: module
    
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module

  - url: /hacsfiles/lovelace-roomba-vacuum-card/roomba-vacuum-card.js
    type: module
    
  - url: /hacsfiles/button-card/button-card.js
    type: module
    
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
    
  - url: /hacsfiles/lovelace-hui-element/hui-element.js
    type: module
    
  - url: /hacsfiles/text-divider-row/text-divider-row.js
    type: module
    
  - url: /hacsfiles/group-card/group-card.js
    type: module
    
  - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
    type: module
    
  - url: /hacsfiles/bignumber-card/bignumber-card.js
    type: module
    
  - url: /hacsfiles/bar-card/bar-card.js
    type: module
    
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
    
  - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js
    type: module
    
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
    
  - url: /hacsfiles/gauge-card/gauge-card.js
    type: module
    
  - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: module
    
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
    
  - url: /hacsfiles/dual-gauge-card/dual-gauge-card.js
    type: module
    
  - url: /hacsfiles/stack-in-card/stack-in-card.js
    type: module
    
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: module
    
  - url: /hacsfiles/hass-shutter-card/hass-shutter-card.js
    type: module
    
  - url: /local/community/decluttering-card/decluttering-card.js
    #url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module
    
  - url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
    type: module
    
  - url: /hacsfiles/config-template-card/config-template-card.js
    type: module
    
  - url: /hacsfiles/apexcharts-card/apexcharts-card.js
    type: module
    
  - url: /hacsfiles/history-explorer-card/history-explorer-card.js
    type: module
    
  - url: /hacsfiles/lovelace-mushroom/mushroom.js
    type: module
    
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
    
  - url: /hacsfiles/ha-floorplan/floorplan.js
    type: module
    
  - url: /hacsfiles/lovelace-state-switch/state-switch.js
    type: module
    
  - url: /hacsfiles/ha-threedy-card/threedy-card.js
    type: module
    
  - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
    type: module