####################################################
# SCHEDULES                                        #
####################################################

  # thermostat_schedule:
  #   name: "Thermostat schedule"
  #   monday:
  #     - from: "17:00:00"
  #       to: "21:00:00"
  #   tuesday:
  #     - from: "17:00:00"
  #       to: "21:00:00"
  #   wednesday:
  #     - from: "17:00:00"
  #       to: "21:00:00"
  #   thursday:
  #     - from: "17:00:00"
  #       to: "21:00:00"
  #   friday:
  #     - from: "17:00:00"
  #       to: "23:00:00"
  #   saturday:
  #     - from: "07:00:00"
  #       to: "10:00:00"
  #     - from: "16:00:00"
  #       to: "23:00:00"
  #   sunday:
  #     - from: "07:00:00"
  #       to: "21:00:00"