####################################################
# SCRIPTS                                          #
####################################################

  none:
    alias: Dummy Script
    sequence:
      - delay:
          milliseconds: 1
      
  clear_lock:
    alias: Clear Lock Script
    sequence:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.doorlock_passcode
          value: ""
      - delay: 00:00:01
      - service: input_boolean.turn_off
        entity_id: group.locks

  lock:
    alias: Lock Script
    sequence:
      - service: lock.lock
        data_template:
          entity_id: lock.{{ entity_id }}_lock
      - service: script.turn_on
        entity_id: script.clear_lock
          
  unlock:
    alias: Unlock Script
    sequence:
      - service: lock.unlock
        data_template:
          entity_id: lock.{{ entity_id }}_lock
      - service: script.turn_on
        entity_id: script.clear_lock
           
  lockall:
    alias: Lock ALL Script
    sequence:
      - service: lock.lock
        entity_id: group.all_locks
      - delay: 00:00:01
      - service: script.turn_on
        entity_id: script.clear_lock
           
  clear_garagedoor:
    alias: Clear Garage Door Script
    sequence:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.doorlock_passcode
          value: ""
      - delay: 00:00:01
      - service: input_boolean.turn_off
        entity_id: group.garagedoors
  
  garagedoor:
    alias: Garage Door Script
    sequence:
      - service: cover.toggle
        data_template:
          entity_id: cover.{{ entity_id }}_opener
      - service: script.turn_on
        entity_id: script.clear_garagedoor
        
  # garagedoor_close:
    # alias: Garage Door Close Script
    # sequence:
      # - service: cover.close_cover
        # data_template:
          # entity_id: cover.{{ entity_id }}_opener
      # - service: script.turn_on
        # entity_id: script.clear_garagedoor

  cars:
    alias: Cars Script
    sequence:
      - service: mqtt.publish
        data_template: {"topic": "Home/Cars/Cmd/{{ id }}", "payload": "{\"{{ command }}\": \"ON\"}"}
      - delay: 00:00:01
      - service: input_boolean.turn_off
        entity_id: group.cars
        
  control_boxes:
    alias: Control Boxes Script
    sequence:
      - service: mqtt.publish
        data_template: {"topic": "{{ entity_id }}/Cmd", "payload": "{\"reset\": \"ON\"}"}
      - delay: 00:00:01
      - service: input_boolean.turn_off
        entity_id: group.control_boxes
          
  milightspeed:
    alias: Milight Speed
    sequence:
      - service: mqtt.publish
        data_template: {"topic": "{{ topic }}", "payload": "{\"speed\": \"{{ command }}\"}"}

  milightsynchelp:
    alias: Milight Sync Help Notification
    sequence:
      - service: persistent_notification.create
        data:
          title: "Milight Sync Help"
          message: |
            ## Prerequisites
            
            Your mqtt json light device should be created with topics setup with last topic level being the *ID* you wish to sync as follow:
            - command_topic: Home/Milight/Cmd/*ID*
            - state_topic: Home/Milight/Stts/*ID*
            
            ## Instructions to sync
            
            1. Turn power off to light to sync
            2. Enter the *ID* to sync into the box but don't press enter
            3. Turn on power to light to sync
            4. Press enter in the box as soon the light turns on
            5. Light will blink
            6. Done!
            
  haupdateavailable:
    alias: New Home Assistant version
    sequence:
      - service: persistent_notification.create
        data:
          title: "New Home Assistant version"
          message: |
            New Home Assistant version {{ states.sensor.ha_latest_version.state}} is available for download.
            
            You are currently running {{ states.sensor.ha_installed_version.state}}.
            
            ## Release Notes
            https://home-assistant.io/blog/categories/release-notes/
          
  # rain_count:
    # alias: Rain Count
    # sequence:
      # - service: input_boolean.turn_on
        # entity_id: input_boolean.outdoor_rain_trigger
      # - delay: 00:00:01
      # - service: input_boolean.turn_off
        # entity_id: input_boolean.outdoor_rain_trigger
        
  gardenirrigation_start30m:
    alias: Garden Irrigation Forced 30m
    sequence:
      - service: script.turn_off
        entity_id: script.gardenirrigation_start1h
      - service: switch.turn_on
        entity_id: switch.garden_irrigation
      - service: input_boolean.turn_off
        entity_id: input_boolean.gardenirrigation_start1h
      - delay: 00:30:00
      - service: script.turn_on
        entity_id: script.gardenirrigation_cancel
  gardenirrigation_start1h:
    alias: Garden Irrigation Forced 1h
    sequence:
      - service: script.turn_off
        entity_id: script.gardenirrigation_start30m
      - service: switch.turn_on
        entity_id: switch.garden_irrigation
      - service: input_boolean.turn_off
        entity_id: input_boolean.gardenirrigation_start30m
      - delay: 01:00:00
      - service: script.turn_on
        entity_id: script.gardenirrigation_cancel
  gardenirrigation_cancel:
    alias: Garden Irrigation Forced Cancel
    sequence:
      - service: script.turn_off
        entity_id: script.gardenirrigation_start30m
      - service: script.turn_off
        entity_id: script.gardenirrigation_start1h
      - service: input_boolean.turn_off
        entity_id: input_boolean.gardenirrigation_start30m
      - service: input_boolean.turn_off
        entity_id: input_boolean.gardenirrigation_start1h
      - delay: 00:00:02
      - service: input_boolean.turn_off
        entity_id: input_boolean.gardenirrigation_cancel
        
  pondfiller_start30m:
    alias: Pond Filler Forced 30m
    sequence:
      - service: switch.turn_on
        entity_id: switch.pond_filler_valve
      - service: script.turn_off
        entity_id: script.pondfiller_start1h
      - service: script.turn_off
        entity_id: script.pondfiller_start2h
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start1h
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start2h
      - delay: 00:30:00
      - service: script.turn_on
        entity_id: script.pondfiller_cancel
  pondfiller_start1h:
    alias: Pond Filler Forced 1h
    sequence:
      - service: switch.turn_on
        entity_id: switch.pond_filler_valve
      - service: script.turn_off
        entity_id: script.pondfiller_start30m
      - service: script.turn_off
        entity_id: script.pondfiller_start2h
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start30m
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start2h
      - delay: 01:00:00
      - service: script.turn_on
        entity_id: script.pondfiller_cancel
  pondfiller_start2h:
    alias: Pond Filler Forced 2h
    sequence:
      - service: switch.turn_on
        entity_id: switch.pond_filler_valve
      - service: script.turn_off
        entity_id: script.pondfiller_start30m
      - service: script.turn_off
        entity_id: script.pondfiller_start1h
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start30m
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start1h
      - delay: 02:00:00
      - service: script.turn_on
        entity_id: script.pondfiller_cancel
  pondfiller_cancel:
    alias: Pond Filler Forced Cancel
    sequence:
      - service: script.turn_off
        entity_id: script.pondfiller_start30m
      - service: script.turn_off
        entity_id: script.pondfiller_start1h
      - service: script.turn_off
        entity_id: script.pondfiller_start2h
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start30m
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start1h
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_start2h
      - delay: 00:00:02
      - service: input_boolean.turn_off
        entity_id: input_boolean.pondfiller_cancel
        
  update_entities:
    alias: Update entities
    sequence:
      - service: python_script.issues
      - service: python_script.count
      