####################################################
# THEMES                                           #
####################################################

alert_yellow:
  primary-text-color: '#FFC000'
  paper-item-icon-color: '#FFC000'
alert_red:
  primary-text-color: '#FF0000'
  paper-item-icon-color: '#FF0000'
sensor_on:
  primary-text-color: '#2F7EFD'
  paper-item-icon-color: '#2F7EFD'
sensor_off:
  primary-text-color: '#48485E'
  paper-item-icon-color: '#48485E'
  
th_gauge_3: 
  label-badge-blue: "#55ACEE"
  label-badge-green: "#0DA035"
  label-badge-yellow: "#F4B400"
  label-badge-red: "#B82A27"
  
chicoutimi: #Dark Orange
  ### Main Interface Colors ###
  primary-color: "#FF8300"
  light-primary-color: "#FFA23F"
  divider-color: "#1F1F28"
  mdc-theme-primary: orange
  app-header-background-color: "#FF8300"
  ### Text ###
  text-primary-color: white
  secondary-text-color: slategray
  disabled-text-color: "#595975"
  ### States and Badges ###
  state-icon-color: "#FF8300"
  state-icon-active-color: "#FBCD41"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Labels ###
  label-badge-background-color: "#363647"
  label-badge-text-color: "#F1F1F1"
  label-badge-red: "#FFA23F"
  ### Sliders ###
  paper-slider-knob-color: "#FF8300"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#FF8300"
  paper-toggle-button-checked-bar-color: "#FFA23F"
  paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color) #"#FF8300"
  paper-toggle-button-unchecked-bar-color: "#444446"
    ### Sidebar Menu ###
  sidebar-icon-color: "#B6B6C1"
  modes:
    light:
      primary-text-color: black
      text-primary-color: black
      #accent-color: white
      primary-background-color: white
      secondary-background-color: var(--primary-background-color)
      app-header-selection-bar-color: black
      mdc-text-field--disabled: black
    dark:
      primary-text-color: white
      text-primary-color: white
      #accent-color: black
      primary-background-color: black
      secondary-background-color: var(--primary-background-color)
      app-header-selection-bar-color: white
      mdc-text-field--disabled: white
      
dolbeau: #Dark Blue
  ### Main Interface Colors ###
  primary-color: "#2F7EFD"
  light-primary-color: "#6FA6FE"
  divider-color: "#1F1F28"
  mdc-theme-primary: var(--sidebar-selected-text-color)
  app-header-background-color: "#2F7EFD"
  ### Text ###
  text-primary-color: white
  secondary-text-color: slategray
  disabled-text-color: "#595975"
  ### States and Badges ###
  state-icon-color: "#2F7EFD"
  state-icon-active-color: "#FBCD41"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Labels ###
  label-badge-background-color: "#23232E"
  label-badge-text-color: "#F1F1F1"
  label-badge-red: "#6FA6FE"
  ### Sliders ###
  paper-slider-knob-color: "#2F7EFD"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#2F7EFD"
  paper-toggle-button-checked-bar-color: "#6FA6FE"
  paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color) #"#2F7EFD"
  paper-toggle-button-unchecked-bar-color: "#3E4756"
  ### Sidebar Menu ###
  sidebar-icon-color: "#B6B6C1"
  modes:
    light:
      primary-text-color: black
      text-primary-color: black
      #accent-color: white
      primary-background-color: white
      secondary-background-color: var(--primary-background-color)
      app-header-selection-bar-color: black
      mdc-text-field--disabled: black
    dark:
      primary-text-color: white
      text-primary-color: white
      #accent-color: black
      primary-background-color: black
      secondary-background-color: var(--primary-background-color)
      app-header-selection-bar-color: white
      mdc-text-field--disabled: white


# Dark - Blue:
#   ### Main Interface Colors ###
#   primary-color: "#2F7EFD"
#   light-primary-color: "#6FA6FE"
#   primary-background-color: "#1F1F28"
#   secondary-background-color: var(--primary-background-color)
#   divider-color: "#2F2F3D"
#   ### Text ###
#   primary-text-color: "#FFFFFF"
#   secondary-text-color: "#6FA6FE"
#   text-primary-color: "#FFFFFF"
#   disabled-text-color: "#4E4E66"
#   ### Sidebar Menu ###
#   sidebar-icon-color: "#B6B6C1"
#   sidebar-text-color: "#F1F1F1"
#   sidebar-selected-background-color: var(--primary-background-color)
#   sidebar-selected-icon-color: "#6FA6FE"
#   sidebar-selected-text-color: var(--sidebar-selected-icon-color)
#   ### States and Badges ###
#   state-icon-color: "#2F7EFD"
#   state-icon-active-color: "#FBCD41"
#   state-icon-unavailable-color: var(--disabled-text-color)
#   ### Sliders ###
#   paper-slider-knob-color: "#2F7EFD"
#   paper-slider-knob-start-color: var(--paper-slider-knob-color)
#   paper-slider-pin-color: var(--paper-slider-knob-color)
#   paper-slider-active-color: var(--paper-slider-knob-color)
#   paper-slider-secondary-color: var(--light-primary-color)
#   ### Labels ###
#   label-badge-background-color: "#23232E"
#   label-badge-text-color: "#F1F1F1"
#   label-badge-red: "#6FA6FE"
#   ### Cards ###
#   paper-card-background-color: "#23232E"
#   paper-listbox-background-color: var(--primary-background-color)
#   data-table-background-color: var(--primary-background-color)
#   material-background-color: var(--primary-background-color)
#   card-background-color: var(--primary-background-color)
#   ### Toggles ###
#   paper-toggle-button-checked-button-color: "#2F7EFD"
#   paper-toggle-button-checked-bar-color: "#6FA6FE"
#   paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color)
#   paper-toggle-button-unchecked-bar-color: "#3E4756"
#   ### Table row ###
#   table-row-background-color: var(--primary-background-color)
#   table-row-alternative-background-color: var(--secondary-background-color)
  
# Dark - Orange:
#   ### Main Interface Colors ###
#   primary-color: "#FF8300"
#   light-primary-color: "#FFA23F"
#   primary-background-color: "#1F1F28"
#   secondary-background-color: var(--primary-background-color)
#   divider-color: "#353544"
#   ### Text ###
#   primary-text-color: "#FFFFFF"
#   secondary-text-color: "#FF8300"
#   text-primary-color: "#FFFFFF"
#   disabled-text-color: "#595975"
#   input-ink-color: var(--secondary-text-color)
#   mdc-text-field-ink-color: var(--text-primary-color)
#   mdc-text-field-fill-color: var(--primary-background-color)
#   mdc-select-fill-color: var(--primary-background-color)
#   ### Sidebar Menu ###
#   sidebar-icon-color: "#7D8BA6"
#   sidebar-text-color: "#F1F1F1"
#   sidebar-selected-background-color: var(--primary-background-color)
#   sidebar-selected-icon-color: "#FFA23F"
#   sidebar-selected-text-color: var(--sidebar-selected-icon-color)
#   ### States and Badges ###
#   state-icon-color: "#FF8300"
#   state-icon-active-color: "#FBCD41"
#   state-icon-unavailable-color: var(--disabled-text-color)
#   ### Sliders ###
#   paper-slider-knob-color: "#FF8300"
#   paper-slider-knob-start-color: var(--paper-slider-knob-color)
#   paper-slider-pin-color: var(--paper-slider-knob-color)
#   paper-slider-active-color: var(--paper-slider-knob-color)
#   paper-slider-secondary-color: var(--light-primary-color)
#   ### Labels ###
#   label-badge-background-color: "#363647"
#   label-badge-text-color: "#F1F1F1"
#   label-badge-red: "#FFA23F"
#   ### Cards ###
#   paper-card-background-color: "#23232E"
#   paper-listbox-background-color: var(--primary-background-color)
#   data-table-background-color: var(--primary-background-color)
#   material-background-color: var(--primary-background-color)
#   card-background-color: var(--primary-background-color)
#   ### Toggles ###
#   paper-toggle-button-checked-button-color: "#FF8300"
#   paper-toggle-button-checked-bar-color: "#FFA23F"
#   paper-toggle-button-unchecked-button-color: "#767679"
#   paper-toggle-button-unchecked-bar-color: "#444446"
#   ### Table row ###
#   table-row-background-color: var(--primary-background-color)
#   table-row-alternative-background-color: var(--secondary-background-color)
  