####################################################
# UILOVELACE - YAML                                #
####################################################

## IMPORTANT - You need to edit and resave THIS file 
## after making a change in the Lovelace folder in
## order to changes to be refelected after a refresh

title: Cindy & Jean
preload_cards:
  - markdown
  - gauge
  - conditional
  - custom:fold-entity-row
  - custom:secondaryinfo-entity-row
preload_rows:
  - divider

views: !include_dir_merge_list UILovelace

decluttering_templates: !include_dir_merge_named UILovelaceDeclut

