####################################################
# UTILITY METERS                                   #
####################################################

  main_daily_energy:
    source:  sensor.main_power_usage
    cycle: daily
  main_monthly_energy:
    source:  sensor.main_power_usage
    cycle: monthly
    
  garage_daily_energy:
    source:  sensor.garage_power_usage
    cycle: daily
  garage_monthly_energy:
    source:  sensor.garage_power_usage
    cycle: monthly
    
  pool_daily_energy:
    source:  sensor.pool_power_usage
    cycle: daily
  pool_monthly_energy:
    source:  sensor.pool_power_usage
    cycle: monthly