####################################################
# INPUTS BOOLEAN                                   #
####################################################

  restart_hass:
    name: Restart HASS
    initial: off
    icon: mdi:autorenew
    
  running_hass:
    name: HASS is running
    initial: off
    icon: mdi:autorenew
    
  request_position:
    name: Request IOS positions
    initial: off
    icon: mdi:map-marker-radius
    
  force_reset_graphs:
    name: Force Reset Graphs
    initial: off
    icon: mdi:trending-up
    
  gardenirrigation_start30m:
    name: Garden Irrigation 30 minutes
    initial: off
    icon: mdi:clock-start
  gardenirrigation_start1h:
    name: Garden Irrigation 1 hour
    initial: off
    icon: mdi:clock-start
  gardenirrigation_cancel:
    name: Garden Irrigation Cancel
    initial: off
    icon: mdi:clock-start
    
  pondfiller_start30m:
    name: Pond Filler 30 minutes
    initial: off
    icon: mdi:clock-start
  pondfiller_start1h:
    name: Pond Filler 1 hour
    initial: off
    icon: mdi:clock-start
  pondfiller_start2h:
    name: Pond Filler 2 hour
    initial: off
    icon: mdi:clock-start
  pondfiller_cancel:
    name: Pond Filler Cancel
    initial: off
    icon: mdi:clock-start
    
  control_room_control_reset:
    name: Control Room Control Reset
    initial: off
    icon: mdi:power-cycle
  garage_main_control_reset:
    name: Garage Main Reset
    initial: off
    icon: mdi:power-cycle
  garage_slave_control_reset:
    name: Garage Slave Reset
    initial: off
    icon: mdi:power-cycle
  pond_control_reset:
    name: Pond Control Reset
    initial: off
    icon: mdi:power-cycle
  pool_control_reset:
    name: Pool Control Reset
    initial: off
    icon: mdi:power-cycle
  weather_control_reset:
    name: Weather Control Reset
    initial: off
    icon: mdi:power-cycle
  shed_control_reset:
    name: Shed Control Reset
    initial: off
    icon: mdi:power-cycle
  
  pool_running:
    name: Pool Running
    icon: mdi:pool
    
  pond_running:
    name: Pond Running
    icon: mdi:fish
    
  living_room_hvac_tilt:
    name: Living Room HVAC Tilt
    icon: mdi:weather-windy
    
  garage_front_heater:
    name: Garage Front Heater
  garage_rear_heater:
    name: Garage Front Heater
  garage_heaters:
    name: Garage Heaters
  garage_air_valve:
    name: Garage Air Valve
  house_air_valve:
    name: House Air Valve
  air_compressor_purge:
    name: Air Compressor Purge
    