####################################################
# INPUTS BOOLEAN - CARS                            #
####################################################

  cars_lexus_lock:
    name: Lexus Lock
    initial: off
  cars_lexus_unlock:
    name: Lexus Unlock
    initial: off
  cars_lexus_start:
    name: Lexus Start
    initial: off
  cars_lexus_other1:
    name: Lexus Trunk
    initial: off
    
  cars_journey_lock:
    name: Journey Lock
    initial: off
  cars_journey_unlock:
    name: Journey Unlock
    initial: off
  cars_journey_start:
    name: Journey Start
    initial: off