####################################################
# INPUTS BOOLEAN - LOCKS                           #
####################################################

  lock_all:
    name: Lock ALL Doors
    initial: off
    icon: mdi:lock
    
  house_fd_lock:
    name: House FD Lock
    initial: off
    icon: mdi:lock
  house_fd_unlock:
    name: House FD Unlock
    initial: off
    icon: mdi:lock-open
    
  house_sd_lock:
    name: House SD Lock
    initial: off
    icon: mdi:lock
  house_sd_unlock:
    name: House SD Unlock
    initial: off
    icon: mdi:lock-open
    
  house_bd_lock:
    name: House BD Lock
    initial: off
    icon: mdi:lock
  house_bd_unlock:
    name: House BD Unlock
    initial: off
    icon: mdi:lock-open
    
  garage_fd_lock:
    name: Garage FD Lock
    initial: off
    icon: mdi:lock
  garage_fd_unlock:
    name: Garage FD Unlock
    initial: off
    icon: mdi:lock-open
    
  garage_cd_trigger:
    name: Garage CD Trigger
    initial: off
    icon: mdi:garage-open
    
  shed_fd_lock:
    name: Shed FD Lock
    initial: off
    icon: mdi:lock
  shed_fd_unlock:
    name: Shed FD Unlock
    initial: off
    icon: mdi:lock-open
    
  pool_fd_lock:
    name: Pool FD Lock
    initial: off
    icon: mdi:lock
  pool_fd_unlock:
    name: Pool FD Unlock
    initial: off
    icon: mdi:lock-open
    