####################################################
# SENSORS                                          #
####################################################
   
  - platform: ted5000
    host: !secret ted_ip
    port: !secret ted_port
    name: TED5000
    scan_interval: 5
    
#   - platform: hydroquebec
#     username: "username"
#     password: "password"
#     contract: 'contract'
#     monitored_variables:
#      - period_total_bill
#      - period_length
#      - period_total_days
    
  - platform: openexchangerates
    api_key: !secret openexchange_key
    scan_interval: 5
    quote: CAD
    
  # - platform: opensky
    # radius: 10
    
  # - platform: ebox
    # username: !secret ebox_username
    # password: !secret ebox_password
    # monitored_variables:
     # - download
     # - upload
     # - total
    
  - platform: integration
    name: Main Power Usage
    source: sensor.ted5000_mtu1_power
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
  - platform: integration
    name: Garage Power Usage
    source: sensor.ted5000_mtu2_power
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
  - platform: integration
    name: Pool Power Usage
    source: sensor.ted5000_mtu3_power
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
    
  - platform: mqtt
    name: "Postal Status JSON"
    icon: mdi:mailbox
    state_topic: "Home/Postal/Stts"
    value_template: '{{ value_json.state }}'
    availability_topic: "Home/Transmitter/LWT"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/Postal/Stts"
    
  - platform: template
    sensors:
      postal_status:
        friendly_name: Postal Status
        icon_template: >
          mdi:mailbox
        value_template: >
          {% if is_state('switch.postal_status', 'on') %}
            New Mail
          {% else %}
            No Mail
          {% endif %}
        availability_template: "{{ not is_state('switch.postal_status', 'unavailable') }}"
        attribute_templates:
          state: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
          bat_voltage: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'voltage') }}{% else %}{{ 'unknown' }}{% endif %}"
          bat_percent: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
          id: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'id') }}{% else %}{{ 'unknown' }}{% endif %}"
          lora_rssi: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
          source: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'source') }}{% else %}{{ 'unknown' }}{% endif %}"
          version: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
          date: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_ssid: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_rssi: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_percent: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
          
#tags needs to be replaced rssi and percent and add ssid
# wifi_ssid: GauthierHA2
# wifi_rssi: -63.00
# wifi_percent:  74.00
          
      last_postal_arrival:
        friendly_name: Last Postal Arrival Time
        icon_template: >
          mdi:clock-in
        #device_class: timestamp  //Makes display on minutes since...
        value_template: "{{ states('input_datetime.last_postal_arrival') }}"
        
      last_postal_removal:
        friendly_name: Last Postal Removal Time
        icon_template: >
          mdi:clock-out
        #device_class: timestamp  //Makes display on minutes since...
        value_template: "{{ states('input_datetime.last_postal_removal') }}"
    
  - platform: mqtt
    name: "Stepper Wall Clock"
    icon: mdi:clock-start
    state_topic: "Home/WallClock/Stts"
    availability_topic: "Home/WallClock/LWT"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    value_template: >
      {% if value_json.homed == "ON" %}
        Ok
      {% else %}
        Homing
      {% endif %}
    json_attributes_topic: "Home/WallClock/Json"
    
  - platform: mqtt
    name: "Nixie Clock Status"
    icon: mdi:clock
    state_topic: "Home/NixieClock/Stts"
    availability:
      - topic: "Home/NixieClock/LWT"
    value_template: >
      {% if value_json.state == "ON" %}
        On
      {% else %}
        Off
      {% endif %}
    qos: 0
    json_attributes_topic: "Home/NixieClock/Json"
    
  - platform: mqtt
    name: "Nixie Clock Case Temp"
    unit_of_measurement: '°C'
    icon: mdi:clock
    state_topic: "Home/NixieClock/Json"
    value_template: "{{ value_json.temp_in }}"
    availability:
      - topic: "Home/NixieClock/LWT"
    qos: 0
    
  - platform: template
    sensors:
      nixie_clock:
        friendly_name: Nixie Clock
        value_template: "{{ states('sensor.nixie_clock_status') }}"
        availability_template: "{{ not is_state('sensor.nixie_clock_status', 'unavailable') }}"
        entity_picture_template: >
          {% if is_state('sensor.nixie_clock_status','On') %}
            /local/images/CustomMDI/nixietubes/dark_FBCD41.png
          {% elif is_state('sensor.nixie_clock_status','Off') %}
            /local/images/CustomMDI/nixietubes/dark_007AFF.png
          {% else %}
            /local/images/CustomMDI/nixietubes/dark_48485E.png
          {% endif %}
        attribute_templates:
          state: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
          version: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
          date: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
          case_temp: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'temp_in') }}{% else %}{{ 'unknown' }}{% endif %}"
          vcc_3v3: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_ssid: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_rssi: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_percent: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"

