####################################################
# SENSORS - CONTROL ROOM                           #
####################################################

######### CONTROL ROOM - BASIC DATA #########
  - platform: mqtt
    name: "Control Room Control Status"
    icon: mdi:server
    state_topic: "Home/Control/Json"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    value_template: >
      {% set status = value_json.state %}
      {% if status == "ON" %}
        Running...
      {% else %}
        ERROR
      {% endif %}
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "Control Room Box Temperature"
    unit_of_measurement: '째C'
    state_topic: "Home/Control/Json"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    value_template: "{{ value_json.temp_in }}"
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "Control Room Box Humidity"
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Home/Control/Json"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    value_template: "{{ value_json.hum_in }}"
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "Cold Storage Temperature"
    unit_of_measurement: '째C'
    state_topic: "Home/Control/Json"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    value_template: "{{ value_json.temp_out }}"
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "Cold Storage Humidity"
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Home/Control/Json"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    value_template: "{{ value_json.hum_out }}"
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "Control Room 5V Voltage"
    unit_of_measurement: 'V'
    icon: mdi:flash-outline
    state_topic: "Home/Control/Json"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc5V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
    
  - platform: mqtt
    name: "Control Room 12V Voltage"
    unit_of_measurement: 'V'
    icon: mdi:flash-outline
    state_topic: "Home/Control/Json"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc12V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
    
######### CONTROL ROOM - SENSORS #########
  - platform: template
    sensors:
      water_valve_status:
        friendly_name: "Water Valve State"
        value_template: >
          {% set LS_opened = (states.binary_sensor.water_valve_opened.state == 'on') %}
          {% set LS_closed = (states.binary_sensor.water_valve_closed.state == 'on') %}
          {% set RL_open = (states.switch.water_valve_open.state == 'on') %}
          {% set RL_close = (states.switch.water_valve_close.state == 'on') %}
          
          {% if LS_opened and not LS_closed %}
            Opened
          {% elif LS_closed and not LS_opened %}
            Closed
          {% elif LS_closed and LS_opened %}
            ERROR
          {% else %}
            {% if RL_open %}
              Opening
            {% elif RL_close %}
              Closing
            {% else %}
              ERROR
            {% endif %}
          {% endif %}
        availability_template: >
          {{ not is_state('binary_sensor.water_valve_opened', 'unavailable') and not is_state('binary_sensor.water_valve_closed', 'unavailable')}}
        icon_template: >
          {% set LS_opened = (states.binary_sensor.water_valve_opened.state == 'on') %}
          {% set LS_closed = (states.binary_sensor.water_valve_closed.state == 'on') %}
          {% set RL_open = (states.switch.water_valve_open.state == 'on') %}
          {% set RL_close = (states.switch.water_valve_close.state == 'on') %}
          
          {% if LS_opened and not LS_closed %}
            mdi:pipe
          {% elif LS_closed and not LS_opened %}
            mdi:pipe-disconnected
          {% elif not LS_closed and not LS_opened and (RL_open or RL_close) %}
            mdi:valve
          {% elif is_state('binary_sensor.water_valve_opened', 'unavailable') or is_state('binary_sensor.water_valve_closed', 'unavailable') %}
            mdi:pipe-disconnected
          {% else %}
            mdi:help
          {% endif %}
        attribute_templates:
          opened: >
            {{ is_state('binary_sensor.water_valve_opened', "on") }}
          closed: >
            {{ is_state('binary_sensor.water_valve_closed', "on") }}
    
######### CONTROL ROOM - WATER HEATER #########
  - platform: mqtt
    name: "Water Heater Temperature"
    icon: mdi:thermometer
    unit_of_measurement: '째C'
    state_topic: "Home/WaterHeater/Sensors/Stts"
    availability:
      - topic: "Home/WaterHeater/LWT"
    qos: 0
    value_template: "{{ value_json.wtr_t_out }}"
    json_attributes_topic: "Home/WaterHeater/Sensors/Stts"
    #json_attributes_topic: "Home/WaterHeater/Json"
    
  - platform: mqtt
    name: "Water Heater Flow"
    icon: mdi:water-pump
    unit_of_measurement: 'l/min'
    state_topic: "Home/WaterHeater/Sensors/Stts"
    availability:
      - topic: "Home/WaterHeater/LWT"
    qos: 0
    value_template: "{{ value_json.wtr_flow }}"
    json_attributes_topic: "Home/WaterHeater/Sensors/Stts"
    #json_attributes_topic: "Home/WaterHeater/Json"
    
  - platform: template
    sensors:      
      water_heater_status:
        friendly_name_template: >
          {% if is_state('switch.water_heater', 'on') and is_state('binary_sensor.water_heater_flow', 'on') %}
            Water Heater Status: {{ states('sensor.water_heater_temperature') }}째C
          {% else %}
            Water Heater Status
          {% endif %}
        value_template: >
          {% if is_state('switch.water_heater', 'off') %}
            Off
          {% elif is_state('switch.water_heater', 'on') and is_state('binary_sensor.water_heater_flow', 'on') %}
           Heating
          {% else %}
            Ready
          {% endif %}
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        icon_template: >
          {% if is_state('switch.water_heater', 'off') %}
            mdi:radiator-off
          {% elif is_state('switch.water_heater', 'on') and is_state('binary_sensor.water_heater_flow', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}
        attribute_templates:
          state: "{% if states('switch.water_heater') != 'unavailable' %}{{ state_attr('switch.water_heater', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
          version: "{% if states('switch.water_heater') != 'unavailable' %}{{ state_attr('switch.water_heater', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
          date: "{% if states('switch.water_heater') != 'unavailable' %}{{ state_attr('switch.water_heater', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
          #vcc_3v3: "{% if states('switch.water_heater') != 'unavailable' %}{{ state_attr('switch.water_heater', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_ssid: "{% if states('switch.water_heater') != 'unavailable' %}{{ state_attr('switch.water_heater', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_rssi: "{% if states('switch.water_heater') != 'unavailable' %}{{ state_attr('switch.water_heater', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_percent: "{% if states('switch.water_heater') != 'unavailable' %}{{ state_attr('switch.water_heater', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
          temp_in: "{% if states('sensor.water_heater_temperature') != 'unavailable' %}{{ state_attr('sensor.water_heater_temperature', 'wtr_t_in') }}{% else %}{{ 'unknown' }}{% endif %}"
          temp_out: "{% if states('sensor.water_heater_temperature') != 'unavailable' %}{{ state_attr('sensor.water_heater_temperature', 'wtr_t_out') }}{% else %}{{ 'unknown' }}{% endif %}"
          flow: "{% if states('sensor.water_heater_flow') != 'unavailable' %}{{ state_attr('sensor.water_heater_flow','wtr_flow') }}{% else %}{{ 'unknown' }}{% endif %}"