####################################################
# SENSORS - OPEN HARDWARE MONITOR                  #
####################################################

  #JGAU-PC
  - platform: openhardwaremonitor
    host: !secret ip_jgau_pc
  #CFOR-PC
  - platform: openhardwaremonitor
    host: !secret ip_cfor_pc

  - platform: min_max
    name:  JGAU-PC Intel Core i7-3770 Clocks CPU Cores
    # Type - min, max, or mean
    type: max
    entity_ids:
      - sensor.jgau_pc_intel_core_i7_3770_clocks_cpu_core_1
      - sensor.jgau_pc_intel_core_i7_3770_clocks_cpu_core_2
      - sensor.jgau_pc_intel_core_i7_3770_clocks_cpu_core_3
      - sensor.jgau_pc_intel_core_i7_3770_clocks_cpu_core_4
      
  - platform: min_max
    name:  CFOR-PC Intel Core i7-3820 Clocks CPU Cores
    # Type - min, max, or mean
    type: max
    entity_ids:
      - sensor.cfor_pc_intel_core_i7_3820_clocks_cpu_core_1
      - sensor.cfor_pc_intel_core_i7_3820_clocks_cpu_core_2
      - sensor.cfor_pc_intel_core_i7_3820_clocks_cpu_core_3
      - sensor.cfor_pc_intel_core_i7_3820_clocks_cpu_core_4