####################################################
# SENSORS - GARAGE                                 #
####################################################
    
######### GARAGE MAIN - BASIC DATA #########
  - platform: mqtt
    name: Garage Main Control Status
    icon: mdi:server
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    qos: 0
    value_template: >
      {% set status = value_json.state %}
      {% if status == "ON" %}
        Running...
      {% else %}
        ERROR
      {% endif %}
    json_attributes_topic: "Garage/Control/Json"
    
  - platform: mqtt
    name: Garage Main Box Temperature
    unit_of_measurement: '°C'
    icon: mdi:thermometer
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    value_template: "{{ value_json.temp_in }}"
    qos: 0
    
  - platform: mqtt
    name: Garage Main Box Humidity
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    value_template: "{{ value_json.hum_in }}"
    qos: 0
    
  - platform: mqtt
    name: Garage Main 5V Voltage
    unit_of_measurement: 'V'
    icon: mdi:flash-outline
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc5V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
    
  - platform: mqtt
    name: Garage Main 12V Voltage
    icon: mdi:flash-outline
    unit_of_measurement: 'V'
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc12V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}

######### GARAGE MAIN - SAFETY HEATER #########

#See other sensors templates in Templates/t_garage.yaml
        
#   - platform: statistics
#     name: "Garage Safety Front Temp Stats"
#     entity_id: sensor.garage_safety_front_temperature
#     sampling_size: 6
#     max_age:
#       minutes: 1
#     precision: 1
    
#   - platform: statistics
#     name: "Garage Safety Rear Temp Stats"
#     entity_id: sensor.garage_safety_rear_temperature
#     sampling_size: 6
#     max_age:
#       minutes: 1
#     precision: 1
    
  - platform: min_max
    name: Garage Mean Temp
    round_digits: 1
    type: mean
    entity_ids:
      # - sensor.garage_safety_front_temp_raw
      # - sensor.garage_safety_rear_temp_raw
      - sensor.garage_safety_front_temperature
      - sensor.garage_safety_rear_temperature
      - sensor.garage_front_temp_raw
      - sensor.garage_rear_temp_raw
      
  - platform: history_stats
    name: Garage Front Heater Time
    entity_id: switch.garage_front_heater
    state: "on"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
      
  - platform: history_stats
    name: Garage Front Heater Count
    entity_id: switch.garage_front_heater
    state: "on"
    type: count
    end: "{{ now() }}"
    duration:
      hours: 24
      
  - platform: history_stats
    name: Garage Rear Heater Time
    entity_id: switch.garage_rear_heater
    state: "on"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
      
  - platform: history_stats
    name: Garage Rear Heater Count
    entity_id: switch.garage_rear_heater
    state: "on"
    type: count
    end: "{{ now() }}"
    duration:
      hours: 24
        
######### GARAGE SLAVE - BASIC DATA #########
  - platform: mqtt
    name: Garage Slave Control Status
    icon: mdi:server
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: >
      {% set status = value_json.state %}
      {% if status == "ON" %}
        Running...
      {% else %}
        ERROR
      {% endif %}
    json_attributes_topic: "Garage/Slave/Json"
    
  - platform: mqtt
    name: Garage Slave Box Temperature
    unit_of_measurement: '°C'
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.temp_in }}"
    
  - platform: mqtt
    name: Garage Slave Box Humidity
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    value_template: "{{ value_json.hum_in }}"
    qos: 0
    
  - platform: mqtt
    name: Garage Slave 5V Voltage
    icon: mdi:flash-outline
    unit_of_measurement: 'V'
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc5V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
      
######### GARAGE SLAVE - SENSORS #########
  - platform: mqtt
    name: Air Compressor Pressure Raw
    icon: mdi:gauge
    unit_of_measurement: 'psi'
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.air_press }}"
      
#See other sensors templates in Templates/t_garage.yaml
          
  - platform: mqtt
    name: Garage Air Valve
    icon: mdi:valve
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.air_garage }}"
    
  - platform: mqtt
    name: House Air Valve
    icon: mdi:valve
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.air_house }}"
    