####################################################
# SENSORS - GARAGE                                 #
####################################################
    
######### GARAGE MAIN - BASIC DATA #########
  - platform: mqtt
    name: Garage Main Control Status
    icon: mdi:server
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    qos: 0
    value_template: >
      {% set status = value_json.state %}
      {% if status == "ON" %}
        Running...
      {% else %}
        ERROR
      {% endif %}
    json_attributes_topic: "Garage/Control/Json"
    
  - platform: mqtt
    name: Garage Main Box Temperature
    unit_of_measurement: '°C'
    icon: mdi:thermometer
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    value_template: "{{ value_json.temp_in }}"
    qos: 0
    
  - platform: mqtt
    name: Garage Main Box Humidity
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    value_template: "{{ value_json.hum_in }}"
    qos: 0
    
  - platform: mqtt
    name: Garage Main 5V Voltage
    unit_of_measurement: 'V'
    icon: mdi:flash-outline
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc5V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
    
  - platform: mqtt
    name: Garage Main 12V Voltage
    icon: mdi:flash-outline
    unit_of_measurement: 'V'
    state_topic: "Garage/Control/Json"
    availability:
      - topic: "Garage/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc12V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}

######### GARAGE MAIN - SAFETY HEATER #########
  - platform: template
    sensors:
      garage_safety_control_status:
        friendly_name: Garage Safety Control Status
        value_template: >
          {% set status = states.sensor.garage_safety_heartbeat.state != 'unavailable' %}
          {% set delay = ((as_timestamp(now()) - as_timestamp(states.sensor.garage_safety_heartbeat.last_changed))) < 15 %}
          
          {% if status and delay %}
            Running...
          {% else %}
            ERROR
          {% endif %}
        icon_template: >
          mdi:server
        availability_template: >
          {{ not is_state('sensor.garage_safety_heartbeat', 'unavailable') }}
        attribute_templates:
          heartbeat: "{{ states.sensor.garage_safety_heartbeat.state }}"
          f_temp: "{{ states.sensor.garage_safety_front_temperature.state }}"
          f_relay: "{{ states.binary_sensor.garage_front_safety_active.state == 'on' }}"
          f_aux: "{{ states.binary_sensor.garagefrontheater_ac.state == 'on' }}"
          f_coil: "{{ states.switch.garage_front_heater.state == 'on' }}"
          r_temp: "{{ states.sensor.garage_safety_rear_temperature.state }}"
          r_aux: "{{ states.binary_sensor.garagerearheater_ac.state == 'on' }}"
          r_relay: "{{ states.binary_sensor.garage_rear_safety_active.state == 'on' }}"
          r_coil: "{{ states.switch.garage_rear_heater.state == 'on' }}"
        
#   - platform: statistics
#     name: "Garage Safety Front Temp Stats"
#     entity_id: sensor.garage_safety_front_temperature
#     sampling_size: 6
#     max_age:
#       minutes: 1
#     precision: 1
    
#   - platform: statistics
#     name: "Garage Safety Rear Temp Stats"
#     entity_id: sensor.garage_safety_rear_temperature
#     sampling_size: 6
#     max_age:
#       minutes: 1
#     precision: 1
    
  - platform: min_max
    name: Garage Mean Temp
    round_digits: 1
    type: mean
    entity_ids:
      # - sensor.garage_safety_front_temp_raw
      # - sensor.garage_safety_rear_temp_raw
      - sensor.garage_safety_front_temperature
      - sensor.garage_safety_rear_temperature
      - sensor.garage_front_temp_raw
      - sensor.garage_rear_temp_raw
      
  - platform: history_stats
    name: Garage Front Heater Time
    entity_id: switch.garage_front_heater
    state: "on"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
      
  - platform: history_stats
    name: Garage Front Heater Count
    entity_id: switch.garage_front_heater
    state: "on"
    type: count
    end: "{{ now() }}"
    duration:
      hours: 24
      
  - platform: history_stats
    name: Garage Rear Heater Time
    entity_id: switch.garage_rear_heater
    state: "on"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
      
  - platform: history_stats
    name: Garage Rear Heater Count
    entity_id: switch.garage_rear_heater
    state: "on"
    type: count
    end: "{{ now() }}"
    duration:
      hours: 24
        
######### GARAGE SLAVE - BASIC DATA #########
  - platform: mqtt
    name: Garage Slave Control Status
    icon: mdi:server
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: >
      {% set status = value_json.state %}
      {% if status == "ON" %}
        Running...
      {% else %}
        ERROR
      {% endif %}
    json_attributes_topic: "Garage/Slave/Json"
    
  - platform: mqtt
    name: Garage Slave Box Temperature
    unit_of_measurement: '°C'
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.temp_in }}"
    
  - platform: mqtt
    name: Garage Slave Box Humidity
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    value_template: "{{ value_json.hum_in }}"
    qos: 0
    
  - platform: mqtt
    name: Garage Slave 5V Voltage
    icon: mdi:flash-outline
    unit_of_measurement: 'V'
    state_topic: "Garage/Slave/Json"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc5V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
      
######### GARAGE SLAVE - SENSORS #########
  - platform: mqtt
    name: Air Compressor Pressure Raw
    icon: mdi:gauge
    unit_of_measurement: 'psi'
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.air_press }}"
      
  - platform: template
    sensors:
      air_compressor_pressure:
        friendly_name: Air Compressor Pressure
        unit_of_measurement: 'psi'
        value_template: >
          {% set RP = states('sensor.air_compressor_pressure_raw')|float %}
          {% set min = 0.5|float %} 
          {% set span = 4.0|float %}
          {% set presmax = 200.0|float %}
          
          {% if RP < 104 and RP > 30 %}
            {% set RP = 104.0 %}
          {% endif %}
          
          {% set ax = (presmax / span)|float %}
          {% set b = (ax * min * -1.0)|float %}
          {% set ax = ((ax * 5.0) / 1023.0)|float %}
          
          {% set PV = ((ax*RP)+b)|float %}
          
          {% if PV < -0.2 or PV > presmax %}
            {{ "unknown" }}
          {% elif PV < 1.0 %}
            {{ 0.0 | round(1) }}
          {% elif is_state('binary_sensor.reset_sensors_graphs', 'on') %}
            {{ 0.0 | round(1) }}
          {% else %}
            {{ PV | round(1, "half") }}
          {% endif %}
        availability_template: >
          {{ not is_state('sensor.air_compressor_pressure_raw', 'unavailable') }}
        icon_template: mdi:gauge
        attribute_templates:
          pres_raw: "{{ states('sensor.air_compressor_pressure_raw') }}"
          
  - platform: mqtt
    name: Garage Air Valve
    icon: mdi:valve
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.air_garage }}"
    
  - platform: mqtt
    name: House Air Valve
    icon: mdi:valve
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    qos: 0
    value_template: "{{ value_json.air_house }}"
    