####################################################
# SENSORS - HA                                     #
####################################################

  #https://www.home-assistant.io/integrations/glances/
  
  #Home Assistant uptime
  - platform: uptime
    name: Uptime
    #unit_of_measurement: hours
    
  - platform: template
    sensors:
      time_online:
        friendly_name: Time Online
        icon_template: >
          mdi:clock
        value_template: >
          {% set value = states('sensor.uptime') %}
          {% set last_updated = as_timestamp(strptime(value, "%Y-%m-%d  %H:%M:%S")) %}
          {% set uptime = now().timestamp() - last_updated %}
          {% set days = (uptime / 86400) | float %}
          {% set hours = (days * 24) | float %}
          {% set minutes = (hours * 60) | float %}
          
          {% if days >= 1.0 %}
            {{ days | round(2) }} days ago
          {% elif hours >= 1.0 %}
            {{ hours | round(1) }} hours ago
          {% else %}
            {{ minutes | round(0) }} minutes ago
          {% endif %}

  #HA version
  # - platform: version
    # name: HA Installed Version
    
  - platform: command_line
    name: HA Installed Version
    command: "cat /config/.HA_VERSION"
    
  - platform: command_line
    name: HA Latest Version
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    scan_interval: 3600
    
#https://wiki.archlinux.org/index.php/APC_UPS
#Do a "apcaccess status" without quotes and use what's available there...
  - platform: apcupsd
    resources:
      - apc
      - date
      - hostname
      - version
      - upsname
      - cable
      - starttime
      - model
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      - lotrans
      - hitrans
      - battv
      - lastxfer
      - numxfers
      - tonbatt
      - cumonbatt
      - xoffbatt
      - battdate
      - nominv
      - nombattv
      - nompower
    
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
      
  - platform: sql
    db_url: !secret db_mysql
    scan_interval: 60
    queries:
      - name: MariaDB Size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema'
        column: 'value'
        unit_of_measurement: MB
    
  #Terminal command for network card name: ifconfig
  - platform: systemmonitor
    resources:
    # - type: processor_use
    # - type: disk_use_percent
      # arg: /
    # - type: memory_use_percent
    #- type: swap_use_percent
    - type: last_boot
    - type: load_1m
    - type: load_15m
    #IoT card
    - type: packets_in
      arg: hassio
    - type: packets_out
      arg: hassio
    - type: throughput_network_in
      arg: hassio
    - type: throughput_network_out
      arg: hassio
    - type: network_in
      arg: hassio
    - type: network_out
      arg: hassio
    #Internet card
    - type: packets_in
      arg: enp1s6
    - type: packets_out
      arg: enp1s6
    - type: throughput_network_in
      arg: enp1s6
    - type: throughput_network_out
      arg: enp1s6
    - type: network_in
      arg: enp1s6
    - type: network_out
      arg: enp1s6
