####################################################
# SENSORS - POND                                   #
####################################################
#See other sensors templates in Templates/t_pond.yaml

######### POND CONTROL - BASIC DATA #########
  - platform: mqtt
    name: "Pond Control Status"
    icon: mdi:fish
    state_topic: "Pond/Control/Json"
    availability:
      - topic: "Pond/Control/LWT"
    qos: 0
    value_template: >
      {% set status = value_json.state %}
      {% if status == "ON" %}
        Running...
      {% else %}
        ERROR
      {% endif %}
    json_attributes_topic: "Pond/Control/Json"

  - platform: mqtt
    name: "Pond Area Temperature"
    unit_of_measurement: '°C'
    state_topic: "Pond/Control/Json"
    availability:
      - topic: "Pond/Control/LWT"
    value_template: "{{ value_json.temp_out | float | round(1) }}"
    qos: 0

  - platform: mqtt
    name: "Pond Area Humidity"
    unit_of_measurement: '%'
    icon: mdi:water-percent
    state_topic: "Pond/Control/Json"
    availability:
      - topic: "Pond/Control/LWT"
    value_template: "{{ value_json.hum_out | float | round(1) }}"
    qos: 0
    
  - platform: mqtt
    name: "Pond Control Box Temperature"
    unit_of_measurement: '°C'
    state_topic: "Pond/Control/Json"
    availability:
      - topic: "Pond/Control/LWT"
    value_template: "{{ value_json.temp_in | float | round(1) }}"
    qos: 0
    
  - platform: mqtt
    name: "Pond Control Box Humidity"
    unit_of_measurement: '%'
    icon: mdi:water-percent
    state_topic: "Pond/Control/Json"
    availability:
      - topic: "Pond/Control/LWT"
    value_template: "{{ value_json.hum_in | float | round(1) }}"
    qos: 0
    
  - platform: mqtt
    name: "Pond Control 5V Voltage"
    unit_of_measurement: 'V'
    icon: mdi:flash-outline
    state_topic: "Pond/Control/Json"
    availability:
      - topic: "Pond/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc5V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
    
  - platform: mqtt
    name: "Pond Control 12V Voltage"
    unit_of_measurement: 'V'
    icon: mdi:flash-outline
    state_topic: "Pond/Control/Json"
    availability:
      - topic: "Pond/Control/LWT"
    qos: 0
    value_template: >
      {% set RV = value_json.Vcc12V | float %}
      
      {% if is_state('binary_sensor.reset_sensors_graphs', 'on') %}
        {{ 0.0 | round(1) }}
      {% else %}
        {{ RV | round(1) }}
      {% endif %}
      
#See other sensors templates in Templates/t_pond.yaml
    
######### POND CONTROL - SENSORS #########
  - platform: mqtt
    name: "Pond Temperature Raw"
    icon: mdi:oil-temperature
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    qos: 0
    unit_of_measurement: '° F'
    value_template: >
      {% set RT = value_json.wtemp|float %}
      {% set TF = ((-0.16883*RT)+162.57203)|float %}
      {{ TF | round(1) }}
      
  - platform: statistics
    name: "Pond Temperature Stats"
    entity_id: sensor.pond_temperature_raw
    max_age:
      minutes: 10
    precision: 1

#   - platform: mqtt
#     name: "Pond Pressure"
#     icon: mdi:gauge
#     state_topic: "Pond/Control/Sensors/Stts"
#     availability:
#       - topic: "Pond/Control/LWT"
#     qos: 0
#     unit_of_measurement: 'psi'
#     value_template: >
#       {% set RP = value_json.wpsi|float %}
#       {% set min = 0.5|float %} 
#       {% set span = 4.0|float %}
#       {% set presmax = 60.0|float %}
      
#       {% set ax = (presmax / span)|float %}
#       {% set b = (ax * min * -1.0)|float %}
#       {% set ax = ((ax * 5.0) / 1023.0)|float %}
      
#       {% set PV = ((ax*RP)+b)|float %}
      
#       {% if PV < 0 or PV > 35 %}
#         {{ "unknown" }}
#       {% else %}
#         {{ PV | round(1) }}
#       {% endif %}

  - platform: history_stats
    name: Pond Filler Timer
    entity_id: binary_sensor.pondfiller_status
    state: 'on'
    type: time
    end: '{{ now() }}'
    duration:
      hours: 24
