####################################################
# SENSORS - ROOMS                                  #
####################################################

########## MASSAGE ROOM ##########

  - platform: mqtt
    name: "Massage Room Temp"
    icon: mdi:mailbox
    state_topic: "Home/Massage/Clock/Json"
    availability:
      - topic: "Home/Massage/Clock/LWT"
    qos: 0
    value_template: "{{ value_json.temperature | round(1) }}"
    json_attributes_topic: "Home/Massage/Clock/Json"
    unit_of_measurement: '°C'
    
  - platform: mqtt
    name: "Massage Room Humidity"
    icon: mdi:mailbox
    state_topic: "Home/Massage/Clock/Json"
    availability:
      - topic: "Home/Massage/Clock/LWT"
    qos: 0
    value_template: "{{ value_json.humidity | round(1) }}"
    json_attributes_topic: "Home/Massage/Clock/Json"
    unit_of_measurement: '%'
    
  - platform: template
    sensors:
      massage_room_status:
        friendly_name: "Massage Room Status"
        value_template: >
          {% if is_state('switch.massage_room_appliances', 'on') %}
            {% if states('sensor.massage_room_power') | float >= 2 %}
              On
            {% else %}
              Off
            {% endif %}
          {% else %}
            Ready
          {% endif %}
        availability_template: >
          {{ not is_state('switch.massage_room_appliances', 'unavailable') }}
        icon_template: >
          mdi:pen
        attribute_templates:
          state: "{% if states.sensor.massage_room_data.state != 'unavailable' %}{{ states.sensor.massage_room_data.attributes.POWER | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          power: "{% if states.sensor.massage_room_power.state != 'unavailable' %}{{ states.sensor.massage_room_power.attributes.ENERGY.Power | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          voltage: "{% if states.sensor.massage_room_power.state != 'unavailable' %}{{ states.sensor.massage_room_power.attributes.ENERGY.Voltage | round(0) }}{% else %}{{ 'unknown' }}{% endif %}"
          current: "{% if states.sensor.massage_room_power.state != 'unavailable' %}{{ states.sensor.massage_room_power.attributes.ENERGY.Current | round(1) }}{% else %}{{ 'unknown' }}{% endif %}"
          p_factor: "{% if states.sensor.massage_room_power.state != 'unavailable' %}{{ states.sensor.massage_room_power.attributes.ENERGY.Factor | round(2) }}{% else %}{{ 'unknown' }}{% endif %}"
          today: "{% if states.sensor.massage_room_power.state != 'unavailable' %}{{ states.sensor.massage_room_power.attributes.ENERGY.Today | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          yesterday: "{% if states.sensor.massage_room_power.state != 'unavailable' %}{{ states.sensor.massage_room_power.attributes.ENERGY.Yesterday | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          total: "{% if states.sensor.massage_room_power.state != 'unavailable' %}{{ states.sensor.massage_room_power.attributes.ENERGY.Total | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_rssi: "{% if states.sensor.massage_room_data.state != 'unavailable' %}{{ states.sensor.massage_room_data.attributes.Wifi.Signal }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_percent: "{% if states.sensor.massage_room_data.state != 'unavailable' %}{{ states.sensor.massage_room_data.attributes.Wifi.RSSI }}{% else %}{{ 'unknown' }}{% endif %}"
    
  - platform: mqtt
    name: "Massage Room Data"
    state_topic: "Home/Massage/tele/STATE"
    value_template: "{{ value_json.POWER }}"
    # availability:
      # - topic: "Home/Massage/tele/LWT"
      # - payload_available: "Online"
      # - payload_not_available: "Offline"
    availability_topic: "Home/Massage/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    json_attributes_topic: "Home/Massage/tele/STATE"
    
  - platform: mqtt
    name: "Massage Room Power"
    state_topic: "Home/Massage/tele/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    # availability:
      # - topic: "Home/Massage/tele/LWT"
      # - payload_available: "Online"
      # - payload_not_available: "Offline"
    availability_topic: "Home/Massage/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    json_attributes_topic: "Home/Massage/tele/SENSOR"
    
########## THINKERING ROOM ##########

  - platform: template
    sensors:
      soldering_station_status:
        friendly_name: "Soldering Station Status"
        value_template: >
          {% if is_state('switch.soldering_station', 'on') %}
            {% if states('sensor.soldering_station_power') | float >= 2 %}
              On
            {% else %}
              Off
            {% endif %}
          {% else %}
            Ready
          {% endif %}
        availability_template: >
          {{ not is_state('switch.soldering_station', 'unavailable') }}
        icon_template: >
          mdi:pen
        attribute_templates:
          state: "{% if states.sensor.soldering_station_data.state != 'unavailable' %}{{ states.sensor.soldering_station_data.attributes.POWER | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          power: "{% if states.sensor.soldering_station_power.state != 'unavailable' %}{{ states.sensor.soldering_station_power.attributes.ENERGY.Power | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          voltage: "{% if states.sensor.soldering_station_power.state != 'unavailable' %}{{ states.sensor.soldering_station_power.attributes.ENERGY.Voltage | round(0) }}{% else %}{{ 'unknown' }}{% endif %}"
          current: "{% if states.sensor.soldering_station_power.state != 'unavailable' %}{{ states.sensor.soldering_station_power.attributes.ENERGY.Current | round(1) }}{% else %}{{ 'unknown' }}{% endif %}"
          p_factor: "{% if states.sensor.soldering_station_power.state != 'unavailable' %}{{ states.sensor.soldering_station_power.attributes.ENERGY.Factor | round(2) }}{% else %}{{ 'unknown' }}{% endif %}"
          today: "{% if states.sensor.soldering_station_power.state != 'unavailable' %}{{ states.sensor.soldering_station_power.attributes.ENERGY.Today | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          yesterday: "{% if states.sensor.soldering_station_power.state != 'unavailable' %}{{ states.sensor.soldering_station_power.attributes.ENERGY.Yesterday | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          total: "{% if states.sensor.soldering_station_power.state != 'unavailable' %}{{ states.sensor.soldering_station_power.attributes.ENERGY.Total | round(3) }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_rssi: "{% if states.sensor.soldering_station_data.state != 'unavailable' %}{{ states.sensor.soldering_station_data.attributes.Wifi.Signal }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_percent: "{% if states.sensor.soldering_station_data.state != 'unavailable' %}{{ states.sensor.soldering_station_data.attributes.Wifi.RSSI }}{% else %}{{ 'unknown' }}{% endif %}"
    
  - platform: mqtt
    name: "Soldering Station Data"
    state_topic: "Home/Soldering/tele/STATE"
    value_template: "{{ value_json.POWER }}"
    qos: 1
    # availability:
      # - topic: "Home/Soldering/tele/LWT"
      # - payload_available: "Online"
      # - payload_not_available: "Offline"
    availability_topic: "Home/Soldering/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    json_attributes_topic: "Home/Soldering/tele/STATE"
    
  - platform: mqtt
    name: "Soldering Station Power"
    state_topic: "Home/Soldering/tele/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    # availability:
      # - topic: "Home/Soldering/tele/LWT"
      # - payload_available: "Online"
      # - payload_not_available: "Offline"
    availability_topic: "Home/Soldering/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    json_attributes_topic: "Home/Soldering/tele/SENSOR"

########## MASTER BEDROOM ##########
    
  - platform: mqtt
    name: "Master Bed Raw"
    icon: mdi:scale
    #unit_of_measurement: 'lb'
    state_topic: "Home/Master/Bed/Sensors/Stts"
    availability:
      - topic: "Home/Master/Bed/LWT"
    qos: 0
    value_template: "{{ value_json.scale | round(1) }}"
    json_attributes_topic: "Home/Master/Bed/Sensors/Stts"
    
  - platform: template
    sensors:
      master_bed_presence:
        friendly_name: Master Bed Presence
        icon_template: mdi:bed-empty
        # value_template: >
        #   {% set weight = states('sensor.master_bed_raw') | float %}
        #   {% set jean = is_state('person.jean_gauthier', 'home') %}
        #   {% set cindy = is_state('person.cindy_fortin', 'home') %}
          
        #   {% if weight < 30 %}
        #     Empty
        #   {% elif weight < 200 %}
        #     Mi-Loup
        #   {% elif weight < 900 and cindy %}
        #     Cindy
        #   {% elif weight < 1200 and jean %}
        #     Jean
        #   {% elif cindy and jean %}
        #     Cindy & Jean
        #   {% else %}
        #     ERROR
        #   {% endif %}
        value_template: >
          {% set weight = states('sensor.master_bed_raw') | float %}
          {% set jean = is_state('person.jean_gauthier', 'home') %}
          {% set cindy = is_state('person.cindy_fortin', 'home') %}
          
          {% if weight < 30 %}
            Empty
          {% elif weight < 200 %}
            Mi-Loup
          {% else%}
            Someone In Bed
          {% endif %}
        availability_template: "{{ not is_state('sensor.master_bed_raw', 'unavailable') }}"
        attribute_templates:
          state: "{% if states('switch.master_bed_tare') != 'unavailable' %}{{ state_attr('switch.master_bed_tare', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
          version: "{% if states('switch.master_bed_tare') != 'unavailable' %}{{ state_attr('switch.master_bed_tare', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
          date: "{% if states('switch.master_bed_tare') != 'unavailable' %}{{ state_attr('switch.master_bed_tare', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
          vcc_3v3: "{% if states('switch.master_bed_tare') != 'unavailable' %}{{ state_attr('switch.master_bed_tare', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_ssid: "{% if states('switch.master_bed_tare') != 'unavailable' %}{{ state_attr('switch.master_bed_tare', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_rssi: "{% if states('switch.master_bed_tare') != 'unavailable' %}{{ state_attr('switch.master_bed_tare', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
          wifi_percent: "{% if states('switch.master_bed_tare') != 'unavailable' %}{{ state_attr('switch.master_bed_tare', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
          raw_value: "{{ states('sensor.master_bed_raw') }}"
          calib: "{% if states('sensor.master_bed_raw') != 'unavailable' %}{{ state_attr('sensor.master_bed_raw', 'calib') }}{% else %}{{ 'unknown' }}{% endif %}"
          