####################################################
# SENSORS - THERMOSTATS                            #
####################################################
#See other sensors templates in Templates/t_thermostats.yaml

  - platform: mqtt
    name: "Living Room Temp"
    icon: mdi:thermometer
    unit_of_measurement: '°C'
    state_topic: "Home/Living/Therm/Json"
    availability:
      - topic: "Home/Living/Therm/LWT"
    qos: 0
    value_template: "{{ value_json.room_temp }}"
    json_attributes_topic: "Home/Living/Therm/Json"
    
  - platform: mqtt
    name: "Living Room Hum"
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Home/Living/Therm/Json"
    availability:
      - topic: "Home/Living/Therm/LWT"
    qos: 0
    value_template: "{{ value_json.room_hum }}"
    
  - platform: mqtt
    name: "Garage Front Temp Raw"
    icon: mdi:thermometer
    unit_of_measurement: '°C'
    state_topic: "Garage/Front/Therm/Json"
    availability:
      - topic: "Garage/Front/Therm/LWT"
    qos: 0
    value_template: >
      {% set room = value_json.room_temp %}
      
      {% if room|string == '---' or room|string == 'unknown' or room|float == -99.9 or room|float == -1 %}
        {{ Unknown }}
      {% else %}
        {{ room | round(1) }}
      {% endif %}
    json_attributes_topic: "Garage/Front/Therm/Json"
    
  - platform: mqtt
    name: "Garage Front Hum"
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Garage/Front/Therm/Json"
    availability:
      - topic: "Garage/Front/Therm/LWT"
    qos: 0
    value_template: "{{ value_json.room_hum }}"
    
  - platform: mqtt
    name: "Garage Rear Temp Raw"
    icon: mdi:thermometer
    unit_of_measurement: '°C'
    state_topic: "Garage/Rear/Therm/Json"
    availability:
      - topic: "Garage/Rear/Therm/LWT"
    qos: 0
    value_template: >
      {% set room = value_json.room_temp %}
      
      {% if room|string == '---' or room|string == 'unknown' or room|float == -99.9 or room|float == -1 %}
        {{ Unknown }}
      {% else %}
        {{ room | round(1) }}
      {% endif %}
    json_attributes_topic: "Garage/Rear/Therm/Json"
    
  - platform: mqtt
    name: "Garage Rear Hum"
    icon: mdi:water-percent
    unit_of_measurement: '%'
    state_topic: "Garage/Rear/Therm/Json"
    availability:
      - topic: "Garage/Rear/Therm/LWT"
    qos: 0
    value_template: "{{ value_json.room_hum }}"
    
#See other sensors templates in Templates/t_thermostats.yaml
    