####################################################
# LIGHTS - MQTT - ALL OTHERS                       #
####################################################

# MQTT WHITE, RGB or RGBW analog led strips (MiLight ESP hack)
# https://github.com/corbanmailloux/esp-mqtt-rgb-led
# RGBW:
  - name: Master Bedroom RGBW
    schema: json
    state_topic: "Home/Milight/Stts/1"
    command_topic: "Home/Milight/Cmd/1"
    # availability:
      # - topic: "Home/Transmitter/LWT"
    brightness: true
    brightness_scale: 255
    color_mode: true
    supported_color_modes: ['rgbw']
    effect: true
    effect_list: [Smooth, WhiteFade, FadeRGBW, JumpRainbow, RandomColor, RedEffect, GrnEffect, BluEffect, CycleAll]
    optimistic: false
    retain: true
    qos: 0
    
  - name: Under Bar RGBW
    schema: json
    state_topic: "Home/Milight/Stts/2"
    command_topic: "Home/Milight/Cmd/2"
    # availability:
      # - topic: "Home/Transmitter/LWT"
    brightness: true
    brightness_scale: 255
    color_mode: true
    supported_color_modes: ['rgbw']
    effect: true
    effect_list: [Smooth, WhiteFade, FadeRGBW, JumpRainbow, RandomColor, RedEffect, GrnEffect, BluEffect, CycleAll]
    optimistic: false
    retain: true
    qos: 0
    
  - name: Pool Water RGB
    schema: json
    state_topic: "Pool/Milight/Stts/3"
    command_topic: "Pool/Milight/Cmd/3"
    availability:
      - topic: "Pool/Control/LWT"
    brightness: true
    brightness_scale: 255
    color_mode: true
    supported_color_modes: ['rgb']
    effect: true
    effect_list: [Smooth, WhiteFade, FadeRGB, JumpRainbow, RandomColor, RedEffect, GrnEffect, BluEffect, CycleAll]
    optimistic: false
    qos: 0
    
  - name: Nixie Clock RGB
    schema: json
    state_topic: "Home/NixieClock/LED/Stts"
    command_topic: "Home/NixieClock/LED/Cmd"
    availability:
      - topic: "Home/NixieClock/LWT"
    brightness: false
    brightness_scale: 255
    color_mode: true
    supported_color_modes: ['rgb']
    effect: true
    effect_list: [Fixed, Pulse, Cycle, FixedDim, PulseDim, CycleDim]
    optimistic: false
    qos: 0
    
  - name: Nixie Clock
    schema: json
    state_topic: "Home/NixieClock/Stts"
    command_topic: "Home/NixieClock/Cmd"
    availability:
      - topic: "Home/NixieClock/LWT"
    brightness: false
    brightness_scale: 255
    color_mode: false
    supported_color_modes: ['onoff']
    effect: false
    optimistic: false
    qos: 0
    
  - name: Massage Clock RGB
    schema: json
    state_topic: "Home/Massage/Clock/LED/Stts"
    command_topic: "Home/Massage/Clock/LED/Cmd"
    availability:
      - topic: "Home/Massage/Clock/LWT"
    brightness: true
    brightness_scale: 255
    color_mode: true
    supported_color_modes: ['rgb']
    effect: true
    effect_list: [Default, RainbowCycle, Red/Green, Orange/Purple, Yellow/Purple, Red/White, Red/Green Cycle, Orange/Purple Cycle, Yellow/Purple Cycle, Red/White Cycle]
    optimistic: false
    qos: 0
    json_attributes_topic: "Home/Massage/Clock/Json"
    
  - name: Pool Clock
    schema: json
    state_topic: "Pool/Clock/LED/Stts"
    command_topic: "Pool/Clock/LED/Cmd"
    availability:
      - topic: "Pool/Clock/LWT"
    brightness: true
    brightness_scale: 255
    color_mode: true
    supported_color_modes: ['rgb']
    effect: true
    effect_list: [Default, RainbowCycle, TextColor, Spoon, VertRainbowCycle, HorizRainbowCycle, TextChaser, AllEffectsRolling]
    optimistic: false
    qos: 0
    
  - name: Garage Clock
    schema: json
    state_topic: "Garage/Clock/LED/Stts"
    command_topic: "Garage/Clock/LED/Cmd"
    availability:
      - topic: "Garage/Clock/LWT"
    brightness: true
    brightness_scale: 255
    color_mode: true
    supported_color_modes: ['rgb']
    effect: true
    effect_list: [Default, RainbowCycle, TextColor, Spoon, VertRainbowCycle, HorizRainbowCycle, TextChaser, AllEffectsRolling]
    optimistic: false
    qos: 0

# ### MAESTRO - Master Bedroom ==> SN:00001 ###
  # - name: Master Bedroom - Light
    # schema: json
    # state_topic: "Home/Maestro/S00001/LMP/Stts"
    # command_topic: "Home/Maestro/S00001/LMP/Cmd"
    # availability:
      # - topic: "Home/Maestro/S00001/LWT"
    # brightness: true
    # brightness_scale: 7
    # rgb: false
    # white_value: false
    # effect: false
    # optimistic: false
    # qos: 0
    # json_attributes_topic: "Home/Maestro/S00001/Json"
    
  # - name: Master Bedroom - Fan
    # schema: json
    # state_topic: "Home/Maestro/S00001/FAN/Stts"
    # command_topic: "Home/Maestro/S00001/FAN/Cmd"
    # availability:
      # - topic: "Home/Maestro/S00001/LWT"
    # brightness: true
    # brightness_scale: 7
    # rgb: false
    # white_value: false
    # effect: false
    # optimistic: false
    # qos: 0
    # json_attributes_topic: "Home/Maestro/S00001/Json"
    
# ### MAESTRO - 1st Bedroom ==> SN:00002###
  # - name: Bedroom 1 - Light
    # schema: json
    # state_topic: "Home/Maestro/S00002/LMP/Stts"
    # command_topic: "Home/Maestro/S00002/LMP/Cmd"
    # availability:
      # - topic: "Home/Maestro/S00002/LWT"
    # brightness: true
    # brightness_scale: 7
    # rgb: false
    # white_value: false
    # effect: false
    # optimistic: false
    # qos: 0
    # json_attributes_topic: "Home/Maestro/S00002/Json"
    
  # - name: Bedroom 1 - Fan
    # schema: json
    # state_topic: "Home/Maestro/S00002/FAN/Stts"
    # command_topic: "Home/Maestro/S00002/FAN/Cmd"
    # availability:
      # - topic: "Home/Maestro/S00002/LWT"
    # brightness: true
    # brightness_scale: 7
    # rgb: false
    # white_value: false
    # effect: false
    # optimistic: false
    # qos: 0
    # json_attributes_topic: "Home/Maestro/S00002/Json"
    
# ### MAESTRO - 2nd Bedroom ==> SN:00003 ###
  # - name: Bedroom 2 - Light
    # schema: json
    # state_topic: "Home/Maestro/S00003/LMP/Stts"
    # command_topic: "Home/Maestro/S00003/LMP/Cmd"
    # availability:
      # - topic: "Home/Maestro/S00003/LWT"
    # brightness: true
    # brightness_scale: 7
    # rgb: false
    # white_value: false
    # effect: false
    # optimistic: false
    # qos: 0
    # json_attributes_topic: "Home/Maestro/S00003/Json"
    
  # - name: Bedroom 2 - Fan
    # schema: json
    # state_topic: "Home/Maestro/S00003/FAN/Stts"
    # command_topic: "Home/Maestro/S00003/FAN/Cmd"
    # availability:
      # - topic: "Home/Maestro/S00003/LWT"
    # brightness: true
    # brightness_scale: 7
    # rgb: false
    # white_value: false
    # effect: false
    # optimistic: false
    # qos: 0
    # json_attributes_topic: "Home/Maestro/S00003/Json"
    