####################################################
# AUTOMATION - CAMERAS                             #
####################################################

  - alias: "Camera Mode Change - Pool Area"
    mode: restart
    trigger:
      platform: state
      entity_id: input_select.camera_mode_poolarea
    action:
    - service: mqtt.publish
      data_template:
        topic: "Camera/Out/Pool/Lamp/Cmd"
        payload: '{"res":"{{ trigger.to_state.state }}"}'
        qos: 0
        retain: false
    - service: switch.turn_off
      entity_id: switch.camera_poolarea
    - delay:
        seconds: 1
    - service: switch.turn_on
      entity_id: switch.camera_poolarea
        
  - alias: "Camera Mode Select - Pool Area"
    mode: restart
    trigger:
      platform: mqtt
      topic: "Camera/Pool/Json"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.camera_mode_poolarea
          option: '{{ trigger.payload_json.res }}'
      # - service: persistent_notification.create
        # data_template:
          # message: '{{ trigger.payload_json.res }}'