###################################################
# AUTOMATIONS - POOL                              #
###################################################

  #Spring mode, runs pump all day, stop 4h, run 4h, stop 4h, run 12h
  #Summer mode, runs pump based on day of week (runs longer on fridays/saturdays)
  #Autumn mode, pump not running on peak hours
  #If outisde temperature drops below 5°C, run pump
  #Pool water level has to be above low level since 2 minutes
  - alias: Pool Pump Control
    mode: restart
    trigger:
      - platform: time_pattern
        seconds: '/5'
      - platform: state
        entity_id: input_select.poolpump_mode
    action:
      entity_id: switch.pool_pump
      service_template: >
        {% set curHour = now().hour %}
        {% set curWeekday = now().weekday() %}
        {% set PP = false %}
        
        {% if is_state('input_select.poolpump_mode', '24/7') %}
          {% set PP = true %}
        {% elif is_state('input_select.poolpump_mode', 'Spring') %}
          {% if curHour >= 8 and curHour < 20 %}
            {% set PP = true %}
          {% elif curHour >= 0 and curHour < 4 %}
            {% set PP = true %}
          {% endif %}
        {% elif is_state('input_select.poolpump_mode', 'Summer') %}
          {% if curWeekday in (0,1,2,3,6) %}
            {% if curHour >= 7 and curHour < 19 %}
              {% set PP = true %}
            {% elif curHour >= 23 or curHour < 3 %}
              {% set PP = true %}
            {% endif %}
          {% else %}
            {% if curHour >= 6 and curHour < 23 %}
              {% set PP = true %}
            {% elif curHour >= 1 and curHour < 4 %}
              {% set PP = true %}
            {% endif %}
          {% endif %}
        {% elif is_state('input_select.poolpump_mode', 'Autumn') %}
          {% if curHour >= 2 and curHour < 6 %}
            {% set PP = true %}
          {% elif curHour >= 9 and curHour < 11 %}
            {% set PP = true %}
          {% elif curHour >= 14 and curHour < 16 %}
            {% set PP = true %}
          {% elif curHour >= 21 and curHour < 23 %}
            {% set PP = true %}
          {% endif %}
        {% endif %}
        
        {% if not is_state('input_select.poolpump_mode', 'Winter/Off') and is_state('binary_sensor.antifreeze_active', 'on') %}
          {% set PP = true %}
        {% endif %}
        
        {% set lastLevel = as_timestamp(now()) - as_timestamp(states.binary_sensor.pool_level_low.last_changed) %}
        {% if is_state('binary_sensor.pool_level_low', 'off') and lastLevel >= 120 %}
          {% set PP = false %}
        {% endif %}
        
        {% if PP == true %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
        
######## POOL HEATER ########

  #Auto mode, runs heater whenever temperature is below setpoint + 2°C
  - alias: Pool Heater Control
    mode: restart
    trigger:
      - platform: time_pattern
        seconds: '/5'
      - platform: state
        entity_id: input_select.poolheat_mode
    action:
      entity_id: switch.pool_heater
      service_template: >
        {% set curHour = now().hour %}
        {% set curWeekday = now().weekday() %}
        {% set PH = false %}
        
        {% if is_state('input_select.poolheat_mode', '24/7') %}
          {% set PH = true %}
        {% elif is_state('input_select.poolheat_mode', 'Auto') %}
          {% set PH = true %}
        {% endif %}
        
        {% if PH == true %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
        
######## POOL REFILL ########

  #Pool water level has to be below high level since 'delayStart' minutes
  #Pool pump mode shall not be in Winter mode
  #Filler valve can't operate more than 'maxDailyTime' per 24h period
    #Unless it is set to 0 or -1, then there's unlimited daily time
  #Filler will start 'delayStart' minutes after level been below the high level and stop 'delayStop' minutes after it has been reached and maintained
    #If you want to stop it, simply turn off filler valve (high level sensor MUST be ON otherwise filler valve will turn on again)
  - alias: Pool Filler Control
    mode: restart
    trigger:
      - platform: time_pattern
        seconds: '/5'
    condition:
      - condition: template
        value_template: "{{ not is_state('input_select.poolfiller_mode', 'Manual') }}"
    action:
      entity_id: switch.pool_filler_valve
      service_template: >
        {% set lastLevel = (as_timestamp(now()) - as_timestamp(states.binary_sensor.pool_level_high.last_changed))/60 %}
        {% set lastStateOff = is_state('binary_sensor.pool_level_high', 'off') %}
        {% set lastSwitch = is_state('switch.pool_filler_valve', 'on') %}
        {% set lastDay = states('sensor.pool_filler_timer')|float %}
        {% set poolRunning = is_state('input_boolean.pool_running', 'on') %}
        {% set delayStart = states('input_number.pool_filler_start')|int %}
        {% set delayStop = states('input_number.pool_filler_stop')|int %}
        
        {% if states('input_number.pool_filler_runtime')|int <= 0 %}
          {% set maxDailyTime = 25 %}
        {% else %}
          {% set maxDailyTime = states('input_number.pool_filler_runtime')|int/60 %}
        {% endif %}
        
        {% set PF = false %}
        
        {% if lastSwitch %}
          {% if lastStateOff %}
            {% set PF = true %}
          {% elif lastLevel <= delayStop %}
            {% set PF = true %}
          {% endif %}
        {% elif lastStateOff and lastLevel >= delayStart and lastDay <= ((maxDailyTime*60-delayStop)/60) %}
          {% set PF = true %}
        {% endif %}
        
        {% if lastDay >= maxDailyTime %}
          {% set PF = false %}
        {% elif is_state('input_select.poolfiller_mode', 'Winter/Off') or is_state('input_select.poolpump_mode', 'Winter/Off') %}
          {% set PF = false %}
        {% elif is_state('binary_sensor.pool_level_high', 'unavailable') %}
          {% set PF = false %}
        {% elif is_state('group.irrigation', 'on') %}
          {% set PF = false %}
        {% endif %}
                
        {% if PF == true and poolRunning %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
        
######## POOL VALVES ########
        
  - alias: "Pool Drain Adjust"
    mode: restart
    trigger:
      platform: state
      entity_id: input_number.pool_drain_percent
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Control/Cmd"
        payload: '{"drain":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
  - alias: "Pool Slide Adjust"
    mode: restart
    trigger:
      platform: state
      entity_id: input_number.pool_slide_percent
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Control/Cmd"
        payload: '{"slide":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
  - alias: "Pool Heatpump Adjust"
    trigger:
      platform: state
      entity_id: input_number.pool_heatpump_percent
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Control/Cmd"
        payload: '{"heatp":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
######## POOL CLOCK ########
        
  #Input Text Changes Trigger
  - alias: Pool Top Text Change
    mode: restart
    trigger:
      platform: state
      entity_id: input_text.pool_text_top
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/Cmd"
        payload: '{"uptxt":"{{ trigger.to_state.state }}"}'
        qos: 0
        retain: false
        
  - alias: Pool Bottom Text Change
    mode: restart
    trigger:
      platform: state
      entity_id: input_text.pool_text_bottom
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/Cmd"
        payload: '{"dntxt":"{{ trigger.to_state.state }}"}'
        qos: 0
        retain: false

  - alias: "Pool Clock Scroll Speed"
    mode: restart
    trigger:
      platform: state
      entity_id: input_number.pool_clock_scroll_speed
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/Cmd"
        payload: '{"scroll":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
  - alias: "Pool Clock Transistion Speed"
    mode: restart
    trigger:
      platform: state
      entity_id: input_number.pool_clock_trans_speed
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/LED/Cmd"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false

#Publish data to device every minute or when a device requests an update (boot up or invalid data detected (by the device))
  - alias: Publish Pool Clock Data
    mode: restart
    trigger:
      - platform: time_pattern
        minutes: '/1'
      - platform: mqtt
        topic: "Home/Global/Time/Request"
        payload: 'ON'
        encoding: 'utf-8'
    action:
      - service: mqtt.publish
        data_template:
          topic: "Pool/Clock/Cmd"
          payload_template: '{"wtemp":"{{states.sensor.pool_temperature.state}}","wph":"{{states.sensor.pool_ph.state}}","otemp":"{{states.sensor.outdoor_temperature.state}}","ohum":"{{states.sensor.outdoor_humidity.state}}"}'
          qos: 0
          retain: false

  - alias: Publish Pool Pressure Data
    mode: restart
    trigger:
      - platform: time_pattern
        minutes: '/1'
      - platform: state
        entity_id: sensor.pool_pressure
      - platform: state
        entity_id: sensor.pool_fd_status
    action:
      - service: mqtt.publish
        data_template:
          topic: "Pool/Pressure/Cmd"
          payload_template: >
            {% if is_state('sensor.pool_fd_status', 'Unlocked') or is_state('sensor.pool_fd_status', 'Ok') %}
              {"state":"OFF", "wpsi":"{{states.sensor.pool_pressure.state}}"}
            {% else %}
              {"state":"ON", "wpsi":"{{states.sensor.pool_pressure.state}}"}
            {% endif %}
          qos: 0
          retain: false
          