####################################################
# LOCKS - MQTT - ALL OTHERS                        #
####################################################

  - name: House FD Lock
    state_topic: "Home/Door/Front/Sensors/Stts"
    command_topic: "Home/Door/Front/Cmd"
    availability:
      - topic: "Home/Door/Front/LWT"
    json_attributes_topic: "Home/Door/Front/Sensors/Stts"
    <<: &template_powerbolt_lock
      value_template: '{{ value_json.locked }}'
      state_locked: "locked"
      state_unlocked: "unlocked"
      retain: false
      optimistic: false
      qos: 0
    <<: &template_powerbolt_lock_right
      payload_lock: '{"lock": "lock", "mode":"right"}'
      payload_unlock: '{"lock": "unlock", "mode":"right"}'
      
  - name: House SD Lock
    state_topic: "Home/Door/Side/Sensors/Stts"
    command_topic: "Home/Door/Side/Cmd"
    availability:
      - topic: "Home/Door/Side/LWT"
    json_attributes_topic: "Home/Door/Side/Sensors/Stts"
    <<: *template_powerbolt_lock
    <<: &template_powerbolt_lock_left
      payload_lock: '{"lock": "lock", "mode":"left"}'
      payload_unlock: '{"lock": "unlock", "mode":"left"}'

  - name: House BD Lock
    state_topic: "Home/Door/Back/Sensors/Stts"
    command_topic: "Home/Door/Back/Cmd"
    availability:
      - topic: "Home/Door/Back/LWT"
    json_attributes_topic: "Home/Door/Back/Sensors/Stts"
    <<: *template_powerbolt_lock
    # <<: &template_powerbolt_lock_unlock
      # payload_lock: '{"lock": "lock", "mode":"unlock"}'
      # payload_unlock: '{"lock": "unlock", "mode":"unlock"}'
    <<: &template_powerbolt_lock_relock
      payload_lock: '{"lock": "lock", "mode":"relock"}'
      payload_unlock: '{"lock": "unlock", "mode":"relock"}'
      
  - name: House MBD Lock
    state_topic: "Home/Door/MasterBack/Sensors/Stts"
    command_topic: "Home/Door/MasterBack/Cmd"
    availability:
      - topic: "Home/Door/MasterBack/LWT"
    json_attributes_topic: "Home/Door/MasterBack/Sensors/Stts"
    <<: *template_powerbolt_lock
    # <<: &template_powerbolt_lock_unlock
      # payload_lock: '{"lock": "lock", "mode":"unlock"}'
      # payload_unlock: '{"lock": "unlock", "mode":"unlock"}'
    <<: *template_powerbolt_lock_relock

  - name: Garage FD Lock
    state_topic: "Garage/Door/Front/Sensors/Stts"
    command_topic: "Garage/Door/Front/Cmd"
    availability:
      - topic: "Garage/Door/Front/LWT"
    json_attributes_topic: "Garage/Door/Front/Sensors/Stts"
    <<: *template_powerbolt_lock
    <<: *template_powerbolt_lock_left

  - name: Shed FD Lock
    state_topic: "Shed/Door/Front/Sensors/Stts"
    command_topic: "Shed/Door/Front/Cmd"
    availability:
      - topic: "Shed/Door/Front/LWT"
    json_attributes_topic: "Shed/Door/Front/Sensors/Stts"
    <<: *template_powerbolt_lock
    <<: *template_powerbolt_lock_right

  - name: Glasshouse FD Lock
    state_topic: "Glass/Door/Front/Sensors/Stts"
    command_topic: "Glass/Door/Front/Cmd"
    availability:
      - topic: "Glass/Door/Front/LWT"
    json_attributes_topic: "Glass/Door/Front/Sensors/Stts"
    <<: *template_powerbolt_lock
    <<: *template_powerbolt_lock_right

  - name: Pool FD Lock
    state_topic: "Pool/Control/Sensors/Stts"
    command_topic: "Pool/Control/Relay/Cmd"
    availability:
      - topic: "Pool/Control/LWT"
    json_attributes_topic: "Pool/Door/Cabin/Sensors/Stts"
    payload_lock: '{"rX":"ON", "hX":"2.0"}'
    payload_unlock: '{"rY":"ON", "hY":"2.0"}'
    <<: &template_relay_lock
      value_template: '{{ value_json.locked }}'
      state_locked: "locked"
      state_unlocked: "unlocked"
      retain: false
      optimistic: false
      qos: 0
      
  - name: Pool TD Lock
    state_topic: "ExtToilet/Control/Sensors/Stts"
    command_topic: "ExtToilet/Control/Relay/Cmd"
    availability:
      - topic: "ExtToilet/Control/LWT"
    json_attributes_topic: "ExtToilet/Door/Cabin/Sensors/Stts"
    payload_lock: '{"rX":"ON", "hX":"2.0"}'
    payload_unlock: '{"rY":"ON", "hY":"2.0"}'
    <<: *template_relay_lock
      
