####################################################
# BINARY SENSORS - CONTROL ROOM                    #
####################################################
#See other sensors templates in Templates/t_controlroom.yaml

  - platform: mqtt
    name: Water Valve Opened
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.water_on }}'
    qos: 0
    
  - platform: mqtt
    name: Water Valve Closed
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.water_off }}'
    qos: 0
    
  - platform: mqtt
    name: Control Room Light
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.crlight }}'
    qos: 0
    
  - platform: mqtt
    name: Control Room Door
    device_class: door
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.crdoor }}'
    qos: 0
 