####################################################
# BINARY SENSORS - CONTROL ROOM                    #
####################################################
        
  - platform: mqtt
    name: Water Valve Opened
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.water_on }}'
    qos: 0
    
  - platform: mqtt
    name: Water Valve Closed
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.water_off }}'
    qos: 0
    
  - platform: mqtt
    name: Control Room Light
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.crlight }}'
    qos: 0
    
  - platform: mqtt
    name: Control Room Door
    device_class: door
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.crdoor }}'
    qos: 0
    
  - platform: template
    sensors:
      water_heater_flow:
        friendly_name: Water Heater Flow
        value_template: >
          {{ states('sensor.water_heater_flow')|int > 1 }}
        availability_template: >
          {{ not is_state('sensor.water_heater_status', 'unavailable') }}
        icon_template: >
          {% if is_state('switch.water_heater', 'off') %}
            mdi:radiator-off
          {% elif states('sensor.water_heater_flow')|int > 1 %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}

      poweroutlet_status:
        friendly_name: Power Outlet
        # friendly_name: >-
        #   {% if is_state('input_select.poweroutlet_mode', 'Halloween Decorations') or is_state('input_select.poweroutlet_mode', 'Christmas Decorations') or is_state('input_select.poweroutlet_mode', 'Fountain') %}
        #     {{ states.input_select.poweroutlet_mode.state }}
        #   {% else %}
        #     Power Outlet
        #   {% endif %}
        value_template: >
          {{ is_state('switch.power_outlet', 'on') }}
        availability_template: >
          {{ not is_state('switch.power_outlet', 'unavailable') }}
        icon_template: >
          {% if is_state('input_select.poweroutlet_mode', '24/7') %}
            mdi:power-plug
          {% elif is_state('input_select.poweroutlet_mode', 'Halloween Decorations') %}
            mdi:pumpkin
          {% elif is_state('input_select.poweroutlet_mode', 'Christmas Decorations') %}
            mdi:pine-tree
          {% elif is_state('input_select.poweroutlet_mode', 'Fountain') %}
            mdi:fountain
          {% else %}
            mdi:power-plug-off
          {% endif %}
        attribute_templates:
          mode: "{{ states('input_select.poweroutlet_mode') }}"
          schedule: >-
            {% if is_state('input_select.poweroutlet_mode', '24/7') %}
              Always ON
            {% elif is_state('input_select.poweroutlet_mode', 'Fountain') %}
              Turns ON at sunrise until 10PM. Will turn ON if outside temperature is freezing
            {% elif is_state('input_select.poweroutlet_mode', 'Halloween Decorations') %}
              Turns ON an hour before sunset or at 4PM, turns OFF at 11PM. On Halloween night, turns ON at 7AM until midnight
            {% elif is_state('input_select.poweroutlet_mode', 'Christmas Decorations') %}
              Turns ON an hour before sunset or at 4PM, turns OFF at 11PM. On Christmas night, turns ON at 7AM until midnight
            {% else %}
              Always OFF
            {% endif %}
          
      lamppost_status:
        friendly_name: Lamp Post
        value_template: >
          {{ is_state('switch.lamp_post', 'on') }}
        availability_template: >
          {{ not is_state('switch.lamp_post', 'unavailable') }}
        icon_template: >
          {% if is_state('input_select.lamppost_mode', 'Force Off') %}
            mdi:lightbulb-off
          {% else %}
            mdi:lightbulb
          {% endif %}
        attribute_templates:
          mode: "{{ states('input_select.lamppost_mode') }}"
          schedule: >-
            {% if is_state('input_select.lamppost_mode', '24/7') %}
              Always ON
            {% elif is_state('input_select.lamppost_mode', 'Sunset to 23h') %}
              Turns ON at sunset until 23h
            {% elif is_state('input_select.lamppost_mode', 'Sunset to Sunrise') %}
              Turns ON at sunset until sunrise next day
            {% else %}
              Always OFF
            {% endif %}
            
      frontdoorlight_status:
        friendly_name: Front Door Light
        value_template: >
          {{ is_state('switch.front_door_light', 'on') }}
        availability_template: >
          {{ not is_state('switch.front_door_light', 'unavailable') }}
        icon_template: >
          mdi:lightbulb
        attribute_templates:
          mode: >-
            Synch'd on change with the lamp post for now
          
      frontyardirrigation_status:
        friendly_name: Frontyard Irrigation
        value_template: >
          {{ is_state('switch.frontyard_irrigation', 'on') }}
        availability_template: >
          {{ not is_state('switch.frontyard_irrigation', 'unavailable') }}
        icon_template: >
          {% if is_state('input_select.frontyardirrigation_mode', 'Winter/Off') %}
            mdi:water-off
          {% else %}
            mdi:water
          {% endif %}
          
      backyardirrigation_status:
        friendly_name: Backyard Irrigation
        value_template: >
          {{ is_state('switch.backyard_irrigation', 'on') }}
        availability_template: >
          {{ not is_state('switch.backyard_irrigation', 'unavailable') }}
        icon_template: >
          {% if is_state('input_select.backyardirrigation_mode', 'Winter/Off') %}
            mdi:water-off
          {% else %}
            mdi:water
          {% endif %}
          
      gardenirrigation_status:
        friendly_name: Garden Irrigation
        value_template: >
          {{ is_state('switch.garden_irrigation', 'on') }}
        availability_template: >
          {{ not is_state('switch.garden_irrigation', 'unavailable') }}
        icon_template: >
          {% if is_state('input_select.gardenirrigation_mode', 'Winter/Off') %}
            mdi:water-off
          {% else %}
            mdi:water
          {% endif %}
          