####################################################
# BINARY SENSORS - GARAGE                          #
####################################################
#See other sensors templates in Templates/t_garage.yaml

######### GARAGE MAIN #########

          
  - platform: mqtt
    name: Garage Attic Light
    state_topic: "Garage/Control/Sensors/Stts"
    availability:
      - topic: "Garage/Control/LWT"
    value_template: '{{ value_json.attic_light }}'
    qos: 0
          
######### GARAGE SLAVE #########
  - platform: mqtt
    name: Garage Air Valve Closed
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    value_template: '{{ value_json.air_gclosed }}'
    qos: 0
    
  - platform: mqtt
    name: House Air Valve Closed
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    value_template: '{{ value_json.air_hclosed }}'
    qos: 0
    