####################################################
# BINARY SENSORS - LOCKS and DOORS                 #
####################################################

# BELLS
  - platform: mqtt
    name: House FD Bell
    state_topic: "Home/Door/Front/Sensors/Stts"
    availability:
      - topic: "Home/Door/Front/LWT"
    value_template: '{{ value_json.bell }}'
    payload_on: "ON"
    payload_off: "OFF"
    qos: 0
    
  - platform: mqtt
    name: House SD Bell
    state_topic: "Home/Door/Side/Sensors/Stts"
    availability:
      - topic: "Home/Door/Side/LWT"
    value_template: '{{ value_json.bell }}'
    payload_on: "ON"
    payload_off: "OFF"
    qos: 0
    
  - platform: mqtt
    name: House BD Bell
    state_topic: "Home/Door/Back/Sensors/Stts"
    availability:
      - topic: "Home/Door/Back/LWT"
    value_template: '{{ value_json.bell }}'
    payload_on: "ON"
    payload_off: "OFF"
    qos: 0
    
  - platform: mqtt
    name: Garage FD Bell
    state_topic: "Garage/Door/Front/Sensors/Stts"
    availability:
      - topic: "Garage/Door/Front/LWT"
    value_template: '{{ value_json.bell }}'
    payload_on: "ON"
    payload_off: "OFF"
    qos: 0

# DOOR SENSORS
  - platform: mqtt
    name: House FD Opened
    state_topic: "Home/Door/Front/Sensors/Stts"
    availability:
      - topic: "Home/Door/Front/LWT"
    value_template: '{{ value_json.opened }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    json_attributes_topic: "Home/Door/Front/Json"

  - platform: mqtt
    name: House SD Opened
    state_topic: "Home/Door/Side/Sensors/Stts"
    availability:
      - topic: "Home/Door/Side/LWT"
    value_template: '{{ value_json.opened }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    json_attributes_topic: "Home/Door/Side/Json"
    
  - platform: mqtt
    name: House BD Opened
    state_topic: "Home/Door/Back/Sensors/Stts"
    availability:
      - topic: "Home/Door/Back/LWT"
    value_template: '{{ value_json.opened }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    json_attributes_topic: "Home/Door/Back/Json"
 
  - platform: mqtt
    name: Garage FD Opened
    state_topic: "Garage/Door/Front/Sensors/Stts"
    availability:
      - topic: "Garage/Door/Front/LWT"
    value_template: '{{ value_json.opened }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    json_attributes_topic: "Garage/Door/Front/Json"

  - platform: mqtt
    name: Garage BD Opened
    state_topic: "Garage/Slave/Sensors/Stts"
    availability:
      - topic: "Garage/Slave/LWT"
    value_template: '{{ value_json.rear_doors }}'
    device_class: door
    qos: 0
    
  - platform: mqtt
    name: Garage CD Opened
    state_topic: "Garage/Door/Car/Sensors/Stts"
    value_template: '{{ not value_json.state }}'
    payload_on: "opened"
    payload_off: "closed"
    availability:
      - topic: "Garage/Door/Car/LWT"
    device_class: door
    qos: 0
    json_attributes_topic: "Garage/Door/Car/Json"

  - platform: mqtt
    name: Shed FD Opened
    state_topic: "Shed/Door/Sensors/Stts"
    availability:
      - topic: "Shed/Control/LWT"
    value_template: '{{ value_json.main_door }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    
  - platform: mqtt
    name: Shed LD Opened
    state_topic: "Shed/Door/Sensors/Stts"
    availability:
      - topic: "Shed/Control/LWT"
    value_template: '{{ value_json.left_doors }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    
  - platform: mqtt
    name: Shed RD Opened
    state_topic: "Shed/Door/Sensors/Stts"
    availability:
      - topic: "Shed/Control/LWT"
    value_template: '{{ value_json.right_doors }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    
  - platform: mqtt
    name: Pool FD Opened
    state_topic: "Pool/Control/Sensors/Stts"
    availability:
      - topic: "Pool/Control/LWT"
    value_template: '{{ value_json.closed }}'
    payload_on: "opened"
    payload_off: "closed"
    device_class: door
    qos: 0
    