####################################################
# BINARY SENSORS - POND                            #
####################################################
#See other sensors templates in Templates/t_pond.yaml

  - platform: mqtt
    name: Pond Level High
    device_class: moisture
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.hilvl }}'
    qos: 0
    json_attributes_topic: "Home/Control/Sensors/Stts"
    json_attributes_template: '{{ {"High Level" : value_json.hilvl, "High Raw" : value_json.hilvl} | tojson }}'
    
  - platform: mqtt
    name: Pond Level Low
    device_class: moisture
    state_topic: "Home/Control/Sensors/Stts"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.lolvl }}'
    qos: 0
    json_attributes_topic: "Home/Control/Sensors/Stts"
    json_attributes_template: '{{ {"Low Level" : value_json.lolvl, "Low Raw" : value_json.lolvl} | tojson }}'