####################################################
# BINARY SENSORS - POOL                            #
####################################################
#See other sensors templates in Templates/t_pool.yaml

  - platform: mqtt
    name: Pool Level High
    device_class: moisture
    state_topic: "Pool/Control/Sensors/Stts"
    availability:
      - topic: "Pool/Control/LWT"
    #value_template: {{ value_json.hilvl }}
    value_template: 'ON'
    qos: 0
    json_attributes_topic: "Pool/Control/Sensors/Stts"
    json_attributes_template: '{{ {"High Level" : value_json.hilvl, "High Raw" : value_json.hiraw} | tojson }}'
    
  - platform: mqtt
    name: Pool Level Low
    device_class: moisture
    state_topic: "Pool/Control/Sensors/Stts"
    availability:
      - topic: "Pool/Control/LWT"
    #value_template: {{ value_json.lolvl }}
    value_template: 'ON'
    qos: 0
    json_attributes_topic: "Pool/Control/Sensors/Stts"
    json_attributes_template: '{{ {"Low Level" : value_json.lolvl, "Low Raw" : value_json.loraw} | tojson }}'
          
  - platform: mqtt
    name: Pool Gate Closed - Deck
    device_class: door
    state_topic: "Home/Control/Sensors/Stts"
    # payload_off: "ON"
    # payload_on: "OFF"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.gate_deck }}'
    qos: 0
    
  - platform: mqtt
    name: Pool Gate Closed - Main
    device_class: door
    state_topic: "Home/Control/Sensors/Stts"
    # payload_off: "ON"
    # payload_on: "OFF"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.gate_main }}'
    qos: 0
    
  - platform: mqtt
    name: Pool Gate Closed - Pond
    device_class: door
    state_topic: "Home/Control/Sensors/Stts"
    # payload_off: "ON"
    # payload_on: "OFF"
    availability:
      - topic: "Home/Control/LWT"
    value_template: '{{ value_json.gate_pond }}'
    qos: 0
    