    type: vertical-stack
    #title: Main
    cards:
      - type: 'custom:config-template-card'
        variables:
          # - entity: sensor.ted5000_mtu1_energy_daily
          #   name: Main Energy Daily
          # - entity: sensor.ted5000_mtu0_energy_daily
          #   name: House Energy Daily
          # - entity: sensor.ted5000_mtu2_energy_daily
          #   name: Garage Energy Daily
          # - entity: sensor.ted5000_mtu3_energy_daily
          #   name: Pool Energy Daily
          - entity: sensor.ted5000_mtu1_energy_daily
          - entity: sensor.ted5000_mtu0_energy_daily_raw
            name: House Daily Energy
          - entity: sensor.ted5000_mtu2_energy_daily
          - entity: sensor.ted5000_mtu3_energy_daily
          - entity: sensor.chest_freezer_energy_daily
          - entity: sensor.cold_storage_floor_heater_energy_daily
          - entity: sensor.dishwasher_energy_daily
          - entity: sensor.drying_machine_energy_daily
          - entity: sensor.garage_hvac_energy_daily
          - entity: sensor.garage_front_heater_energy_daily
          - entity: sensor.garage_rear_heater_energy_daily
          - entity: sensor.kitchen_refrigerator_energy_daily
          - entity: sensor.living_room_hvac_energy_daily
          - entity: sensor.storage_room_floor_heater_energy_daily
          - entity: sensor.tankless_water_heater_energy_daily
          - entity: sensor.washing_machine_energy_daily
          - entity: sensor.office_heater_energy_daily
          - entity: sensor.recroom_hvac_energy_daily
          - entity: sensor.recroom_heater_energy_daily
          - entity: sensor.bar_heater_energy_daily
          - entity: sensor.entrance_heater_energy_daily
          - entity: sensor.kitchen_heater_energy_daily
          - entity: sensor.living_room_heater_energy_daily
          - entity: sensor.massage_room_heater_energy_daily
          - entity: sensor.master_bedroom_heater_energy_daily
          - entity: sensor.training_room_heater_energy_daily
          - entity: sensor.pond_waterfall_pump_energy_daily
          - entity: sensor.pool_pump_energy_daily
          - entity: sensor.pool_heater_energy_daily
          - entity: sensor.well_energy_daily
          - entity: sensor.ups_load_energy_daily
        entities: 
          # Note: this list of entities may seem redundant, but is necessary to inform
          # config-template-card which entities to watch for updates.
            # Replaced with a sensor that changes value every second
          - sensor.times
        element:
          type: 'custom:bar-card'
          entities: ${vars.filter(v => states[v.entity].state >= 0).sort((v1,v2) => states[v2.entity].state-states[v1.entity].state)}
          direction: right
          entity_row: true
          min: 0
          #max: ${ Math.max(...vars.map(v => states[v.entity].state))}
          #max: ${ Math.floor(Math.max(...vars.map(v => states[v.entity].state))*100)/100}
          max: ${ states['sensor.ted5000_mtu1_energy_daily'].state }
          width: 50%
          height: 20px
          stack: vertical
          decimal: 1
          icon: 'mdi:flash'
          positions:
            icon: off
            indicator: off
            name: outside
            value: inside
          style: |-
            #states > * {
              margin: 1px;
            }
            bar-card-card {
              border-radius: 2.5px;
            }
            bar-card-name,
            bar-card-value {
              font-size: 0.8rem;
              color: #ffffffaa;
            }

            
      # bar-card-currentbar {
      #   background: linear-gradient(to right, green 5%, yellow 15%, orange 35%, red 85%);
      #   clip-path: polygon(0 0, var(--bar-percent) 0, var(--bar-percent) 100%, 0 100%);
      # }
      # bar-card-backgroundbar {
      #   background: linear-gradient(to right, green 5%, yellow 15%, orange 35%, red 85%);
      # }
      # margin-top: -10px;