      type: custom:fold-entity-row
      head: sensor.uun_ordered
      entities:
        - entity: script.update_entities
          secondary_info: last-triggered
          action_name: Re-Count
        - type: custom:fold-entity-row
          head: sensor.entities
          entities:
            - type: custom:hui-element
              card_type: markdown
              style: |
                ha-card {
                  box-shadow: none;
                  margin: 0px -16px -16px -26px;
                  color: var(--primary-color);
                }
              content: |
                {% set list = ['icon_color', 'icon', 'friendly_name', '--------------'] %}
                
                {% for attr in states.sensor.entities.attributes %}
                  {% if attr not in list -%}
                    {{attr}}: {{states.sensor.entities.attributes[attr]}}
                  {%- endif -%}
                {%- endfor -%}

        - type: custom:decluttering-card
          template: entity_issues
          variables: 
            - name: 'Unknown entities'
            - id: 'unknown'

        # - type: custom:decluttering-card
        #   template: entity_issues
        #   variables: 
        #     - name: 'Unknown sensors'
        #     - id: 'sensors'

        - type: custom:decluttering-card
          template: entity_issues
          variables: 
            - name: 'Unavailable'
            - id: 'unavailable'

        - type: custom:decluttering-card
          template: entity_issues
          variables: 
            - name: 'None'
            - id: 'none'

        - type: custom:decluttering-card
          template: entity_issues
          variables: 
            - name: 'Automations Off'
            - id: 'automations'

        - type: custom:decluttering-card
          template: entity_issues
          variables: 
            - name: 'Full list filtered'
            - id: 'all'

        - type: custom:decluttering-card
          template: entity_issues
          variables: 
            - name: 'Full list unfiltered'
            - id: 'unfiltered'

        - type: custom:decluttering-card
          template: entity_issues
          variables: 
            - name: 'Full list blacklisted'
            - id: 'blacklisted'
