    # - type: entities
    #   title: Pond pump
    #   show_header_toggle: false
    #   entities:
    #     - type: custom:fold-entity-row
    #       head: sensor.pondpump_status
    #       entities:
    #       - switch.pond_pump
    #       - input_select.pondpump_mode
    
    - type: entities
      title: Pond Filling
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: binary_sensor.pondfiller_status
          entities:
          - type: "custom:secondaryinfo-entity-row"
            entity: switch.pond_filler_valve
            secondary_info: "Time last 24h: [[ sensor.pond_filler_timer.attributes.value ]]"
          - binary_sensor.pond_level_low
          - binary_sensor.pond_level_high
          #- automation.pond_filler_control
          - type: "custom:button-entity-row"
            buttons:
              - entity: input_boolean.pondfiller_start30m
                name: 30 min
                icon: "mdi:play"
              - entity: input_boolean.pondfiller_start1h
                name: 1 hour
                icon: "mdi:play"
              - entity: input_boolean.pondfiller_start2h
                name: 2 hours
                icon: "mdi:play"
              - entity: input_boolean.pondfiller_cancel
                name: Stop
                icon: "mdi:stop"
    
    - type: entities
      title: Pond Cabinet Status
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.pond_control_status
          entities:
            - input_boolean.pond_running
            - sensor.pond_area_temperature
            - sensor.pond_area_humidity
            - sensor.pond_control_box_temperature
            - sensor.pond_control_box_humidity
            - sensor.pond_control_12v_voltage
            - sensor.pond_control_5v_voltage
            - type: "custom:button-entity-row"
              buttons:
                - entity: input_boolean.pond_control_reset
                  name: RESET
                  icon: "mdi:power-cycle"