##########################################
# CUSTOMIZATIONS - ALL OTHERS            #
##########################################

# STANDARD COLORS
#=========================================
# Icon Online:  var(--state-icon-color) --> #007AFF
# Icon Offline: var(--state-icon-unavailable-color) --> #4F5F78
# Icon Active:  var(--state-icon-active-color) --> #FBCD41
# Red:          FF0000
# Yellow:       FFFF00
# Orange:       FFA500
# Lt Purple:    A500FF
# Dk Purple:    5C005C
# Lt Green:     00FF00
# Gold:         A3852A

  cover.garage_cd_opener:
    custom_ui_state_card: state-card-custom-ui
    confirm_controls_show_lock: true
    hide_control: false
    show_last_changed: true
        
  device_tracker.life360_jean:
    friendly_name: Jean
    
  device_tracker.life360_cindy:
    friendly_name: Cindy
    
  # device_tracker.ipad_de_cindy:
    # custom_ui_state_card: state-card-custom-ui
    # icon: mdi:tablet
    
  binary_sensor.ha_update_available:
    templates:
      icon_color: >
        if (entities['binary_sensor.ha_update_available'].attributes['major_update'] === 'true') return 'red';
        if (state === 'on') return 'orange';
        if (state === 'off') return 'green';
        return 'var(--state-icon-unavailable-color)';
  sensor.chicoutimi_update_available:
    templates:
      icon_color: >
        if (entities['sensor.chicoutimi_update_available'].attributes['major_update'] === 'true') return 'red';
        if (state === 'on') return 'orange';
        if (state === 'off') return 'green';
        return 'var(--state-icon-unavailable-color)';
  sensor.chicoutimi_entities:
    friendly_name: "Entities"
    templates:
      icon: >
        return 'mdi:script-text';
  sensor.chicoutimi_uun_entities:
    friendly_name: "Entities Issues"
    templates:
      icon: >
        if (state > 0) return 'mdi:thumb-down';
        return 'mdi:thumb-up';
      icon_color: >
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        if (state === 'unknown') return 'var(--state-icon-unavailable-color)';
        if (state > 0) return 'red';
        return 'green';
  sensor.chicoutimi_last_boot:
    templates:
      icon: >
        return 'mdi:clock';
  sensor.chicoutimi_mariadb:
    templates:
      icon: >
        return 'mdi:file';
        
  # binary_sensor.garage_attic_light:
    # templates:
      # icon: >
        # return 'mdi:lightbulb';
      # icon_color: >
        # if (state === 'on') return 'var(--state-icon-active-color)';
        # if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        # return 'var(--state-icon-color)';
        
  # binary_sensor.control_room_light:
    # templates:
      # icon: >
        # return 'mdi:lightbulb';
      # icon_color: >
        # if (state === 'on') return 'var(--state-icon-active-color)';
        # if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        # return 'var(--state-icon-color)';
        