##########################################
# CUSTOMIZATIONS - ALL OTHERS            #
##########################################

# STANDARD COLORS
#=========================================
# Icon Online:  var(--state-icon-color) --> #007AFF
# Icon Offline: var(--state-icon-unavailable-color) --> #4F5F78
# Icon Active:  var(--state-icon-active-color) --> #FBCD41
# Red:          FF0000
# Yellow:       FFFF00
# Orange:       FFA500
# Lt Purple:    A500FF
# Dk Purple:    5C005C
# Lt Green:     00FF00
# Gold:         A3852A

  cover.garage_cd_opener:
    custom_ui_state_card: state-card-custom-ui
    confirm_controls_show_lock: true
    hide_control: false
    show_last_changed: true
    
  # device_tracker.ipad_de_cindy:
    # custom_ui_state_card: state-card-custom-ui
    # icon: mdi:tablet

  binary_sensor.iss:
    icon: mdi:space-station
  
  device_tracker.iss:
    friendly_name: ISS Location
    entity_picture: "/local/images/ISS.png"
    
  device_tracker.life360_jean:
    friendly_name: Jean
    entity_picture: "/local/images/People/Jean2023.jpg"
    
  device_tracker.life360_cindy:
    friendly_name: Cindy
    entity_picture: "/local/images/People/Cindy2023.jpg"
    
  device_tracker.life360_cody:
    friendly_name: Cody
    entity_picture: "/local/images/People/Cody2023.jpg"