##########################################
# CUSTOMIZATIONS - INPUTS                #
#     NUMBERS                            #
#     SELECT                             #
#     BOOLEANS                           #
#     TEXT                               #
##########################################

  input_select.poolpump_mode:
    templates:
      icon: >
        if (state === 'Spring') return 'mdi:flower-tulip';
        if (state === 'Summer') return 'mdi:weather-sunny';
        if (state === 'Autumn') return 'mdi:leaf-maple';
        if (state === '24/7') return 'mdi:clock-start';
        if (state === 'Winter/Off') return 'mdi:power-off';
        return 'mdi:power-plug-off';
        
  input_select.poolheat_mode:
    templates:
      icon: >
        if (state === '24/7') return 'mdi:clock-start';
        if (state === 'Auto') return 'mdi:progress-clock';
        if (state === 'Winter/Off') return 'mdi:power-off';
        return 'mdi:power-plug-off';
        
  input_select.pondpump_mode:
    templates:
      icon: >
        if (state === 'Spring') return 'mdi:flower-tulip';
        if (state === 'Summer') return 'mdi:weather-sunny';
        if (state === 'Autumn') return 'mdi:leaf-maple';
        if (state === '24/7') return 'mdi:clock-start';
        if (state === 'Winter/Off') return 'mdi:power-off';
        return 'mdi:power-plug-off';

  input_text.doorlock_passcode:
    custom_ui_state_card: state-card-custom-ui
    icon: mdi:shield-lock
    templates:
      icon_color: >
        if (entities['input_boolean.running_hass'].state === 'off') return 'var(--state-icon-color)';
        if (entities['binary_sensor.lock_passcode_ok'].state === 'on') return 'var(--label-badge-green)';
        return 'var(--state-icon-color)';
  
  input_text.doorlock_passcode_list:
    hidden: true

  input_boolean.enable_flash:
    templates:
      icon: >
        if (state === 'on') return 'mdi:alarm-light';
        return 'mdi:alarm-light-off';