####################################################
# INPUT SELECT                                     #
####################################################
    
  poweroutlet_mode:
    name: Power Outlet Mode
    icon: mdi:calendar-clock
    options:
      - Force Off
      - Fountain
      - Halloween Decorations
      - Christmas Decorations
      - 24/7

  lamppost_mode:
    name: Lamp Post Mode
    icon: mdi:calendar-clock
    options:
      - Force Off
      - Sunset to 23h
      - Sunset to Sunrise
      - 24/7
      
  frontdoorlight_mode:
    name: Front Door Light Mode
    icon: mdi:calendar-clock
    options:
      - Force Off
      - Sunset to 23h
      - Sunset to Sunrise
      - 24/7
      - Switch Mode
    
  garagefrontlight_mode:
    name: Garage Front Light Mode
    icon: mdi:calendar-clock
    options:
      - Force Off
      - Sunset to 23h
      - Sunset to Sunrise
      - 24/7
  
  garagefrontpower_mode:
    name: Garage Front Power Mode
    icon: mdi:calendar-clock
    options:
      - Force Off
      - Christmas Decorations
      - 24/7
      
  nixie_date:
    name: Nixie Date Format
    icon: mdi:calendar-check
    options:
      - MM.DD.YY
      - YY.MM.DD
      - DD.MM.YY

  frontyardirrigation_mode:
    name: Frontyard Irrigation Mode
    icon: mdi:calendar-clock
    options:
      - Winter/Off
      - Auto
      - 24/7
      
  gardenirrigation_mode:
    name: Garden Irrigation Mode
    icon: mdi:calendar-clock
    options:
      - Winter/Off
      - Auto
      - 24/7
      
  gardenirrigationaux_mode:
    name: Garden Irrigation Aux Mode
    icon: mdi:calendar-clock
    options:
      - Winter/Off
      - Auto

  workplace_jean:
    name: Jean's workplace
    icon: mdi:account-tie
    options:
      - Office
      - Telework
      - Trip
      - Away
      - Vacation
      
  cody_presence:
    name: Cody's Home Presence
    icon: mdi:home-account
    options:
      - Auto
      - Force Home
      - Force Away
      - Garderie
      - École
      - Avec Maman
      - Avec Papa