##########################################
# GLOBAL CUSTOMIZATIONS - BINARY SENSORS #
##########################################

#   binary_sensor.*:
#     #state_color: true
#     hide_attributes:
#       - templates
#       - icon_color
    # templates:
    #   icon_color: >
    #     if (state === 'on') return 'var(--state-icon-active-color)';
    #     if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
    #     return 'var(--state-icon-color)';
        
  binary_sensor.*_router:
    templates:
      icon: >
        if (state === 'on') return 'mdi:access-point-network'; 
        return 'mdi:access-point-network-off';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'var(--state-icon-color)';
        
        
  binary_sensor.garage*heater_error:
    templates:
      icon_color: >
        if (state === 'on') return 'green';
        if (state === 'off') return 'red';
        return 'var(--state-icon-unavailable-color)';
        
  binary_sensor.garage_*_safety_active:
    templates:
      icon: >
        if (state === 'on') return 'mdi:radiator'; 
        return 'mdi:radiator-disabled';
      icon_color: >
        if (state === 'on') return 'red';
        if (state === 'off') return 'var(--state-icon-color)';
        return 'var(--state-icon-unavailable-color)';
        
  binary_sensor.pool_gate_closed_*:
    templates:
      icon: >
        if (state === 'on') return 'mdi:gate';
        return 'mdi:gate-arrow-right';
      icon_color: >
        if (state === 'off') return 'var(--state-icon-color)';
        if (state === 'on') return 'red';
        return 'var(--state-icon-unavailable-color)';
        
  # binary_sensor.*_level_*:
    # templates:
      # icon: >
        # if (state === 'on') return 'mdi:checkbox-marked-circle';
        # return 'mdi:checkbox-blank-circle-outline';
      # icon_color: >
        # if (state === 'on') return 'var(--state-icon-active-color)';
        # if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        # return 'var(--state-icon-color)';
        
#   binary_sensor.*_pc:
#     templates:
#       icon_color: >
        # if (state === 'on') return 'var(--state-icon-active-color)';
        # if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        # return 'var(--state-icon-color)';