##########################################
# GLOBAL CUSTOMIZATIONS - LIGHTS         #
##########################################

  switch.*_light:
    templates:
      icon: >
        return 'mdi:lightbulb';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'var(--state-icon-color)';
        
  binary_sensor.*_light:
    templates:
      icon: >
        return 'mdi:lightbulb';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'var(--state-icon-color)';
        
  light.*_light:
    templates:
      icon: >
        return 'mdi:lightbulb';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'var(--state-icon-color)';
        
  light.*_fan:
    templates:
      icon: >
        return 'mdi:fan';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'var(--state-icon-color)';