####################################################
# SENSORS - ANNIVERSARIES                          #
####################################################

  - platform: date_countdown
    name: "Cody Counter"
    date: "11-01-2037 20:22"
