####################################################
# SENSORS - HA                                     #
####################################################

  #https://www.home-assistant.io/integrations/glances/
  
  #Home Assistant uptime
#   - platform: uptime
#     name: Uptime
#     #unit_of_measurement: hours
    
#https://wiki.archlinux.org/index.php/APC_UPS
#Do a "apcaccess status" without quotes and use what's available there...
  # - platform: apcupsd
  #   resources:
  #     - apc
  #     - date
  #     - hostname
  #     - version
  #     - upsname
  #     - cable
  #     - starttime
  #     - model
  #     - status
  #     - linev
  #     - loadpct
  #     - bcharge
  #     - timeleft
  #     - mbattchg
  #     - mintimel
  #     - maxtime
  #     - lotrans
  #     - hitrans
  #     - battv
  #     - lastxfer
  #     - numxfers
  #     - tonbatt
  #     - cumonbatt
  #     - xoffbatt
  #     - battdate
  #     - nominv
  #     - nombattv
  #     - nompower
    
  # - platform: filesize
  #   file_paths:
  #     - /config/home-assistant_v2.db

#https: //www.home-assistant.io/components/sensor.sql/
  # - platform: sql
  #   db_url: !secret db_mysql
  #   scan_interval: 60
  #   queries:
  #     - name: MariaDB Size
  #       #query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "size_mb" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema'
  #       query: "SELECT table_schema AS 'database', ROUND(SUM( data_length + index_length ) / 1024 / 1024, 1) AS 'size_mb' FROM information_schema.TABLES WHERE table_schema='homeassistant'"
  #       column: 'size_mb'
  #       unit_of_measurement: MB
    
  #Linux terminal command for network card name: ifconfig
  # - platform: systemmonitor
    # resources:
    # # - type: processor_temperature
    # - type: processor_use
    # - type: disk_use_percent
      # arg: /
    # - type: disk_use
      # arg: /
    # - type: disk_free
      # arg: /
    # - type: memory_use_percent
    # - type: memory_use
    # - type: memory_free
    # # - type: swap_use_percent
    # # - type: swap_use
    # # - type: swap_free
    # - type: last_boot
    # - type: load_1m
    # - type: load_5m
    # - type: load_15m
    # #ethernet card
    # - type: packets_in
      # arg: lo
    # - type: packets_out
      # arg: lo
    # - type: throughput_network_in
      # arg: lo
    # - type: throughput_network_out
      # arg: lo
    # - type: network_in
      # arg: lo
    # - type: network_out
      # arg: lo
    #IoT card
    # - type: packets_in
      # arg: enp5s0
    # - type: packets_out
      # arg: enp5s0
    # - type: throughput_network_in
      # arg: enp5s0
    # - type: throughput_network_out
      # arg: enp5s0
    # - type: network_in
      # arg: enp5s0
    # - type: network_out
      # arg: enp5s0

  - platform: file
    name: SpeedTest - Download
    file_path: /config/datalog/speed_test/speedtest.csv
    value_template: >
      {{ (value.split('","')[7]|int(0)/125000) }}
    unit_of_measurement: "Mbit/s"
    
  - platform: file
    name: SpeedTest - Upload
    file_path: /config/datalog/speed_test/speedtest.csv
    value_template: >
      {{ (value.split('","')[8]|int(0)/125000) }}
    unit_of_measurement: "Mbit/s"
    
  - platform: file
    name: SpeedTest - Ping
    file_path: /config/datalog/speed_test/speedtest.csv
    value_template: >
      {{ value.split('","')[4]|float(0) }}
    unit_of_measurement: "ms"
    
  - platform: file
    name: SpeedTest - Latency Download
    file_path: /config/datalog/speed_test/speedtest.csv
    value_template: >
      {{ value.split('","')[15]|float(0) }}
    unit_of_measurement: "ms"
    
  - platform: file
    name: SpeedTest - Latency Upload
    file_path: /config/datalog/speed_test/speedtest.csv
    value_template: >
      {{ value.split('","')[19]|float(0) }}
    unit_of_measurement: "ms"
    
