####################################################
# INPUTS BUTTONS                                   #
####################################################

  ring_jean:
    name: Ring Jean
    icon: mdi:card-account-phone