clean_up:
  description: A simple service to keep the number of backups manageable,
  fields:
    number_of_snapshots_to_keep:
      description: Number of snapshots you wish to keep.
      example: 3
