####################################################
# SWITCHES                                         #
####################################################
    
  - platform: mqtt
    name: Postal Status
    icon: mdi:mailbox
    state_topic: "Home/Postal/Stts"
    command_topic: "Home/Postal/Cmd"
    value_template: '{{ value_json.state }}'
    payload_on: '{"state":"ON"}'
    payload_off: '{"state":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    availability:
      - topic: "Home/Transmitter/LWT"
    qos: 0
    json_attributes_topic: "Home/Transmitter/Json"
    
  - platform: mqtt
    name: Postal Status Activate Delay
    icon: mdi:lock-clock
    state_topic: "Home/Postal/Stts"
    command_topic: "Home/Postal/Cmd"
    value_template: '{{ value_json.delay }}'
    payload_on: '{"delay":"ON"}'
    payload_off: '{"delay":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    availability:
      - topic: "Home/Transmitter/LWT"
    qos: 0
    
  #Homed status of the hands
  - platform: mqtt
    name: Stepper Wall Clock Homed
    icon: mdi:clock-start
    state_topic: "Home/WallClock/Stts"
    command_topic: "Home/WallClock/Cmd"
    value_template: '{{ value_json.homed }}'
    payload_on: '{"homed":"ON"}'
    payload_off: '{"homed":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    availability:
      - topic: "Home/WallClock/LWT"
    qos: 0
    
        