####################################################
# TEMPLATES                                        #
####################################################

  - sensor:

    - name: Postal Status
      #unique_id: postal_status
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: none
      icon: mdi:mailbox
      availability: >
        {{ not is_state('switch.postal_status', 'unavailable') }}
      state: >
        {% if is_state('switch.postal_status', 'on') %}
          New Mail
        {% else %}
          No Mail
        {% endif %}
      attributes:
        state: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        bat_voltage: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'voltage') }}{% else %}{{ 'unknown' }}{% endif %}"
        bat_percent: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
        id: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'id') }}{% else %}{{ 'unknown' }}{% endif %}"
        lora_rssi: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        source: "{% if states('sensor.postal_status_json') != 'unavailable' %}{{ state_attr('sensor.postal_status_json', 'source') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('switch.postal_status') != 'unavailable' %}{{ state_attr('switch.postal_status', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"

    - unique_id: last_postal_arrival
      #name: Last Postal Arrival Time
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: timestamp  //Makes display on minutes since...
      icon: mdi:clock-in
      availability: >
        {{ not is_state('switch.postal_status', 'unavailable') }}
      state: >
        {{ states('input_datetime.last_postal_arrival') }}
      attributes:
        friendly_name: Last Postal Arrival Time

    - unique_id: last_postal_removal
      #name: Last Postal Removal Time
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: timestamp  //Makes display on minutes since...
      icon: mdi:clock-out
      state: >
        {{ states('input_datetime.last_postal_removal') }}
        {{ states('input_datetime.last_postal_removal') }}
      attributes:
        friendly_name: Last Postal Removal Time

    - name: Nixie Clock
      #unique_id: nixie_clock
      #unit_of_measurement: ''
      #state_class: measurement
      #device_class: none
      icon: mdi:clock-out
      state: >
        {{ states('sensor.nixie_clock_status') }}
      availability: >
        {{ not is_state('sensor.nixie_clock_status', 'unavailable') }}
      attributes:
        state: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        case_temp: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'temp_in') }}{% else %}{{ 'unknown' }}{% endif %}"
        vcc_3v3: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('sensor.nixie_clock_status') != 'unavailable' %}{{ state_attr('sensor.nixie_clock_status', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
      picture: >
        {% if is_state('sensor.nixie_clock_status','On') %}
          /local/images/CustomMDI/nixietubes/dark_FBCD41.png
        {% elif is_state('sensor.nixie_clock_status','Off') %}
          /local/images/CustomMDI/nixietubes/dark_007AFF.png
        {% else %}
          /local/images/CustomMDI/nixietubes/dark_48485E.png
        {% endif %}

  - binary_sensor:
  
    - unique_id: power_peakperiod
      #name: Hydro-Québec Peak Period
      device_class: cold
      #icon: mdi:none
      state: >
        {% set month = state_attr('sensor.dates', 'month')|int %}
        {% set hourmin = state_attr('sensor.times', 'hourmin')|int %}
        {% set T = states('sensor.outdoor_temperature')|float %}
        
        {% if month in (12,1,2,3) and T < -20.0 %}
          {% if hourmin >= 600 and hourmin <= 900 %}
            {{ true }}
          {% elif hourmin >= 1600 and hourmin <= 2000 %}
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
        {% else %}
          {{ false }}
        {% endif %}
      attributes:
        friendly_name: Hydro-Québec Peak Period

    - name: Reset Sensors Graphs
      #unique_id: reset_sensors_graphs
      #device_class: none
      #icon: mdi:none
      state: >
        {% if state_attr('sensor.times', 'sec_midnight')|int < 5 %}
          {{ true }}
        {% elif is_state('input_boolean.force_reset_graphs', 'on') %}
          {{ true }}
        {% else %}
          {{ false }}
        {% endif %}

    - name: HA Update Available
      #unique_id: ha_update_available
      #device_class: none
      #icon: mdi:none
      icon: >
        {% if states('sensor.ha_installed_version') == 'unavailable' or states('sensor.ha_installed_version') == 'unknown' or states('sensor.ha_latest_version') == 'unavailable' or states('sensor.ha_latest_version') == 'unknown' %}
          mdi:cloud-question
        {% elif states('sensor.ha_installed_version') != states('sensor.ha_latest_version') %}
          mdi:cloud-download
        {% elif states('sensor.ha_installed_version') == states('sensor.ha_latest_version') %}
          mdi:cloud-check
        {% else %}
          mdi:cloud-question
        {% endif %}
      availability: >-
        {{ states('sensor.ha_installed_version') != 'unavailable' and 
                states('sensor.ha_installed_version') != 'unknown' and 
                states('sensor.ha_latest_version') != 'unavailable' and 
                states('sensor.ha_latest_version') != 'unknown' }}
      state: >
        {% if states('sensor.ha_installed_version') != states('sensor.ha_latest_version') %}
          {{ true }}
        {% else %}
          {{ false }}
        {% endif %}
      attributes:
        current: "{{ states('sensor.ha_installed_version') }}"
        latest: "{{ states('sensor.ha_latest_version') }}"
        major_update: "{{ states('sensor.ha_latest_version')[5:]|int - states('sensor.ha_installed_version')[5:]|int > 0 }}"
        breaking_changes: "{{ states('sensor.potential_breaking_changes') }}"
          