####################################################
# TEMPLATES - COLLECTS                             #
####################################################

  - sensor:

    #Trash collect day
    - unique_id: collect_trash_week
      #name: Trash Collect
      icon: mdi:trash-can
      state: >
        {% set enabled = not is_state('input_select.collect_trash','Disabled') %}
        {% set collectday = state_attr('input_select.collect_trash','options').index(states('input_select.collect_trash'))|int % 5 %}
        {% set today = state_attr('sensor.dates', 'weekdaynumber')|int +1 %}
        {% set collectweek = state_attr('input_select.collect_trash','options').index(states('input_select.collect_trash'))|int -1 %}
        {% set week = state_attr('sensor.dates', 'weekofyear')|int %2 %}
        {% set time = '14:00' %}
        {% set allweeks = state_attr('sensor.collect_trash_week','summer') == 'on' %}
        {% set selected = states('input_select.collect_trash')|replace('Odd/','')|replace('Even/','')|replace('All/','') %}
        {% set now = state_attr('sensor.times', 'short') %}
        
        {% if today >= 7 %}
          {% set today = 0 %}
          {% set week = (week+1)%2 %}
        {% endif %}
        
        {% if collectweek >= 10 %}{% set collectweek = 2 %}{% set allweeks = true %}
        {% elif collectweek >= 5 %}{% set collectweek = 0 %}
        {% else %}{% set collectweek = 1 %}
        {% endif %}
        
        {% if ((today > collectday) or ((today == collectday) and (now >= time))) %}{% set passed = true %}
        {% elif ((today < collectday) or ((today == collectday) and (now < time))) %}{% set passed = false %}
        {% endif %}
        
        {% if collectweek == week or allweeks %}{% set thisweek = true %}
        {% else %}{% set thisweek = false %}
        {% endif %}
        
        {% if not enabled %}
          Disabled
        {% elif thisweek and not passed %}
          {% if today+1 == collectday %}
            Tomorrow
          {% elif today == collectday %}
            Today
          {% elif today < collectday %}
            Next {{ selected }}
          {% endif %}
        {% elif (thisweek and passed and allweeks) or (not thisweek and passed) %}
          Next {{ selected }}
        {% elif thisweek and passed and not allweeks %}
          In 2 {{ selected }}s
        {% elif not thisweek and not passed %}
          {{ selected }} Next Week
        {% else %}
          Error
        {% endif %}
      attributes:
        friendly_name: Trash Collect
        displayName: TRASH
        summer: >
          {% set year_start = state_attr('input_datetime.collect_trash_start', 'year')|int %}
          {% set month_start = state_attr('input_datetime.collect_trash_start', 'month')|int %}
          {% set day_start = state_attr('input_datetime.collect_trash_start', 'day')|int %}
          {% set year_end = state_attr('input_datetime.collect_trash_end', 'year')|int %}
          {% set month_end = state_attr('input_datetime.collect_trash_end', 'month')|int %}
          {% set day_end = state_attr('input_datetime.collect_trash_end', 'day')|int %}
          {% set year = state_attr('sensor.dates', 'year')|int %}
          {% set month = state_attr('sensor.dates', 'month')|int %}
          {% set day = state_attr('sensor.dates', 'day')|int %}
          {% set enable = year_start >= year and year_end >= year %}
          
          {% set start = month > month_start or (month == month_start and day >= day_start) %}
          {% set end = month < month_end or (month == month_end and day <= day_end) %}
          
          {% if not enable %}
            disabled
          {% elif start and end %}
            on
          {% else %}
            off
          {% endif %}
        today: >
          {% set time = '14:00' %}
          {% set now = state_attr('sensor.times', 'short') %}
          {% set today = is_state('sensor.collect_trash_week', 'Today') and now < time %}
          
          {% if today %}
            on
          {% else %}
            off
          {% endif %}
        tomorrow: >
          {% set tomorrow = is_state('sensor.collect_trash_week', 'Tomorrow') %}
          
          {% if tomorrow %}
            on
          {% else %}
            off
          {% endif %}
        thisweek: >
          {% if ' Next ' in states('sensor.collect_trash_week') %}
            off
          {% elif 'Next ' in states('sensor.collect_trash_week') or is_state('sensor.collect_trash_week', 'Today') or is_state('sensor.collect_trash_week', 'Tomorrow') %}
            on
          {% else %}
            off
          {% endif %}
        
    - unique_id: collect_trash_summer_mode
      #name: Trash Summer Mode
      icon: >
        {% if state_attr('sensor.collect_trash_week', 'summer') == 'on'  %}
          mdi:tree
        {% elif state_attr('sensor.collect_trash_week', 'summer') == 'off'  %}
          mdi:snowflake
        {% else %}
          mdi:trash-can
        {% endif %}
      state: >
        {% if state_attr('sensor.collect_trash_week', 'summer') == 'on' %}
          Weekly
        {% elif state_attr('sensor.collect_trash_week', 'summer') == 'off' %}
          Fortnightly
        {% else %}
          Disabled
        {% endif %}
      attributes:
        friendly_name: Trash Summer Mode

  #Recycle collect day
    - unique_id: collect_recycle_week
      #name: Recycle Collect
      icon: mdi:recycle
      state: >
        {% set enabled = not is_state('input_select.collect_recycle','Disabled') %}
        {% set collectday = state_attr('input_select.collect_recycle','options').index(states('input_select.collect_recycle'))|int % 5 %}
        {% set today = state_attr('sensor.dates', 'weekdaynumber')|int +1 %}
        {% set collectweek = state_attr('input_select.collect_recycle','options').index(states('input_select.collect_recycle'))|int -1 %}
        {% set week = state_attr('sensor.dates', 'weekofyear')|int %2 %}
        {% set time = '14:00' %}
        {% set allweeks = state_attr('sensor.collect_recycle_week','summer') == 'on' %}
        {% set selected = states('input_select.collect_recycle')|replace('Odd/','')|replace('Even/','')|replace('All/','') %}
        {% set now = state_attr('sensor.times', 'short') %}
        
        {% if today >= 7 %}
          {% set today = 0 %}
          {% set week = (week+1)%2 %}
        {% endif %}
        
        {% if collectweek >= 10 %}{% set collectweek = 2 %}{% set allweeks = true %}
        {% elif collectweek >= 5 %}{% set collectweek = 0 %}
        {% else %}{% set collectweek = 1 %}
        {% endif %}
        
        {% if ((today > collectday) or ((today == collectday) and (now >= time))) %}{% set passed = true %}
        {% elif ((today < collectday) or ((today == collectday) and (now < time))) %}{% set passed = false %}
        {% endif %}
        
        {% if collectweek == week or allweeks %}{% set thisweek = true %}
        {% else %}{% set thisweek = false %}
        {% endif %}
        
        {% if not enabled %}
          Disabled
        {% elif thisweek and not passed %}
          {% if today+1 == collectday %}
            Tomorrow
          {% elif today == collectday %}
            Today
          {% elif today < collectday %}
            Next {{ selected }}
          {% endif %}
        {% elif (thisweek and passed and allweeks) or (not thisweek and passed) %}
          Next {{ selected }}
        {% elif thisweek and passed and not allweeks %}
          In 2 {{ selected }}s
        {% elif not thisweek and not passed %}
          {{ selected }} Next Week
        {% else %}
          Error
        {% endif %}
      attributes:
        friendly_name: Recycle Collect
        displayName: RECYCLE
        summer: >
          {% set year_start = state_attr('input_datetime.collect_recycle_start', 'year')|int %}
          {% set month_start = state_attr('input_datetime.collect_recycle_start', 'month')|int %}
          {% set day_start = state_attr('input_datetime.collect_recycle_start', 'day')|int %}
          {% set year_end = state_attr('input_datetime.collect_recycle_end', 'year')|int %}
          {% set month_end = state_attr('input_datetime.collect_recycle_end', 'month')|int %}
          {% set day_end = state_attr('input_datetime.collect_recycle_end', 'day')|int %}
          {% set year = state_attr('sensor.dates', 'year')|int %}
          {% set month = state_attr('sensor.dates', 'month')|int %}
          {% set day = state_attr('sensor.dates', 'day')|int %}
          {% set enable = year_start >= year and year_end >= year %}
          
          {% set start = month > month_start or (month == month_start and day >= day_start) %}
          {% set end = month < month_end or (month == month_end and day <= day_end) %}
          
          {% if not enable %}
            disabled
          {% elif start and end %}
            on
          {% else %}
            off
          {% endif %}
        today: >
          {% set time = '14:00' %}
          {% set now = state_attr('sensor.times', 'short') %}
          {% set today = is_state('sensor.collect_recycle_week', 'Today') and now < time %}
          
          {% if today %}
            on
          {% else %}
            off
          {% endif %}
        tomorrow: >
          {% set tomorrow = is_state('sensor.collect_recycle_week', 'Tomorrow') %}
          
          {% if tomorrow %}
            on
          {% else %}
            off
          {% endif %}
        thisweek: >
          {% if ' Next ' in states('sensor.collect_recycle_week') %}
            off
          {% elif 'Next ' in states('sensor.collect_recycle_week') or is_state('sensor.collect_recycle_week', 'Today') or is_state('sensor.collect_recycle_week', 'Tomorrow') %}
            on
          {% else %}
            off
          {% endif %}
        
    - unique_id: collect_recycle_summer_mode
      #name: Recycle Summer Mode
      icon: >
        {% if state_attr('sensor.collect_recycle_week', 'summer') == 'on'  %}
          mdi:tree
        {% elif state_attr('sensor.collect_recycle_week', 'summer') == 'off'  %}
          mdi:snowflake
        {% else %}
          mdi:recycle
        {% endif %}
      state: >
        {% if state_attr('sensor.collect_recycle_week', 'summer') == 'on' %}
          Weekly
        {% elif state_attr('sensor.collect_recycle_week', 'summer') == 'off' %}
          Fortnightly
        {% else %}
          Disabled
        {% endif %}
      attributes:
        friendly_name: Recycle Summer Mode

  #Compost collect day
    - unique_id: collect_compost_week
      #name: Compost Collect
      icon: mdi:sprout-outline
      state: >
        {% set enabled = not is_state('input_select.collect_compost','Disabled') %}
        {% set collectday = state_attr('input_select.collect_compost','options').index(states('input_select.collect_compost'))|int % 5 %}
        {% set today = state_attr('sensor.dates', 'weekdaynumber')|int +1 %}
        {% set collectweek = state_attr('input_select.collect_compost','options').index(states('input_select.collect_compost'))|int -1 %}
        {% set week = state_attr('sensor.dates', 'weekofyear')|int %2 %}
        {% set time = '14:00' %}
        {% set allweeks = state_attr('sensor.collect_compost_week','summer') == 'on' %}
        {% set selected = states('input_select.collect_compost')|replace('Odd/','')|replace('Even/','')|replace('All/','') %}
        {% set now = state_attr('sensor.times', 'short') %}
        
        {% if today >= 7 %}
          {% set today = 0 %}
          {% set week = (week+1)%2 %}
        {% endif %}
        
        {% if collectweek >= 10 %}{% set collectweek = 2 %}{% set allweeks = true %}
        {% elif collectweek >= 5 %}{% set collectweek = 0 %}
        {% else %}{% set collectweek = 1 %}
        {% endif %}
        
        {% if ((today > collectday) or ((today == collectday) and (now >= time))) %}{% set passed = true %}
        {% elif ((today < collectday) or ((today == collectday) and (now < time))) %}{% set passed = false %}
        {% endif %}
        
        {% if collectweek == week or allweeks %}{% set thisweek = true %}
        {% else %}{% set thisweek = false %}
        {% endif %}
        
        {% if not enabled %}
          Disabled
        {% elif thisweek and not passed %}
          {% if today+1 == collectday %}
            Tomorrow
          {% elif today == collectday %}
            Today
          {% elif today < collectday %}
            Next {{ selected }}
          {% endif %}
        {% elif (thisweek and passed and allweeks) or (not thisweek and passed) %}
          Next {{ selected }}
        {% elif thisweek and passed and not allweeks %}
          In 2 {{ selected }}s
        {% elif not thisweek and not passed %}
          {{ selected }} Next Week
        {% else %}
          Error
        {% endif %}
      attributes:
        friendly_name: Compost Collect
        displayName: COMPOST
        summer: >
          {% set year_start = state_attr('input_datetime.collect_compost_start', 'year')|int %}
          {% set month_start = state_attr('input_datetime.collect_compost_start', 'month')|int %}
          {% set day_start = state_attr('input_datetime.collect_compost_start', 'day')|int %}
          {% set year_end = state_attr('input_datetime.collect_compost_end', 'year')|int %}
          {% set month_end = state_attr('input_datetime.collect_compost_end', 'month')|int %}
          {% set day_end = state_attr('input_datetime.collect_compost_end', 'day')|int %}
          {% set year = state_attr('sensor.dates', 'year')|int %}
          {% set month = state_attr('sensor.dates', 'month')|int %}
          {% set day = state_attr('sensor.dates', 'day')|int %}
          {% set enable = year_start >= year and year_end >= year %}
          
          {% set start = month > month_start or (month == month_start and day >= day_start) %}
          {% set end = month < month_end or (month == month_end and day <= day_end) %}
          
          {% if not enable %}
            disabled
          {% elif start and end %}
            on
          {% else %}
            off
          {% endif %}
        today: >
          {% set time = '14:00' %}
          {% set now = state_attr('sensor.times', 'short') %}
          {% set today = is_state('sensor.collect_compost_week', 'Today') and now < time %}
          
          {% if today %}
            on
          {% else %}
            off
          {% endif %}
        tomorrow: >
          {% set tomorrow = is_state('sensor.collect_compost_week', 'Tomorrow') %}
          
          {% if tomorrow %}
            on
          {% else %}
            off
          {% endif %}
        thisweek: >
          {% if ' Next ' in states('sensor.collect_compost_week') %}
            off
          {% elif 'Next ' in states('sensor.collect_compost_week') or is_state('sensor.collect_compost_week', 'Today') or is_state('sensor.collect_compost_week', 'Tomorrow') %}
            on
          {% else %}
            off
          {% endif %}
        
    - unique_id: collect_compost_summer_mode
      #name: Compost Summer Mode
      icon: >
        {% if state_attr('sensor.collect_compost_week', 'summer') == 'on'  %}
          mdi:tree
        {% elif state_attr('sensor.collect_compost_week', 'summer') == 'off'  %}
          mdi:snowflake
        {% else %}
          mdi:sprout-outline
        {% endif %}
      state: >
        {% if state_attr('sensor.collect_compost_week', 'summer') == 'on' %}
          Weekly
        {% elif state_attr('sensor.collect_compost_week', 'summer') == 'off' %}
          Fortnightly
        {% else %}
          Disabled
        {% endif %}
      attributes:
        friendly_name: Compost Summer Mode
        