####################################################
# TEMPLATES - HA                                   #
####################################################

  - sensor:

  #Home Assistant uptime
    - name: Time Online
      #unique_id: time_online
      icon: mdi:clock
      state: >
        {% set value = states('sensor.uptime') %}
        {% set last_updated = as_timestamp(strptime(value, "%Y-%m-%d  %H:%M:%S")) %}
        {% set uptime = now().timestamp() - last_updated %}
        {% set days = (uptime / 86400) | float %}
        {% set hours = (days * 24) | float %}
        {% set minutes = (hours * 60) | float %}
        
        {% if days >= 1.0 %}
          {{ days | round(2) }} days ago
        {% elif hours >= 1.0 %}
          {{ hours | round(1) }} hours ago
        {% else %}
          {{ minutes | round(0) }} minutes ago
        {% endif %}
