####################################################
# TEMPLATES - DOORS & LOCKS                        #
####################################################

  - sensor:
  
    - name: Lock Passcode OK
      #unique_id: lock_passcode_ok
      state: >
        {% set string = states('input_text.doorlock_passcode_list') %}
        {% set passcode = states('input_text.doorlock_passcode') %}
        {% set ok = namespace(found=False) %}
        {% for word in string.split() %}
          {% if passcode == word %}
            {% set ok.found = True %}
          {% endif %}
        {% endfor %}
        
        {% if ok.found == true %}
          on
        {% else %}
          off
        {% endif %}

    - unique_id: house_fd_status
      #name: House Front Door
      availability: >
        {{ not is_state('lock.house_fd_lock', 'unavailable') }}
      state: >
        {% set locked = is_state('lock.house_fd_lock', 'locked') %}
        {% set closed = is_state('binary_sensor.house_fd_opened', 'off') %}
        {% set unavailable = is_state('lock.house_fd_lock', 'unavailable') %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed and locked %}
          Ok
        {% elif closed and not locked %}
          Unlocked
        {% elif not closed and not locked %}
          Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: House Front Door
        state: "{% if states('binary_sensor.house_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_fd_opened', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('binary_sensor.house_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_fd_opened', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('binary_sensor.house_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_fd_opened', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        #vcc_3v3: "{% if states('binary_sensor.house_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_fd_opened', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        battery:  "{% if states('lock.house_fd_lock') != 'unavailable' %}{{ state_attr('lock.house_fd_lock', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('binary_sensor.house_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_fd_opened', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('binary_sensor.house_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_fd_opened', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('binary_sensor.house_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_fd_opened', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
        locked: >
          {% if is_state('lock.house_fd_lock', 'locked') %}
            True
          {% elif is_state('lock.house_fd_lock', 'unlocked') %}
            False
          {% else %}
            NA
          {% endif %}
        closed: >
          {% if is_state('binary_sensor.house_fd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.house_fd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        bell: >
          {% if is_state('binary_sensor.house_fd_bell', 'on') %}
            True
          {% elif is_state('binary_sensor.house_fd_bell', 'off') %}
            False
          {% else %}
            NA
          {% endif %}

    - unique_id: house_sd_status
      #name: House Side Door
      availability: >
        {{ not is_state('lock.house_sd_lock', 'unavailable') }}
      state: >
        {% set locked = is_state('lock.house_sd_lock', 'locked') %}
        {% set closed = is_state('binary_sensor.house_sd_opened', 'off') %}
        {% set unavailable = is_state('lock.house_sd_lock', 'unavailable') %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed and locked %}
          Ok
        {% elif closed and not locked %}
          Unlocked
        {% elif not closed and not locked %}
          Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: House Side Door
        state: "{% if states('binary_sensor.house_sd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_sd_opened', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('binary_sensor.house_sd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_sd_opened', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('binary_sensor.house_sd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_sd_opened', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        #vcc_3v3: "{% if states('binary_sensor.house_sd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_sd_opened', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        battery:  "{% if states('lock.house_sd_lock') != 'unavailable' %}{{ state_attr('lock.house_sd_lock', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('binary_sensor.house_sd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_sd_opened', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('binary_sensor.house_sd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_sd_opened', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('binary_sensor.house_sd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_sd_opened', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
        locked: >
          {% if is_state('lock.house_sd_lock', 'locked') %}
            True
          {% elif is_state('lock.house_sd_lock', 'unlocked') %}
            False
          {% else %}
            NA
          {% endif %}
        closed: >
          {% if is_state('binary_sensor.house_sd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.house_sd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        bell: >
          {% if is_state('binary_sensor.house_sd_bell', 'on') %}
            True
          {% elif is_state('binary_sensor.house_sd_bell', 'off') %}
            False
          {% else %}
            NA
          {% endif %}

    - unique_id: house_bd_status
      #name: House Back Door
      availability: >
        {{ not is_state('lock.house_bd_lock', 'unavailable') }}
      state: >
        {% set locked = is_state('lock.house_bd_lock', 'locked') %}
        {% set closed = is_state('binary_sensor.house_bd_opened', 'off') %}
        {% set unavailable = is_state('lock.house_bd_lock', 'unavailable') %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed and locked %}
          Ok
        {% elif closed and not locked %}
          Unlocked
        {% elif not closed and not locked %}
          Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: House Back Door
        state: "{% if states('binary_sensor.house_bd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_bd_opened', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('binary_sensor.house_bd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_bd_opened', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('binary_sensor.house_bd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_bd_opened', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        #vcc_3v3: "{% if states('binary_sensor.house_bd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_bd_opened', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        battery:  "{% if states('lock.house_bd_lock') != 'unavailable' %}{{ state_attr('lock.house_bd_lock', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('binary_sensor.house_bd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_bd_opened', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('binary_sensor.house_bd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_bd_opened', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('binary_sensor.house_bd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.house_bd_opened', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
        locked: >
          {% if is_state('lock.house_bd_lock', 'locked') %}
            True
          {% elif is_state('lock.house_bd_lock', 'unlocked') %}
            False
          {% else %}
            NA
          {% endif %}
        closed: >
          {% if is_state('binary_sensor.house_bd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.house_bd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        bell: >
          {% if is_state('binary_sensor.house_bd_bell', 'on') %}
            True
          {% elif is_state('binary_sensor.house_bd_bell', 'off') %}
            False
          {% else %}
            NA
          {% endif %}

    - unique_id: garage_fd_status
      #name: Garage Front Door
      availability: >
        {{ not is_state('lock.garage_fd_lock', 'unavailable') }}
      state: >
        {% set locked = is_state('lock.garage_fd_lock', 'locked') %}
        {% set closed = is_state('binary_sensor.garage_fd_opened', 'off') %}
        {% set unavailable = is_state('lock.garage_fd_lock', 'unavailable') %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed and locked %}
          Ok
        {% elif closed and not locked %}
          Unlocked
        {% elif not closed and not locked %}
          Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: Garage Front Door
        state: "{% if states('binary_sensor.garage_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_fd_opened', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('binary_sensor.garage_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_fd_opened', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('binary_sensor.garage_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_fd_opened', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        #vcc_3v3: "{% if states('binary_sensor.garage_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_fd_opened', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        battery:  "{% if states('lock.garage_fd_lock') != 'unavailable' %}{{ state_attr('lock.garage_fd_lock', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('binary_sensor.garage_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_fd_opened', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('binary_sensor.garage_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_fd_opened', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('binary_sensor.garage_fd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_fd_opened', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
        locked: >
          {% if is_state('lock.garage_fd_lock', 'locked') %}
            True
          {% elif is_state('lock.garage_fd_lock', 'unlocked') %}
            False
          {% else %}
            NA
          {% endif %}
        closed: >
          {% if is_state('binary_sensor.garage_fd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.garage_fd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        bell: >
          {% if is_state('binary_sensor.garage_fd_bell', 'on') %}
            True
          {% elif is_state('binary_sensor.garage_fd_bell', 'off') %}
            False
          {% else %}
            NA
          {% endif %}
          
    - unique_id: garage_bd_status
      #name: Garage Back Door
      availability: >
        {{ not is_state('binary_sensor.garage_bd_opened', 'unavailable') }}
      state: >
        {% set closed = is_state('binary_sensor.garage_bd_opened', 'off') %}
        {% set unavailable = is_state('binary_sensor.garage_bd_opened', 'unavailable') %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed %}
          Ok
        {% elif not closed %}
          Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: Garage Back Door
        closed: >
          {% if is_state('binary_sensor.garage_bd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.garage_bd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
          
    - unique_id: garage_cd_status
      #name: Garage Car Door
      availability: >
        {{ not is_state('cover.garage_cd_opener', 'unavailable') and not is_state('sensor.garage_cd_raw', 'unavailable') }}
      state: >
        {% set fullOpen = is_state('sensor.garage_cd_raw', 'opened') %}
        {% set closed = is_state('sensor.garage_cd_raw', 'closed') %}
        {% set unavailable = is_state('cover.garage_cd_opener', 'unavailable') or is_state('sensor.garage_cd_raw', 'unavailable') %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed %}
          Ok
        {% elif not closed and not fullOpen %}
          Opened
        {% elif not closed and fullOpen %}
          Fully Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: Garage Car Door
        state: "{% if states('binary_sensor.garage_cd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_cd_opened', 'state') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if states('binary_sensor.garage_cd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_cd_opened', 'version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if states('binary_sensor.garage_cd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_cd_opened', 'date') }}{% else %}{{ 'unknown' }}{% endif %}"
        vcc_3v3: "{% if states('binary_sensor.garage_cd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_cd_opened', 'Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        battery:  "{% if states('lock.garage_cd_lock') != 'unavailable' %}{{ state_attr('lock.garage_cd_lock', 'battery') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if states('binary_sensor.garage_cd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_cd_opened', 'wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if states('binary_sensor.garage_cd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_cd_opened', 'wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if states('binary_sensor.garage_cd_opened') != 'unavailable' %}{{ state_attr('binary_sensor.garage_cd_opened', 'wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
        closed: >
          {% if is_state('binary_sensor.garage_cd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.garage_cd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        position: >
          {% if is_state('sensor.garage_cd_raw', 'opened') %}
            100
          {% elif is_state('sensor.garage_cd_raw', 'closed') %}
            0
          {% else %}
            50
          {% endif %}
        
    - unique_id: shed_fd_status
      #name: Shed Doors
      availability: >
        {{ not is_state('lock.shed_fd_lock', 'unavailable') and not is_state('binary_sensor.shed_fd_opened', 'unavailable') }}
      state: >
        {% set locked = is_state('lock.shed_fd_lock', 'locked') %}
        {% set main = is_state('binary_sensor.shed_fd_opened', 'off') %}
        {% set left = is_state('binary_sensor.shed_ld_opened', 'off') %}
        {% set right = is_state('binary_sensor.shed_rd_opened', 'off') %}
        {% set unavailable = is_state('lock.shed_fd_lock', 'unavailable') %}
        
        {% set closed = main and left and right %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed and locked %}
          Ok
        {% elif closed and not locked %}
          Unlocked
        {% elif not closed and not locked %}
          Opened
        {% elif not (left and right) and closed and locked %}
          Sides Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: Shed Doors
        locked: >
          {% if is_state('lock.shed_fd_lock', 'locked') %}
            True
          {% elif is_state('lock.shed_fd_lock', 'unlocked') %}
            False
          {% else %}
            NA
          {% endif %}
        closed: >
          {% if is_state('binary_sensor.shed_fd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.shed_fd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        left: >
          {% if is_state('binary_sensor.shed_ld_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.shed_ld_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        right: >
          {% if is_state('binary_sensor.shed_rd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.shed_rd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
        
    - unique_id: pool_fd_status
      #name: Pool Cabin Door
      availability: >
        {{ not is_state('lock.pool_fd_lock', 'unavailable') and not is_state('binary_sensor.pool_fd_opened', 'unavailable') }}
      state: >
        {% set locked = is_state('lock.pool_fd_lock', 'locked') %}
        {% set closed = is_state('binary_sensor.pool_fd_opened', 'off') %}
        {% set unavailable = is_state('lock.pool_fd_lock', 'unavailable') %}
        
        {% set locked = closed %}
        
        {% if unavailable %}
          Unavailable
        {% elif closed and locked %}
          Ok
        {% elif closed and not locked %}
          Unlocked
        {% elif not closed and not locked %}
          Opened
        {% else %}
          ERROR
        {% endif %}
      attributes:
        friendly_name: Pool Cabin Door
        locked: >
          {% if is_state('lock.pool_fd_lock', 'locked') %}
            True
          {% elif is_state('lock.pool_fd_lock', 'unlocked') %}
            False
          {% else %}
            NA
          {% endif %}
        closed: >
          {% if is_state('binary_sensor.pool_fd_opened', 'off') %}
            True
          {% elif is_state('binary_sensor.pool_fd_opened', 'on') %}
            False
          {% else %}
            NA
          {% endif %}
