####################################################
# TEMPLATES - MOON                                 #
####################################################

  - sensor:

    - name: Moon Phases
      #unique_id: moon_phases
      #icon: mdi:none
      state: >
        {{ states('sensor.moon').replace('_',' ') | title }}
      picture: >
        {% set state = states('sensor.moon').title().replace('_','').replace(' ','') %}
        {{ '/local/images/MoonPhases/N{}.jpg'.format(state) }}
