####################################################
# TEMPLATES - ROOMS                                #
####################################################

########## MASSAGE ROOM ##########

  - sensor:

    - name: Massage Room Status
      #unique_id: massage_room_status
      icon: mdi:pen
      availability: >-
        {{ not is_state('switch.massage_room_appliances', 'unavailable') and
           not is_state('sensor.massage_room_data','unavailable') and
           not is_state('sensor.massage_room_power','unavailable') }}
      state: >
        {% if is_state('switch.massage_room_appliances', 'on') %}
          {% if states('sensor.massage_room_power') | float >= 2 %}
            On
          {% else %}
            Off
          {% endif %}
        {% else %}
          Ready
        {% endif %}
      attributes:
        state: "{% if state_attr('sensor.massage_room_data','POWER') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_data','POWER') | round(3) }}{% endif %}"
        power: "{% if state_attr('sensor.massage_room_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_power','ENERGY').Power | round(3) }}{% endif %}"
        voltage: "{% if state_attr('sensor.massage_room_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_power','ENERGY').Voltage | round(0) }}{% endif %}"
        current: "{% if state_attr('sensor.massage_room_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_power','ENERGY').Current | round(1) }}{% endif %}"
        p_factor: "{% if state_attr('sensor.massage_room_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_power','ENERGY').Factor | round(2) }}{% endif %}"
        today: "{% if state_attr('sensor.massage_room_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_power','ENERGY').Today | round(3) }}{% endif %}"
        yesterday: "{% if state_attr('sensor.massage_room_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_power','ENERGY').Yesterday | round(3) }}{% endif %}"
        total: "{% if state_attr('sensor.massage_room_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_power','ENERGY').Total | round(3) }}{% endif %}"
        wifi_rssi: "{% if state_attr('sensor.massage_room_data','Wifi') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_data','Wifi').Signal }}{% endif %}"
        wifi_percent: "{% if state_attr('sensor.massage_room_data','Wifi') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.massage_room_data','Wifi').RSSI }}{% endif %}"
    
########## THINKERING ROOM ##########

    - name: Soldering Station Status
      #unique_id: soldering_station_status
      icon: mdi:pen
      availability: >-
        {{ not is_state('switch.soldering_station', 'unavailable') and
           not is_state('sensor.soldering_station_data','unavailable') and
           not is_state('sensor.soldering_station_power','unavailable') }}
      state: >
          {% if is_state('switch.soldering_station', 'on') %}
            {% if states('sensor.soldering_station_power') | float >= 2 %}
              On
            {% else %}
              Off
            {% endif %}
          {% else %}
            Ready
          {% endif %}
      attributes:
        state: "{% if state_attr('sensor.soldering_station_data','POWER') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_data','POWER') | round(3) }}{% endif %}"
        power: "{% if state_attr('sensor.soldering_station_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_power','ENERGY').Power | round(3) }}{% endif %}"
        voltage: "{% if state_attr('sensor.soldering_station_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_power','ENERGY').Voltage | round(0) }}{% endif %}"
        current: "{% if state_attr('sensor.soldering_station_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_power','ENERGY').Current | round(1) }}{% endif %}"
        p_factor: "{% if state_attr('sensor.soldering_station_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_power','ENERGY').Factor | round(2) }}{% endif %}"
        today: "{% if state_attr('sensor.soldering_station_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_power','ENERGY').Today | round(3) }}{% endif %}"
        yesterday: "{% if state_attr('sensor.soldering_station_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_power','ENERGY').Yesterday | round(3) }}{% endif %}"
        total: "{% if state_attr('sensor.soldering_station_power','ENERGY') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_power','ENERGY').Total | round(3) }}{% endif %}"
        wifi_rssi: "{% if state_attr('sensor.soldering_station_data','Wifi') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_data','Wifi').Signal }}{% endif %}"
        wifi_percent: "{% if state_attr('sensor.soldering_station_data','Wifi') == None %}{{ 'unknown' }}{% else %}{{ state_attr('sensor.soldering_station_data','Wifi').RSSI }}{% endif %}"

########## MASTER BEDROOM ##########
    
    - name: Master Bed Presence
      #unique_id: master_bed_presence
      icon: mdi:bed-empty
      availability: >
        {{ not is_state('sensor.master_bed_raw', 'unavailable') }}
      # state: >
      #   {% set weight = states('sensor.master_bed_raw') | float %}
      #   {% set jean = is_state('person.jean_gauthier', 'home') %}
      #   {% set cindy = is_state('person.cindy_fortin', 'home') %}
        
      #   {% if weight < 30 %}
      #     Empty
      #   {% elif weight < 200 %}
      #     Mi-Loup
      #   {% elif weight < 900 and cindy %}
      #     Cindy
      #   {% elif weight < 1200 and jean %}
      #     Jean
      #   {% elif cindy and jean %}
      #     Cindy & Jean
      #   {% else %}
      #     ERROR
      #   {% endif %}
      state: >
        {% set weight = states('sensor.master_bed_raw') | float %}
        {% set jean = is_state('person.jean_gauthier', 'home') %}
        {% set cindy = is_state('person.cindy_fortin', 'home') %}
        
        {% if weight < 30 %}
          Empty
        {% elif weight < 200 %}
          Mi-Loup
        {% else%}
          Someone In Bed
        {% endif %}
      attributes:
        state: "{% if not is_state('switch.master_bed_tare','unavailable') %}{{ states('switch.master_bed_tare') }}{% else %}{{ 'unknown' }}{% endif %}"
        version: "{% if not is_state('switch.master_bed_tare','unavailable') %}{{ state_attr('switch.master_bed_tare','version') }}{% else %}{{ 'unknown' }}{% endif %}"
        date: "{% if not is_state('switch.master_bed_tare','unavailable') %}{{ state_attr('switch.master_bed_tare','date') }}{% else %}{{ 'unknown' }}{% endif %}"
        vcc_3v3: "{% if not is_state('switch.master_bed_tare','unavailable') %}{{ state_attr('switch.master_bed_tare','Vcc3V3') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_ssid: "{% if not is_state('switch.master_bed_tare','unavailable') %}{{ state_attr('switch.master_bed_tare','wifi_ssid') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_rssi: "{% if not is_state('switch.master_bed_tare','unavailable') %}{{ state_attr('switch.master_bed_tare','wifi_rssi') }}{% else %}{{ 'unknown' }}{% endif %}"
        wifi_percent: "{% if not is_state('switch.master_bed_tare','unavailable') %}{{ state_attr('switch.master_bed_tare','wifi_percent') }}{% else %}{{ 'unknown' }}{% endif %}"
        raw_value: "{{ states('sensor.master_bed_raw') }}"
        calib: "{% if not is_state('sensor.master_bed_raw','unavailable') %}{{ state_attr('sensor.master_bed_raw','calib') }}{% else %}{{ 'unknown' }}{% endif %}"
          