####################################################
# SWITCHES - MQTT - WELL                           #
####################################################

######### WELL MAIN #########
  - name: Well Master 12V
    state_topic: "Well/Control/Relay/Stts"
    command_topic: "Well/Control/Relay/Cmd"
    value_template: '{{ value_json.r8 }}'
    availability:
      - topic: "Well/Control/LWT"
    payload_on: '{"r8":"ON"}'
    payload_off: '{"r8":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    
  - name: Well Pit Light
    state_topic: "Well/Control/Relay/Stts"
    command_topic: "Well/Control/Relay/Cmd"
    value_template: '{{ value_json.r7 }}'
    availability:
      - topic: "Well/Control/LWT"
    payload_on: '{"r7":"ON"}'
    payload_off: '{"r7":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    json_attributes_topic: "Well/Control/LWT"
    json_attributes_template: >
      {{ '{"appliances": "light"' + 
      ', "watts": 9}' }}
    
  - name: Well Pit Heating Light
    state_topic: "Well/Control/Relay/Stts"
    command_topic: "Well/Control/Relay/Cmd"
    value_template: '{{ value_json.r6 }}'
    availability:
      - topic: "Well/Control/LWT"
    payload_on: '{"r6":"ON"}'
    payload_off: '{"r6":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    json_attributes_topic: "Well/Control/LWT"
    json_attributes_template: >
      {{ '{"appliances": "light"' + 
      ', "watts": 75}' }}
    
  - name: Pond Filler Valve
    icon: mdi:debug-step-out
    state_topic: "Well/Control/Relay/Stts"
    command_topic: "Well/Control/Relay/Cmd"
    value_template: '{{ value_json.r1 }}'
    payload_on: '{"r1":"ON"}'
    payload_off: '{"r1":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    availability:
      - topic: "Well/Control/LWT"
    qos: 0
    
  - name: Frontyard Irrigation
    state_topic: "Well/Control/Relay/Stts"
    command_topic: "Well/Control/Relay/Cmd"
    value_template: '{{ value_json.r2 }}'
    payload_on: '{"r2":"ON"}'
    payload_off: '{"r2":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    availability:
      - topic: "Well/Control/LWT"
    qos: 0
    
