####################################################
# SWITCHES - MQTT - GARAGE                         #
####################################################

######### GARAGE MAIN #########
  - name: Garage Front Light
    state_topic: "Garage/Control/Relay/Stts"
    command_topic: "Garage/Control/Relay/Cmd"
    value_template: '{{ value_json.r1 }}'
    availability:
      - topic: "Garage/Control/LWT"
    payload_on: '{"r1":"ON"}'
    payload_off: '{"r1":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    json_attributes_topic: "Garage/Control/LWT"
    json_attributes_template: >
      {{ '{"appliances": "light"' + 
      ', "watts": 10}' }}
    
  - name: Garage Front Power
    state_topic: "Garage/Control/Relay/Stts"
    command_topic: "Garage/Control/Relay/Cmd"
    value_template: '{{ value_json.r2 }}'
    availability:
      - topic: "Garage/Control/LWT"
    payload_on: '{"r2":"ON"}'
    payload_off: '{"r2":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    json_attributes_topic: "Garage/Control/LWT"
    json_attributes_template: >
      {{ '{"appliances": "light"' + 
      ', "watts": 25}' }}
    
## 2022-02-08 - RELAY #16 is dead, do not use
## 2022-02-13 - Repaired with air gaps, works now
  - name: Garage Air Compressor
    icon: mdi:compass
    state_topic: "Garage/Control/Relay/Stts"
    command_topic: "Garage/Control/Relay/Cmd"
    value_template: '{{ value_json.r16 }}'
    availability:
      - topic: "Garage/Control/LWT"
    payload_on: '{"r16":"ON"}'
    payload_off: '{"r16":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    
  - name: Garage Front Heater
    icon: mdi:radiator
    state_topic: "Garage/Control/Relay/Stts"
    command_topic: "Garage/Control/Relay/Cmd"
    value_template: '{{ value_json.r15 }}'
    availability:
      - topic: "Garage/Control/LWT"
    payload_on: '{"r15":"ON"}'
    payload_off: '{"r15":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    json_attributes_topic: "Garage/Control/LWT"
    json_attributes_template: >
      {{ '{"appliances": "heater"' + 
      ', "watts": 4774}' }}
    
  - name: Garage Rear Heater
    icon: mdi:radiator
    state_topic: "Garage/Control/Relay/Stts"
    command_topic: "Garage/Control/Relay/Cmd"
    value_template: '{{ value_json.r14 }}'
    availability:
      - topic: "Garage/Control/LWT"
    payload_on: '{"r14":"ON"}'
    payload_off: '{"r14":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    json_attributes_topic: "Garage/Control/LWT"
    json_attributes_template: >
      {{ '{"appliances": "heater"' + 
      ', "watts": 4774}' }}
      
  - name: Garage Thermostat Reset
    icon: mdi:reload-alert
    state_topic: "Garage/Control/Relay/Stts"
    command_topic: "Garage/Control/Relay/Cmd"
    value_template: '{{ value_json.r10 }}'
    availability:
      - topic: "Garage/Control/LWT"
    payload_on: '{"r10":"ON","h10":"5"}'
    payload_off: '{"r10":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0

#NOT USED AS A MQTT SWITCH - Directly programmed in the arduino as a doorchime trigger (see auto_allothers.yaml ==> automation.doorchime_trigger)
  # - name: Garage Front Doorchime
    # icon: mdi:radiator
    # state_topic: "Garage/Control/Relay/Stts"
    # command_topic: "Garage/Control/Relay/Cmd"
    # value_template: '{{ value_json.r9 }}'
    # availability:
      # - topic: "Garage/Control/LWT"
    # payload_on: '{"r9":"ON"}'
    # payload_off: '{"r9":"OFF"}'
    # state_on: "ON"
    # state_off: "OFF"
    # qos: 0
      
######### GARAGE SLAVE #########

#NOT USED AS A MQTT SWITCH - Directly programmed in the arduino as a doorchime trigger (see auto_allothers.yaml ==> automation.doorchime_trigger)
  # - name: Garage Rear Doorchime
    # icon: mdi:radiator
    # state_topic: "Garage/Slave/Relay/Stts"
    # command_topic: "Garage/Slave/Relay/Cmd"
    # value_template: '{{ value_json.r1 }}'
    # availability:
      # - topic: "Garage/Slave/LWT"
    # payload_on: '{"r1":"ON"}'
    # payload_off: '{"r1":"OFF"}'
    # state_on: "ON"
    # state_off: "OFF"
    # qos: 0
    
  #Air purge needs a hold value in second(s)
  - name: Air Compressor Purge
    state_topic: "Garage/Slave/Relay/Stts"
    command_topic: "Garage/Slave/Relay/Cmd"
    value_template: '{{ value_json.r4 }}'
    availability:
      - topic: "Garage/Slave/LWT"
    #payload_on: '{"r4":"ON","h4":"{{(states.input_number.air_compressor_purge.state|float)}}"}' #NOT WORKING
    payload_on: '{"r4":"ON", "h4":"1.0"}'
    payload_off: '{"r4":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    
  # Valve need to activate the direction relay first then activate the main relay
  - name: Garage Air Valve
    state_topic: "Garage/Slave/Relay/Stts"
    command_topic: "Garage/Slave/Relay/Cmd"
    value_template: '{{ value_json.r8 }}'
    availability:
      - topic: "Garage/Slave/LWT"
    payload_on: '{"r8":"ON"}'
    payload_off: '{"r8":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    
  - name: Garage Air Valve Open
    state_topic: "Garage/Slave/Relay/Stts"
    command_topic: "Garage/Slave/Relay/Cmd"
    value_template: '{{ value_json.r6 }}'
    availability:
      - topic: "Garage/Slave/LWT"
    payload_on: '{"r6":"ON"}'
    payload_off: '{"r6":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    
  # Valve need to activate the direction relay first then activate the main relay
  - name: House Air Valve
    state_topic: "Garage/Slave/Relay/Stts"
    command_topic: "Garage/Slave/Relay/Cmd"
    value_template: '{{ value_json.r7 }}'
    availability:
      - topic: "Garage/Slave/LWT"
    payload_on: '{"r7":"ON"}'
    payload_off: '{"r7":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0

  - name: House Air Valve Open
    state_topic: "Garage/Slave/Relay/Stts"
    command_topic: "Garage/Slave/Relay/Cmd"
    value_template: '{{ value_json.r5 }}'
    availability:
      - topic: "Garage/Slave/LWT"
    payload_on: '{"r5":"ON"}'
    payload_off: '{"r5":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    qos: 0
    
