    type: vertical-stack
    cards:
      - type: custom:mushroom-title-card
        title: House
        #subtitle: Floor Heater
        alignment: justify
#Comfort
      # - type: custom:mushroom-chips-card
        # chips:
          # # - type: menu
          # - type: entity
            # entity: sensor.entrance_temperature
            # icon_color: orange
          # - type: entity
            # entity: sensor.entrance_humidity
            # icon: mdi:water-percent
            # icon_color: indigo
          # - type: entity
            # entity: sensor.entrance_temperature
            # icon: mdi:heat-wave
            # icon_color: red
#Doors
      - type: custom:mushroom-chips-card
        chips:
          - type: template
            tap_action:
              action: more-info
            entity: sensor.house_fd_status
            icon: |-
              {% set state = states('sensor.house_fd_status') %}
              {% if state == 'Ok' %}
                mdi:shield-lock
              {% elif state == 'Ok*' %}
                mdi:shield-alert
              {% elif state == 'Unlocked' %}
                mdi:shield-remove
              {% elif state == 'Opened' %}
                mdi:door-open         
              {% else %}
                mdi:close-octagon
              {% endif %}
            icon_color: |-
              {% set state = states('sensor.house_fd_status') %}
              {% if state == 'Ok' %}
                green
              {% elif state == 'Ok*' %}
                orange
              {% elif state == 'Unlocked' %}
                red
              {% elif state == 'Opened' %}
                var(--state-icon-active-color)
              {% elif state == 'unavailable' %}
                var(--state-icon-unavailable-color)
              {% else %}
                red
              {% endif %}
            content: |-
              {% set state = states('sensor.house_fd_status') %}
              Front Door {{state}}

          - type: template
            tap_action:
              action: more-info
            entity: binary_sensor.house_fd_bell
            icon: |-
              {% if is_state('binary_sensor.house_fd_bell', 'off') %}
                mdi:bell-outline
              {% else %}
                mdi:bell-ring
              {% endif %}
            icon_color: |-
              {% if is_state('binary_sensor.house_fd_bell', 'off') %}
                gray
              {% else %}
                yellow
              {% endif %}
            content: |-
              {% if is_state('binary_sensor.house_fd_bell', 'on') %}
                Ring
              {% else %}
                Off
              {% endif %}
          - type: entity
            entity: input_number.doorchime_tf_volume
          - type: entity
            entity: input_select.doorchime_tf_sound
            
      - type: custom:mushroom-chips-card
        chips:
          - type: template
            tap_action:
              action: more-info
            entity: sensor.house_bd_status
            icon: |-
              {% set state = states('sensor.house_bd_status') %}
              {% if state == 'Ok' %}
                mdi:shield-lock
              {% elif state == 'Ok*' %}
                mdi:shield-alert
              {% elif state == 'Unlocked' %}
                mdi:shield-remove
              {% elif state == 'Opened' %}
                mdi:door-open         
              {% else %}
                mdi:close-octagon
              {% endif %}
            icon_color: |-
              {% set state = states('sensor.house_bd_status') %}
              {% if state == 'Ok' %}
                green
              {% elif state == 'Ok*' %}
                orange
              {% elif state == 'Unlocked' %}
                red
              {% elif state == 'Opened' %}
                var(--state-icon-active-color)
              {% elif state == 'unavailable' %}
                var(--state-icon-unavailable-color)
              {% else %}
                red
              {% endif %}
            content: |-
              {% set state = states('sensor.house_bd_status') %}
              Back Door {{state}}
              
          - type: template
            tap_action:
              action: more-info
            entity: binary_sensor.house_bd_bell
            icon: |-
              {% if is_state('binary_sensor.house_bd_bell', 'off') %}
                mdi:bell-outline
              {% else %}
                mdi:bell-ring
              {% endif %}
            icon_color: |-
              {% if is_state('binary_sensor.house_bd_bell', 'off') %}
                gray
              {% else %}
                yellow
              {% endif %}
            content: |-
              {% if is_state('binary_sensor.house_bd_bell', 'on') %}
                Ring
              {% else %}
                Off
              {% endif %}
          - type: entity
            entity: input_number.doorchime_bf_volume
          - type: entity
            entity: input_select.doorchime_bf_sound
        
#Lights
      - type: custom:mushroom-chips-card
        chips:
          - type: template
            tap_action:
              action: more-info
            entity: switch.front_door_light
            icon: |-
              {% if is_state('switch.front_door_light', 'on') %}
                mdi:lightbulb-on
              {% else %}
                mdi:lightbulb-off
              {% endif %}
            icon_color: |-
              {% if is_state('switch.front_door_light', 'off') %}
                grey
              {% else %}
                yellow
              {% endif %}
            content: |-
              {% if is_state('switch.front_door_light', 'on') %}
                Front On
              {% else %}
                Front Off
              {% endif %}
              
          - type: template
            tap_action:
              action: more-info
            entity: binary_sensor.lamppost_status
            icon: |-
              {% if is_state('binary_sensor.lamppost_status', 'on') %}
                mdi:lightbulb-on
              {% else %}
                mdi:lightbulb-off
              {% endif %}
            icon_color: |-
              {% if is_state('binary_sensor.lamppost_status', 'off') %}
                grey
              {% else %}
                yellow
              {% endif %}
            content: |-
              {% if is_state('binary_sensor.lamppost_status', 'on') %}
                LampPost On
              {% else %}
                LampPost Off
              {% endif %}
#Heaters
      - type: custom:mushroom-chips-card
        chips:
          - type: template
            tap_action:
              action: more-info
            entity: binary_sensor.entrance_heater_running
            icon: |-
              {% if is_state('binary_sensor.entrance_heater_running','on') %}
                mdi:radiator
              {% elif is_state('binary_sensor.entrance_heater_running','off') %}
                mdi:radiator-disabled
              {% else %}
                mdi:radiator-off
              {% endif %}
            icon_color: |-
              {% if is_state('binary_sensor.entrance_heater_running', 'off') %}
                grey
              {% else %}
                yellow
              {% endif %}
            content: |-
              {% if is_state('binary_sensor.entrance_heater_running', 'on') %}
                On
              {% else %}
                Off
              {% endif %}
              
          - type: template
            icon: mdi:ticket-percent
            icon_color: blue
            content: |-
              {% if state_attr('sensor.entrance_heater_power','duty_cycle') %}
                {% set duty = state_attr('sensor.entrance_heater_power','duty_cycle').split(' ')[0]|float(0) %}
              {% else %}
                {% set duty = 0 %}
              {% endif %}
              
              Duty Cycle {{ duty|round(1) }} %
#Energy
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: sensor.entrance_heater_power
            icon: mdi:transmission-tower
          - type: entity
            entity: sensor.entrance_heater_energy_daily
            icon: mdi:lightning-bolt
          - type: template
            icon: |-
              mdi:cash
            content: |-
              {% set energy = states('sensor.entrance_heater_energy_daily')|float(0) %}
              {% set cost = states('sensor.ted5000_utility_current_rate')|float(0) %}
              {{ (energy*cost)|round(5) }} $
#Comfort graphs
      # - type: horizontal-stack
        # cards:
          # - type: custom:mini-graph-card
            # entities:
              # - sensor.entrance_temperature
            # name: Temperature
            # hour24: true
            # hours_to_show: 24
            # cache: false
            # points_per_hour: 1
            # color: orange
            # line_color: orange
          # - type: custom:mini-graph-card
            # icon: mdi:water-percent
            # entities:
              # - sensor.entrance_humidity
            # name: Humidity
            # hour24: true
            # hours_to_show: 24
            # cache: false
            # points_per_hour: 1
            # color: steelblue
            # line_color: steelblue
          # - type: custom:mini-graph-card
            # entities:
              # - sensor.entrance_temperature
            # name: Floor
            # icon: mdi:heat-wave
            # hour24: true
            # hours_to_show: 24
            # cache: false
            # points_per_hour: 1
            # color: green
            # line_color: green
#Comfort thermostat            
      # - type: custom:mushroom-climate-card
        # entity: climate.entrance_heater
        # show_temperature_control: true
        # hvac_modes:
          # - 'heat'
          # - 'off'
        # icon: mdi:heat-wave
        # #layout: vertical
#Energy graphs
      # - type: horizontal-stack
        # cards:
          # - type: custom:mini-graph-card
            # entities:
              # - sensor.entrance_heater_power
            # name: Power
            # icon: mdi:transmission-tower
            # hour24: true
            # hours_to_show: 24
            # cache: false
            # points_per_hour: 0.5
            # color: green
            # line_color: green
            # #group_by: hour
          # - type: custom:mini-graph-card
            # entities:
              # - sensor.entrance_heater_energy_daily
            # name: Energy
            # icon: mdi:lightning-bolt
            # hour24: true
            # hours_to_show: 24
            # cache: false
            # show:
              # graph: bar
            # #bar_spacing: 6
            # aggregate_func: max
            # group_by: hour
            # color_thresholds:
              # - value: 0
                # color: "#00ff00f0"
              # - color: "#6fed00f0"
              # - color: "#98db00f0"
              # - color: "#b6c700f0"
              # - color: "#cdb200f0"
              # - color: "#df9b00f0"
              # - color: "#ee8200f0"
              # - color: "#f86600f0"
              # - color: "#fe4400f0"
              # - value: 10
                # color: "#ff0000f0"